/*
 * Generated by Bluespec Compiler, version 2023.01-6-g034050db (build 034050db)
 * 
 * On Fri May 12 17:05:38 IST 2023
 * 
 */
extern "C" {
  void fill_image();
  unsigned int initial_load();
  unsigned int lateral_load();
}
