/*
 * Generated by Bluespec Compiler, version 2023.01-6-g034050db (build 034050db)
 * 
 * On Fri May 12 17:05:38 IST 2023
 * 
 */
#include "bluesim_primitives.h"
#include "model_mkFlowTest.h"

#include <cstdlib>
#include <time.h>
#include "bluesim_kernel_api.h"
#include "bs_vcd.h"
#include "bs_reset.h"


/* Constructor */
MODEL_mkFlowTest::MODEL_mkFlowTest()
{
  mkFlowTest_instance = NULL;
}

/* Function for creating a new model */
void * new_MODEL_mkFlowTest()
{
  MODEL_mkFlowTest *model = new MODEL_mkFlowTest();
  return (void *)(model);
}

/* Schedule functions */

static void schedule_posedge_CLK(tSimStateHdl simHdl, void *instance_ptr)
       {
	 MOD_mkFlowTest &INST_top = *((MOD_mkFlowTest *)(instance_ptr));
	 tUInt8 DEF_INST_top_INST_px_DEF_NOT_mem_rRdPtr_read__9_PLUS_100000_68_EQ_mem_r_ETC___d270;
	 tUInt8 DEF_INST_top_INST_px_DEF_NOT_cx2_78_ULT_width_79_80___d281;
	 tUInt8 DEF_INST_top_INST_px_DEF_cx2_78_ULT_width_79___d280;
	 tUInt8 DEF_INST_top_INST_px_DEF_inQ_i_notEmpty____d325;
	 tUInt32 DEF_INST_top_INST_px_DEF_b__h14773;
	 tUInt8 DEF_INST_top_INST_px_DEF_CAN_FIRE_RL_inCLK;
	 tUInt8 DEF_INST_top_INST_px_DEF_WILL_FIRE_RL_inCLK;
	 tUInt8 DEF_INST_top_INST_px_DEF_CAN_FIRE_RL_mem_portA;
	 tUInt8 DEF_INST_top_INST_px_DEF_WILL_FIRE_RL_mem_portA;
	 tUInt8 DEF_INST_top_INST_px_DEF_CAN_FIRE_RL_mem_portB;
	 tUInt8 DEF_INST_top_INST_px_DEF_WILL_FIRE_RL_mem_portB;
	 tUInt8 DEF_INST_top_INST_px_DEF_CAN_FIRE_RL_mem_portB_read_data;
	 tUInt8 DEF_INST_top_INST_px_DEF_WILL_FIRE_RL_mem_portB_read_data;
	 tUInt8 DEF_INST_top_INST_px_DEF_CAN_FIRE_RL__Q2;
	 tUInt8 DEF_INST_top_INST_px_DEF_WILL_FIRE_RL__Q2;
	 tUInt8 DEF_INST_top_INST_px_DEF_CAN_FIRE_RL__Q3;
	 tUInt8 DEF_INST_top_INST_px_DEF_WILL_FIRE_RL__Q3;
	 tUInt8 DEF_INST_top_INST_px_DEF_CAN_FIRE_RL__Q4;
	 tUInt8 DEF_INST_top_INST_px_DEF_WILL_FIRE_RL__Q4;
	 tUInt8 DEF_INST_top_INST_px_DEF_CAN_FIRE_RL__Q5;
	 tUInt8 DEF_INST_top_INST_px_DEF_WILL_FIRE_RL__Q5;
	 tUInt8 DEF_INST_top_INST_px_DEF_CAN_FIRE_RL__Q6;
	 tUInt8 DEF_INST_top_INST_px_DEF_WILL_FIRE_RL__Q6;
	 tUInt8 DEF_INST_top_INST_px_DEF_CAN_FIRE_RL__Q7;
	 tUInt8 DEF_INST_top_INST_px_DEF_WILL_FIRE_RL__Q7;
	 tUInt8 DEF_INST_top_INST_px_DEF_CAN_FIRE_RL__Q1_1;
	 tUInt8 DEF_INST_top_INST_px_DEF_WILL_FIRE_RL__Q1_1;
	 tUInt8 DEF_INST_top_INST_px_DEF_CAN_FIRE_RL__Q2_1;
	 tUInt8 DEF_INST_top_INST_px_DEF_WILL_FIRE_RL__Q2_1;
	 tUInt8 DEF_INST_top_INST_px_DEF_CAN_FIRE_RL__Q3_1;
	 tUInt8 DEF_INST_top_INST_px_DEF_WILL_FIRE_RL__Q3_1;
	 tUInt8 DEF_INST_top_INST_px_DEF_CAN_FIRE_RL__Q4_1;
	 tUInt8 DEF_INST_top_INST_px_DEF_WILL_FIRE_RL__Q4_1;
	 tUInt8 DEF_INST_top_INST_px_DEF_CAN_FIRE_RL__Q5_1;
	 tUInt8 DEF_INST_top_INST_px_DEF_WILL_FIRE_RL__Q5_1;
	 tUInt8 DEF_INST_top_INST_px_DEF_CAN_FIRE_RL__Q6_1;
	 tUInt8 DEF_INST_top_INST_px_DEF_WILL_FIRE_RL__Q6_1;
	 tUInt8 DEF_INST_top_INST_px_DEF_CAN_FIRE_RL__Q7_1;
	 tUInt8 DEF_INST_top_INST_px_DEF_WILL_FIRE_RL__Q7_1;
	 tUInt8 DEF_INST_top_INST_px_DEF_CAN_FIRE_RL__Q1_2;
	 tUInt8 DEF_INST_top_INST_px_DEF_WILL_FIRE_RL__Q1_2;
	 tUInt8 DEF_INST_top_INST_px_DEF_CAN_FIRE_RL__Q2_2;
	 tUInt8 DEF_INST_top_INST_px_DEF_WILL_FIRE_RL__Q2_2;
	 tUInt8 DEF_INST_top_INST_px_DEF_CAN_FIRE_RL__Q3_2;
	 tUInt8 DEF_INST_top_INST_px_DEF_WILL_FIRE_RL__Q3_2;
	 tUInt8 DEF_INST_top_INST_px_DEF_CAN_FIRE_RL__Q4_2;
	 tUInt8 DEF_INST_top_INST_px_DEF_WILL_FIRE_RL__Q4_2;
	 tUInt8 DEF_INST_top_INST_px_DEF_CAN_FIRE_RL__Q5_2;
	 tUInt8 DEF_INST_top_INST_px_DEF_WILL_FIRE_RL__Q5_2;
	 tUInt8 DEF_INST_top_INST_px_DEF_CAN_FIRE_RL__Q6_2;
	 tUInt8 DEF_INST_top_INST_px_DEF_WILL_FIRE_RL__Q6_2;
	 tUInt8 DEF_INST_top_INST_px_DEF_CAN_FIRE_RL__Q7_2;
	 tUInt8 DEF_INST_top_INST_px_DEF_WILL_FIRE_RL__Q7_2;
	 tUInt8 DEF_INST_top_INST_px_DEF_CAN_FIRE_RL__Q1_3;
	 tUInt8 DEF_INST_top_INST_px_DEF_WILL_FIRE_RL__Q1_3;
	 tUInt8 DEF_INST_top_INST_px_DEF_CAN_FIRE_RL__Q2_3;
	 tUInt8 DEF_INST_top_INST_px_DEF_WILL_FIRE_RL__Q2_3;
	 tUInt8 DEF_INST_top_INST_px_DEF_CAN_FIRE_RL__Q3_3;
	 tUInt8 DEF_INST_top_INST_px_DEF_WILL_FIRE_RL__Q3_3;
	 tUInt8 DEF_INST_top_INST_px_DEF_CAN_FIRE_RL__Q4_3;
	 tUInt8 DEF_INST_top_INST_px_DEF_WILL_FIRE_RL__Q4_3;
	 tUInt8 DEF_INST_top_INST_px_DEF_CAN_FIRE_RL__Q5_3;
	 tUInt8 DEF_INST_top_INST_px_DEF_WILL_FIRE_RL__Q5_3;
	 tUInt8 DEF_INST_top_INST_px_DEF_CAN_FIRE_RL__Q6_3;
	 tUInt8 DEF_INST_top_INST_px_DEF_WILL_FIRE_RL__Q6_3;
	 tUInt8 DEF_INST_top_INST_px_DEF_CAN_FIRE_RL__Q7_3;
	 tUInt8 DEF_INST_top_INST_px_DEF_WILL_FIRE_RL__Q7_3;
	 tUInt8 DEF_INST_top_INST_px_DEF_CAN_FIRE_RL__Q1_4;
	 tUInt8 DEF_INST_top_INST_px_DEF_WILL_FIRE_RL__Q1_4;
	 tUInt8 DEF_INST_top_INST_px_DEF_CAN_FIRE_RL__Q2_4;
	 tUInt8 DEF_INST_top_INST_px_DEF_WILL_FIRE_RL__Q2_4;
	 tUInt8 DEF_INST_top_INST_px_DEF_CAN_FIRE_RL__Q3_4;
	 tUInt8 DEF_INST_top_INST_px_DEF_WILL_FIRE_RL__Q3_4;
	 tUInt8 DEF_INST_top_INST_px_DEF_CAN_FIRE_RL__Q4_4;
	 tUInt8 DEF_INST_top_INST_px_DEF_WILL_FIRE_RL__Q4_4;
	 tUInt8 DEF_INST_top_INST_px_DEF_CAN_FIRE_RL__Q5_4;
	 tUInt8 DEF_INST_top_INST_px_DEF_WILL_FIRE_RL__Q5_4;
	 tUInt8 DEF_INST_top_INST_px_DEF_CAN_FIRE_RL__Q6_4;
	 tUInt8 DEF_INST_top_INST_px_DEF_WILL_FIRE_RL__Q6_4;
	 tUInt8 DEF_INST_top_INST_px_DEF_CAN_FIRE_RL__Q7_4;
	 tUInt8 DEF_INST_top_INST_px_DEF_WILL_FIRE_RL__Q7_4;
	 tUInt8 DEF_INST_top_INST_px_DEF_CAN_FIRE_RL__Q1_5;
	 tUInt8 DEF_INST_top_INST_px_DEF_WILL_FIRE_RL__Q1_5;
	 tUInt8 DEF_INST_top_INST_px_DEF_CAN_FIRE_RL__Q2_5;
	 tUInt8 DEF_INST_top_INST_px_DEF_WILL_FIRE_RL__Q2_5;
	 tUInt8 DEF_INST_top_INST_px_DEF_CAN_FIRE_RL__Q3_5;
	 tUInt8 DEF_INST_top_INST_px_DEF_WILL_FIRE_RL__Q3_5;
	 tUInt8 DEF_INST_top_INST_px_DEF_CAN_FIRE_RL__Q4_5;
	 tUInt8 DEF_INST_top_INST_px_DEF_WILL_FIRE_RL__Q4_5;
	 tUInt8 DEF_INST_top_INST_px_DEF_CAN_FIRE_RL__Q5_5;
	 tUInt8 DEF_INST_top_INST_px_DEF_WILL_FIRE_RL__Q5_5;
	 tUInt8 DEF_INST_top_INST_px_DEF_CAN_FIRE_RL__Q6_5;
	 tUInt8 DEF_INST_top_INST_px_DEF_WILL_FIRE_RL__Q6_5;
	 tUInt8 DEF_INST_top_INST_px_DEF_CAN_FIRE_RL__Q7_5;
	 tUInt8 DEF_INST_top_INST_px_DEF_WILL_FIRE_RL__Q7_5;
	 tUInt8 DEF_INST_top_INST_px_DEF_CAN_FIRE_RL__Q1_6;
	 tUInt8 DEF_INST_top_INST_px_DEF_WILL_FIRE_RL__Q1_6;
	 tUInt8 DEF_INST_top_INST_px_DEF_CAN_FIRE_RL__Q2_6;
	 tUInt8 DEF_INST_top_INST_px_DEF_WILL_FIRE_RL__Q2_6;
	 tUInt8 DEF_INST_top_INST_px_DEF_CAN_FIRE_RL__Q3_6;
	 tUInt8 DEF_INST_top_INST_px_DEF_WILL_FIRE_RL__Q3_6;
	 tUInt8 DEF_INST_top_INST_px_DEF_CAN_FIRE_RL__Q4_6;
	 tUInt8 DEF_INST_top_INST_px_DEF_WILL_FIRE_RL__Q4_6;
	 tUInt8 DEF_INST_top_INST_px_DEF_CAN_FIRE_RL__Q5_6;
	 tUInt8 DEF_INST_top_INST_px_DEF_WILL_FIRE_RL__Q5_6;
	 tUInt8 DEF_INST_top_INST_px_DEF_CAN_FIRE_RL__Q6_6;
	 tUInt8 DEF_INST_top_INST_px_DEF_WILL_FIRE_RL__Q6_6;
	 tUInt8 DEF_INST_top_INST_px_DEF_CAN_FIRE_RL__Q7_6;
	 tUInt8 DEF_INST_top_INST_px_DEF_WILL_FIRE_RL__Q7_6;
	 tUInt8 DEF_INST_top_INST_px_DEF_CAN_FIRE_RL__activate3;
	 tUInt8 DEF_INST_top_INST_px_DEF_WILL_FIRE_RL__activate3;
	 tUInt8 DEF_INST_top_INST_px_DEF_CAN_FIRE_RL__activate4;
	 tUInt8 DEF_INST_top_INST_px_DEF_WILL_FIRE_RL__activate4;
	 tUInt8 DEF_INST_top_INST_px_DEF_CAN_FIRE_RL__activate5;
	 tUInt8 DEF_INST_top_INST_px_DEF_WILL_FIRE_RL__activate5;
	 tUInt8 DEF_INST_top_INST_px_DEF_CAN_FIRE_RL__activate6;
	 tUInt8 DEF_INST_top_INST_px_DEF_WILL_FIRE_RL__activate6;
	 tUInt8 DEF_INST_top_INST_px_DEF_CAN_FIRE_RL__activate67;
	 tUInt8 DEF_INST_top_INST_px_DEF_WILL_FIRE_RL__activate67;
	 tUInt8 DEF_INST_top_INST_px_DEF_CAN_FIRE_RL_initialLoad;
	 tUInt8 DEF_INST_top_INST_px_DEF_WILL_FIRE_RL_initialLoad;
	 tUInt8 DEF_INST_top_INST_px_DEF_CAN_FIRE_RL_coalesce;
	 tUInt8 DEF_INST_top_INST_px_DEF_WILL_FIRE_RL_coalesce;
	 tUInt8 DEF_INST_top_INST_px_DEF_CAN_FIRE_RL_lateralLoad;
	 tUInt8 DEF_INST_top_INST_px_DEF_WILL_FIRE_RL_lateralLoad;
	 tUInt8 DEF_INST_top_INST_px_DEF_CAN_FIRE_RL__Q1;
	 tUInt8 DEF_INST_top_INST_px_DEF_WILL_FIRE_RL__Q1;
	 tUInt8 DEF_INST_top_INST_px_DEF_CAN_FIRE_RL__activate1;
	 tUInt8 DEF_INST_top_INST_px_DEF_WILL_FIRE_RL__activate1;
	 tUInt8 DEF_INST_top_INST_px_DEF_CAN_FIRE_RL__activate2;
	 tUInt8 DEF_INST_top_INST_px_DEF_WILL_FIRE_RL__activate2;
	 tUInt8 DEF_INST_top_DEF_px_RDY_put____d3;
	 tUInt8 DEF_INST_top_DEF_init__h1558;
	 tUInt8 DEF_INST_top_DEF_inL__h1563;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_configure;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_configure;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_intialLoad;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_intialLoad;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_lateralLoad;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_lateralLoad;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_receive3;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_receive3;
	 tUInt8 DEF_INST_top_INST_px_INST_coax_0_DEF_CAN_FIRE_RL_inCCLK;
	 tUInt8 DEF_INST_top_INST_px_INST_coax_1_DEF_CAN_FIRE_RL_inCCLK;
	 tUInt8 DEF_INST_top_INST_px_INST_coax_0_DEF_WILL_FIRE_RL_inCCLK;
	 tUInt8 DEF_INST_top_INST_px_INST_coax_1_DEF_WILL_FIRE_RL_inCCLK;
	 tUInt8 DEF_INST_top_INST_px_INST_coax_0_DEF_CAN_FIRE_RL__Q1;
	 tUInt8 DEF_INST_top_INST_px_INST_coax_1_DEF_CAN_FIRE_RL__Q1;
	 tUInt8 DEF_INST_top_INST_px_INST_coax_0_DEF_WILL_FIRE_RL__Q1;
	 tUInt8 DEF_INST_top_INST_px_INST_coax_1_DEF_WILL_FIRE_RL__Q1;
	 tUInt8 DEF_INST_top_INST_px_INST_coax_0_DEF_CAN_FIRE_RL__activate1;
	 tUInt8 DEF_INST_top_INST_px_INST_coax_1_DEF_CAN_FIRE_RL__activate1;
	 tUInt8 DEF_INST_top_INST_px_INST_coax_0_DEF_WILL_FIRE_RL__activate1;
	 tUInt8 DEF_INST_top_INST_px_INST_coax_1_DEF_WILL_FIRE_RL__activate1;
	 tUInt8 DEF_INST_top_INST_px_INST_coax_0_DEF_CAN_FIRE_RL__activate2;
	 tUInt8 DEF_INST_top_INST_px_INST_coax_1_DEF_CAN_FIRE_RL__activate2;
	 tUInt8 DEF_INST_top_INST_px_INST_coax_0_DEF_WILL_FIRE_RL__activate2;
	 tUInt8 DEF_INST_top_INST_px_INST_coax_1_DEF_WILL_FIRE_RL__activate2;
	 tUInt8 DEF_INST_top_INST_px_INST_coax_0_DEF_CAN_FIRE_RL_fill_window;
	 tUInt8 DEF_INST_top_INST_px_INST_coax_1_DEF_CAN_FIRE_RL_fill_window;
	 tUInt8 DEF_INST_top_INST_px_INST_coax_0_DEF_WILL_FIRE_RL_fill_window;
	 tUInt8 DEF_INST_top_INST_px_INST_coax_1_DEF_WILL_FIRE_RL_fill_window;
	 INST_top.INST_px.METH_RDY_configure();
	 INST_top.INST_px.INST_coax_0.METH_RDY_configure();
	 INST_top.INST_px.INST_coax_1.METH_RDY_configure();
	 DEF_INST_top_DEF_init__h1558 = INST_top.INST_init.METH_read();
	 DEF_INST_top_DEF_CAN_FIRE_RL_configure = !DEF_INST_top_DEF_init__h1558;
	 DEF_INST_top_DEF_WILL_FIRE_RL_configure = DEF_INST_top_DEF_CAN_FIRE_RL_configure;
	 DEF_INST_top_DEF_inL__h1563 = INST_top.INST_inL.METH_read();
	 DEF_INST_top_DEF_px_RDY_put____d3 = INST_top.INST_px.METH_RDY_put();
	 DEF_INST_top_DEF_CAN_FIRE_RL_intialLoad = DEF_INST_top_DEF_px_RDY_put____d3 && (DEF_INST_top_DEF_init__h1558 && DEF_INST_top_DEF_inL__h1563);
	 DEF_INST_top_DEF_WILL_FIRE_RL_intialLoad = DEF_INST_top_DEF_CAN_FIRE_RL_intialLoad;
	 DEF_INST_top_DEF_CAN_FIRE_RL_lateralLoad = DEF_INST_top_DEF_px_RDY_put____d3 && (DEF_INST_top_DEF_init__h1558 && !DEF_INST_top_DEF_inL__h1563);
	 DEF_INST_top_DEF_WILL_FIRE_RL_lateralLoad = DEF_INST_top_DEF_CAN_FIRE_RL_lateralLoad;
	 INST_top.INST_px.INST_coax_0.METH_RDY_get();
	 INST_top.INST_px.INST_coax_1.METH_RDY_get();
	 DEF_INST_top_DEF_CAN_FIRE_RL_receive3 = INST_top.INST_px.METH_RDY_get_1() && INST_top.INST_px.METH_RDY_get_0();
	 DEF_INST_top_DEF_WILL_FIRE_RL_receive3 = DEF_INST_top_DEF_CAN_FIRE_RL_receive3;
	 DEF_INST_top_INST_px_DEF_CAN_FIRE_RL__Q1 = (tUInt8)1u;
	 DEF_INST_top_INST_px_DEF_WILL_FIRE_RL__Q1 = DEF_INST_top_INST_px_DEF_CAN_FIRE_RL__Q1;
	 DEF_INST_top_INST_px_DEF_CAN_FIRE_RL__Q1_1 = (tUInt8)1u;
	 DEF_INST_top_INST_px_DEF_WILL_FIRE_RL__Q1_1 = DEF_INST_top_INST_px_DEF_CAN_FIRE_RL__Q1_1;
	 DEF_INST_top_INST_px_DEF_CAN_FIRE_RL__Q1_2 = (tUInt8)1u;
	 DEF_INST_top_INST_px_DEF_WILL_FIRE_RL__Q1_2 = DEF_INST_top_INST_px_DEF_CAN_FIRE_RL__Q1_2;
	 DEF_INST_top_INST_px_DEF_CAN_FIRE_RL__Q1_3 = (tUInt8)1u;
	 DEF_INST_top_INST_px_DEF_WILL_FIRE_RL__Q1_3 = DEF_INST_top_INST_px_DEF_CAN_FIRE_RL__Q1_3;
	 DEF_INST_top_INST_px_DEF_CAN_FIRE_RL__Q1_4 = (tUInt8)1u;
	 DEF_INST_top_INST_px_DEF_WILL_FIRE_RL__Q1_4 = DEF_INST_top_INST_px_DEF_CAN_FIRE_RL__Q1_4;
	 DEF_INST_top_INST_px_DEF_CAN_FIRE_RL__Q1_5 = (tUInt8)1u;
	 DEF_INST_top_INST_px_DEF_WILL_FIRE_RL__Q1_5 = DEF_INST_top_INST_px_DEF_CAN_FIRE_RL__Q1_5;
	 DEF_INST_top_INST_px_DEF_CAN_FIRE_RL__Q1_6 = (tUInt8)1u;
	 DEF_INST_top_INST_px_DEF_WILL_FIRE_RL__Q1_6 = DEF_INST_top_INST_px_DEF_CAN_FIRE_RL__Q1_6;
	 DEF_INST_top_INST_px_DEF_CAN_FIRE_RL__Q2_1 = (tUInt8)1u;
	 DEF_INST_top_INST_px_DEF_WILL_FIRE_RL__Q2_1 = DEF_INST_top_INST_px_DEF_CAN_FIRE_RL__Q2_1;
	 DEF_INST_top_INST_px_DEF_CAN_FIRE_RL__Q2 = (tUInt8)1u;
	 DEF_INST_top_INST_px_DEF_WILL_FIRE_RL__Q2 = DEF_INST_top_INST_px_DEF_CAN_FIRE_RL__Q2;
	 DEF_INST_top_INST_px_DEF_CAN_FIRE_RL__Q2_2 = (tUInt8)1u;
	 DEF_INST_top_INST_px_DEF_WILL_FIRE_RL__Q2_2 = DEF_INST_top_INST_px_DEF_CAN_FIRE_RL__Q2_2;
	 DEF_INST_top_INST_px_DEF_CAN_FIRE_RL__Q2_3 = (tUInt8)1u;
	 DEF_INST_top_INST_px_DEF_WILL_FIRE_RL__Q2_3 = DEF_INST_top_INST_px_DEF_CAN_FIRE_RL__Q2_3;
	 DEF_INST_top_INST_px_DEF_CAN_FIRE_RL__Q2_4 = (tUInt8)1u;
	 DEF_INST_top_INST_px_DEF_WILL_FIRE_RL__Q2_4 = DEF_INST_top_INST_px_DEF_CAN_FIRE_RL__Q2_4;
	 DEF_INST_top_INST_px_DEF_CAN_FIRE_RL__Q2_5 = (tUInt8)1u;
	 DEF_INST_top_INST_px_DEF_WILL_FIRE_RL__Q2_5 = DEF_INST_top_INST_px_DEF_CAN_FIRE_RL__Q2_5;
	 DEF_INST_top_INST_px_DEF_CAN_FIRE_RL__Q2_6 = (tUInt8)1u;
	 DEF_INST_top_INST_px_DEF_WILL_FIRE_RL__Q2_6 = DEF_INST_top_INST_px_DEF_CAN_FIRE_RL__Q2_6;
	 DEF_INST_top_INST_px_DEF_CAN_FIRE_RL__Q3 = (tUInt8)1u;
	 DEF_INST_top_INST_px_DEF_WILL_FIRE_RL__Q3 = DEF_INST_top_INST_px_DEF_CAN_FIRE_RL__Q3;
	 DEF_INST_top_INST_px_DEF_CAN_FIRE_RL__Q3_1 = (tUInt8)1u;
	 DEF_INST_top_INST_px_DEF_WILL_FIRE_RL__Q3_1 = DEF_INST_top_INST_px_DEF_CAN_FIRE_RL__Q3_1;
	 DEF_INST_top_INST_px_DEF_CAN_FIRE_RL__Q3_2 = (tUInt8)1u;
	 DEF_INST_top_INST_px_DEF_WILL_FIRE_RL__Q3_2 = DEF_INST_top_INST_px_DEF_CAN_FIRE_RL__Q3_2;
	 DEF_INST_top_INST_px_DEF_CAN_FIRE_RL__Q3_3 = (tUInt8)1u;
	 DEF_INST_top_INST_px_DEF_WILL_FIRE_RL__Q3_3 = DEF_INST_top_INST_px_DEF_CAN_FIRE_RL__Q3_3;
	 DEF_INST_top_INST_px_DEF_CAN_FIRE_RL__Q3_4 = (tUInt8)1u;
	 DEF_INST_top_INST_px_DEF_WILL_FIRE_RL__Q3_4 = DEF_INST_top_INST_px_DEF_CAN_FIRE_RL__Q3_4;
	 DEF_INST_top_INST_px_DEF_CAN_FIRE_RL__Q3_5 = (tUInt8)1u;
	 DEF_INST_top_INST_px_DEF_WILL_FIRE_RL__Q3_5 = DEF_INST_top_INST_px_DEF_CAN_FIRE_RL__Q3_5;
	 DEF_INST_top_INST_px_DEF_CAN_FIRE_RL__Q3_6 = (tUInt8)1u;
	 DEF_INST_top_INST_px_DEF_WILL_FIRE_RL__Q3_6 = DEF_INST_top_INST_px_DEF_CAN_FIRE_RL__Q3_6;
	 DEF_INST_top_INST_px_DEF_CAN_FIRE_RL__Q4 = (tUInt8)1u;
	 DEF_INST_top_INST_px_DEF_WILL_FIRE_RL__Q4 = DEF_INST_top_INST_px_DEF_CAN_FIRE_RL__Q4;
	 DEF_INST_top_INST_px_DEF_CAN_FIRE_RL__Q4_1 = (tUInt8)1u;
	 DEF_INST_top_INST_px_DEF_WILL_FIRE_RL__Q4_1 = DEF_INST_top_INST_px_DEF_CAN_FIRE_RL__Q4_1;
	 DEF_INST_top_INST_px_DEF_CAN_FIRE_RL__Q4_2 = (tUInt8)1u;
	 DEF_INST_top_INST_px_DEF_WILL_FIRE_RL__Q4_2 = DEF_INST_top_INST_px_DEF_CAN_FIRE_RL__Q4_2;
	 DEF_INST_top_INST_px_DEF_CAN_FIRE_RL__Q4_3 = (tUInt8)1u;
	 DEF_INST_top_INST_px_DEF_WILL_FIRE_RL__Q4_3 = DEF_INST_top_INST_px_DEF_CAN_FIRE_RL__Q4_3;
	 DEF_INST_top_INST_px_DEF_CAN_FIRE_RL__Q4_4 = (tUInt8)1u;
	 DEF_INST_top_INST_px_DEF_WILL_FIRE_RL__Q4_4 = DEF_INST_top_INST_px_DEF_CAN_FIRE_RL__Q4_4;
	 DEF_INST_top_INST_px_DEF_CAN_FIRE_RL__Q4_5 = (tUInt8)1u;
	 DEF_INST_top_INST_px_DEF_WILL_FIRE_RL__Q4_5 = DEF_INST_top_INST_px_DEF_CAN_FIRE_RL__Q4_5;
	 DEF_INST_top_INST_px_DEF_CAN_FIRE_RL__Q5 = (tUInt8)1u;
	 DEF_INST_top_INST_px_DEF_WILL_FIRE_RL__Q5 = DEF_INST_top_INST_px_DEF_CAN_FIRE_RL__Q5;
	 DEF_INST_top_INST_px_DEF_CAN_FIRE_RL__Q4_6 = (tUInt8)1u;
	 DEF_INST_top_INST_px_DEF_WILL_FIRE_RL__Q4_6 = DEF_INST_top_INST_px_DEF_CAN_FIRE_RL__Q4_6;
	 DEF_INST_top_INST_px_DEF_CAN_FIRE_RL__Q5_1 = (tUInt8)1u;
	 DEF_INST_top_INST_px_DEF_WILL_FIRE_RL__Q5_1 = DEF_INST_top_INST_px_DEF_CAN_FIRE_RL__Q5_1;
	 DEF_INST_top_INST_px_DEF_CAN_FIRE_RL__Q5_2 = (tUInt8)1u;
	 DEF_INST_top_INST_px_DEF_WILL_FIRE_RL__Q5_2 = DEF_INST_top_INST_px_DEF_CAN_FIRE_RL__Q5_2;
	 DEF_INST_top_INST_px_DEF_CAN_FIRE_RL__Q5_3 = (tUInt8)1u;
	 DEF_INST_top_INST_px_DEF_WILL_FIRE_RL__Q5_3 = DEF_INST_top_INST_px_DEF_CAN_FIRE_RL__Q5_3;
	 DEF_INST_top_INST_px_DEF_CAN_FIRE_RL__Q5_4 = (tUInt8)1u;
	 DEF_INST_top_INST_px_DEF_WILL_FIRE_RL__Q5_4 = DEF_INST_top_INST_px_DEF_CAN_FIRE_RL__Q5_4;
	 DEF_INST_top_INST_px_DEF_CAN_FIRE_RL__Q5_5 = (tUInt8)1u;
	 DEF_INST_top_INST_px_DEF_WILL_FIRE_RL__Q5_5 = DEF_INST_top_INST_px_DEF_CAN_FIRE_RL__Q5_5;
	 DEF_INST_top_INST_px_DEF_CAN_FIRE_RL__Q5_6 = (tUInt8)1u;
	 DEF_INST_top_INST_px_DEF_WILL_FIRE_RL__Q5_6 = DEF_INST_top_INST_px_DEF_CAN_FIRE_RL__Q5_6;
	 DEF_INST_top_INST_px_DEF_CAN_FIRE_RL__Q6 = (tUInt8)1u;
	 DEF_INST_top_INST_px_DEF_WILL_FIRE_RL__Q6 = DEF_INST_top_INST_px_DEF_CAN_FIRE_RL__Q6;
	 DEF_INST_top_INST_px_DEF_CAN_FIRE_RL__Q6_2 = (tUInt8)1u;
	 DEF_INST_top_INST_px_DEF_WILL_FIRE_RL__Q6_2 = DEF_INST_top_INST_px_DEF_CAN_FIRE_RL__Q6_2;
	 DEF_INST_top_INST_px_DEF_CAN_FIRE_RL__Q6_1 = (tUInt8)1u;
	 DEF_INST_top_INST_px_DEF_WILL_FIRE_RL__Q6_1 = DEF_INST_top_INST_px_DEF_CAN_FIRE_RL__Q6_1;
	 DEF_INST_top_INST_px_DEF_CAN_FIRE_RL__Q6_3 = (tUInt8)1u;
	 DEF_INST_top_INST_px_DEF_WILL_FIRE_RL__Q6_3 = DEF_INST_top_INST_px_DEF_CAN_FIRE_RL__Q6_3;
	 DEF_INST_top_INST_px_DEF_CAN_FIRE_RL__Q6_4 = (tUInt8)1u;
	 DEF_INST_top_INST_px_DEF_WILL_FIRE_RL__Q6_4 = DEF_INST_top_INST_px_DEF_CAN_FIRE_RL__Q6_4;
	 DEF_INST_top_INST_px_DEF_CAN_FIRE_RL__Q6_5 = (tUInt8)1u;
	 DEF_INST_top_INST_px_DEF_WILL_FIRE_RL__Q6_5 = DEF_INST_top_INST_px_DEF_CAN_FIRE_RL__Q6_5;
	 DEF_INST_top_INST_px_DEF_CAN_FIRE_RL__Q6_6 = (tUInt8)1u;
	 DEF_INST_top_INST_px_DEF_WILL_FIRE_RL__Q6_6 = DEF_INST_top_INST_px_DEF_CAN_FIRE_RL__Q6_6;
	 DEF_INST_top_INST_px_DEF_CAN_FIRE_RL__Q7 = (tUInt8)1u;
	 DEF_INST_top_INST_px_DEF_WILL_FIRE_RL__Q7 = DEF_INST_top_INST_px_DEF_CAN_FIRE_RL__Q7;
	 DEF_INST_top_INST_px_DEF_CAN_FIRE_RL__Q7_1 = (tUInt8)1u;
	 DEF_INST_top_INST_px_DEF_WILL_FIRE_RL__Q7_1 = DEF_INST_top_INST_px_DEF_CAN_FIRE_RL__Q7_1;
	 DEF_INST_top_INST_px_DEF_CAN_FIRE_RL__Q7_2 = (tUInt8)1u;
	 DEF_INST_top_INST_px_DEF_WILL_FIRE_RL__Q7_2 = DEF_INST_top_INST_px_DEF_CAN_FIRE_RL__Q7_2;
	 DEF_INST_top_INST_px_DEF_CAN_FIRE_RL__Q7_3 = (tUInt8)1u;
	 DEF_INST_top_INST_px_DEF_WILL_FIRE_RL__Q7_3 = DEF_INST_top_INST_px_DEF_CAN_FIRE_RL__Q7_3;
	 DEF_INST_top_INST_px_DEF_CAN_FIRE_RL__Q7_5 = (tUInt8)1u;
	 DEF_INST_top_INST_px_DEF_WILL_FIRE_RL__Q7_5 = DEF_INST_top_INST_px_DEF_CAN_FIRE_RL__Q7_5;
	 DEF_INST_top_INST_px_DEF_CAN_FIRE_RL__Q7_4 = (tUInt8)1u;
	 DEF_INST_top_INST_px_DEF_WILL_FIRE_RL__Q7_4 = DEF_INST_top_INST_px_DEF_CAN_FIRE_RL__Q7_4;
	 DEF_INST_top_INST_px_DEF_CAN_FIRE_RL__Q7_6 = (tUInt8)1u;
	 DEF_INST_top_INST_px_DEF_WILL_FIRE_RL__Q7_6 = DEF_INST_top_INST_px_DEF_CAN_FIRE_RL__Q7_6;
	 DEF_INST_top_INST_px_DEF_CAN_FIRE_RL_coalesce = INST_top.INST_px.INST_coax_0.METH_RDY_put() && (INST_top.INST_px.INST_coax_1.METH_RDY_put() && (tUInt8)(INST_top.INST_px.INST_p7_rv.METH_port0__read() >> 1u));
	 DEF_INST_top_INST_px_DEF_WILL_FIRE_RL_coalesce = DEF_INST_top_INST_px_DEF_CAN_FIRE_RL_coalesce;
	 DEF_INST_top_INST_px_DEF_CAN_FIRE_RL_inCLK = (tUInt8)1u;
	 DEF_INST_top_INST_px_DEF_WILL_FIRE_RL_inCLK = DEF_INST_top_INST_px_DEF_CAN_FIRE_RL_inCLK;
	 INST_top.INST_px.DEF_x__h6041 = INST_top.INST_px.INST_mem_rRdPtr.METH_read();
	 INST_top.INST_px.DEF_x__h5967 = INST_top.INST_px.INST_mem_rWrPtr.METH_read();
	 DEF_INST_top_INST_px_DEF_b__h14773 = INST_top.INST_px.INST_width.METH_read();
	 INST_top.INST_px.DEF_b__h14772 = INST_top.INST_px.INST_cx2.METH_read();
	 DEF_INST_top_INST_px_DEF_inQ_i_notEmpty____d325 = INST_top.INST_px.INST_inQ.METH_i_notEmpty();
	 DEF_INST_top_INST_px_DEF_cx2_78_ULT_width_79___d280 = (INST_top.INST_px.DEF_b__h14772) < DEF_INST_top_INST_px_DEF_b__h14773;
	 DEF_INST_top_INST_px_DEF_NOT_mem_rRdPtr_read__9_PLUS_100000_68_EQ_mem_r_ETC___d270 = !((262143u & ((INST_top.INST_px.DEF_x__h6041) + 100000u)) == (INST_top.INST_px.DEF_x__h5967));
	 DEF_INST_top_INST_px_DEF_CAN_FIRE_RL_initialLoad = (DEF_INST_top_INST_px_DEF_NOT_mem_rRdPtr_read__9_PLUS_100000_68_EQ_mem_r_ETC___d270 && DEF_INST_top_INST_px_DEF_inQ_i_notEmpty____d325) && DEF_INST_top_INST_px_DEF_cx2_78_ULT_width_79___d280;
	 DEF_INST_top_INST_px_DEF_WILL_FIRE_RL_initialLoad = DEF_INST_top_INST_px_DEF_CAN_FIRE_RL_initialLoad;
	 DEF_INST_top_INST_px_INST_coax_0_DEF_CAN_FIRE_RL_inCCLK = (tUInt8)1u;
	 DEF_INST_top_INST_px_INST_coax_0_DEF_WILL_FIRE_RL_inCCLK = DEF_INST_top_INST_px_INST_coax_0_DEF_CAN_FIRE_RL_inCCLK;
	 DEF_INST_top_INST_px_DEF_CAN_FIRE_RL_mem_portA = (tUInt8)1u;
	 DEF_INST_top_INST_px_DEF_WILL_FIRE_RL_mem_portA = DEF_INST_top_INST_px_DEF_CAN_FIRE_RL_mem_portA;
	 DEF_INST_top_INST_px_DEF_CAN_FIRE_RL_mem_portB = (tUInt8)1u;
	 DEF_INST_top_INST_px_DEF_WILL_FIRE_RL_mem_portB = DEF_INST_top_INST_px_DEF_CAN_FIRE_RL_mem_portB;
	 DEF_INST_top_INST_px_DEF_CAN_FIRE_RL_mem_portB_read_data = (tUInt8)1u;
	 DEF_INST_top_INST_px_DEF_WILL_FIRE_RL_mem_portB_read_data = DEF_INST_top_INST_px_DEF_CAN_FIRE_RL_mem_portB_read_data;
	 DEF_INST_top_INST_px_INST_coax_0_DEF_CAN_FIRE_RL__Q1 = (tUInt8)1u;
	 DEF_INST_top_INST_px_INST_coax_0_DEF_WILL_FIRE_RL__Q1 = DEF_INST_top_INST_px_INST_coax_0_DEF_CAN_FIRE_RL__Q1;
	 DEF_INST_top_INST_px_INST_coax_1_DEF_CAN_FIRE_RL__Q1 = (tUInt8)1u;
	 DEF_INST_top_INST_px_INST_coax_1_DEF_WILL_FIRE_RL__Q1 = DEF_INST_top_INST_px_INST_coax_1_DEF_CAN_FIRE_RL__Q1;
	 DEF_INST_top_INST_px_INST_coax_1_DEF_CAN_FIRE_RL_inCCLK = (tUInt8)1u;
	 DEF_INST_top_INST_px_INST_coax_1_DEF_WILL_FIRE_RL_inCCLK = DEF_INST_top_INST_px_INST_coax_1_DEF_CAN_FIRE_RL_inCCLK;
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_intialLoad)
	   INST_top.RL_intialLoad();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_lateralLoad)
	   INST_top.RL_lateralLoad();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_receive3)
	   INST_top.RL_receive3();
	 DEF_INST_top_INST_px_INST_coax_0_DEF_CAN_FIRE_RL_fill_window = (tUInt8)(INST_top.INST_px.INST_coax_0.INST_p1_rv.METH_port0__read() >> 1u) && !((tUInt8)(INST_top.INST_px.INST_coax_0.INST_p2_rv.METH_port1__read() >> 1u));
	 DEF_INST_top_INST_px_INST_coax_0_DEF_WILL_FIRE_RL_fill_window = DEF_INST_top_INST_px_INST_coax_0_DEF_CAN_FIRE_RL_fill_window;
	 DEF_INST_top_INST_px_INST_coax_1_DEF_CAN_FIRE_RL_fill_window = (tUInt8)(INST_top.INST_px.INST_coax_1.INST_p1_rv.METH_port0__read() >> 1u) && !((tUInt8)(INST_top.INST_px.INST_coax_1.INST_p2_rv.METH_port1__read() >> 1u));
	 DEF_INST_top_INST_px_INST_coax_1_DEF_WILL_FIRE_RL_fill_window = DEF_INST_top_INST_px_INST_coax_1_DEF_CAN_FIRE_RL_fill_window;
	 if (DEF_INST_top_INST_px_DEF_WILL_FIRE_RL__Q7_2)
	   INST_top.INST_px.RL__Q7_2();
	 if (DEF_INST_top_INST_px_DEF_WILL_FIRE_RL__Q7_3)
	   INST_top.INST_px.RL__Q7_3();
	 if (DEF_INST_top_INST_px_DEF_WILL_FIRE_RL__Q6_3)
	   INST_top.INST_px.RL__Q6_3();
	 if (DEF_INST_top_INST_px_DEF_WILL_FIRE_RL__Q7_4)
	   INST_top.INST_px.RL__Q7_4();
	 if (DEF_INST_top_INST_px_DEF_WILL_FIRE_RL__Q6_4)
	   INST_top.INST_px.RL__Q6_4();
	 if (DEF_INST_top_INST_px_DEF_WILL_FIRE_RL__Q5_4)
	   INST_top.INST_px.RL__Q5_4();
	 if (DEF_INST_top_INST_px_DEF_WILL_FIRE_RL__Q7_5)
	   INST_top.INST_px.RL__Q7_5();
	 if (DEF_INST_top_INST_px_DEF_WILL_FIRE_RL__Q6_5)
	   INST_top.INST_px.RL__Q6_5();
	 if (DEF_INST_top_INST_px_DEF_WILL_FIRE_RL__Q5_5)
	   INST_top.INST_px.RL__Q5_5();
	 if (DEF_INST_top_INST_px_DEF_WILL_FIRE_RL__Q4_5)
	   INST_top.INST_px.RL__Q4_5();
	 if (DEF_INST_top_INST_px_DEF_WILL_FIRE_RL__Q7_6)
	   INST_top.INST_px.RL__Q7_6();
	 if (DEF_INST_top_INST_px_DEF_WILL_FIRE_RL__Q6_6)
	   INST_top.INST_px.RL__Q6_6();
	 if (DEF_INST_top_INST_px_DEF_WILL_FIRE_RL__Q5_6)
	   INST_top.INST_px.RL__Q5_6();
	 if (DEF_INST_top_INST_px_DEF_WILL_FIRE_RL__Q4_6)
	   INST_top.INST_px.RL__Q4_6();
	 if (DEF_INST_top_INST_px_DEF_WILL_FIRE_RL__Q3_6)
	   INST_top.INST_px.RL__Q3_6();
	 if (DEF_INST_top_INST_px_DEF_WILL_FIRE_RL_coalesce)
	   INST_top.INST_px.RL_coalesce();
	 DEF_INST_top_INST_px_DEF_CAN_FIRE_RL__activate67 = (tUInt8)(INST_top.INST_px.INST_p6_rv.METH_port0__read() >> 1u) && !((tUInt8)(INST_top.INST_px.INST_p7_rv.METH_port1__read() >> 1u));
	 DEF_INST_top_INST_px_DEF_WILL_FIRE_RL__activate67 = DEF_INST_top_INST_px_DEF_CAN_FIRE_RL__activate67;
	 if (DEF_INST_top_INST_px_DEF_WILL_FIRE_RL__Q7)
	   INST_top.INST_px.RL__Q7();
	 if (DEF_INST_top_INST_px_DEF_WILL_FIRE_RL__Q6)
	   INST_top.INST_px.RL__Q6();
	 if (DEF_INST_top_INST_px_DEF_WILL_FIRE_RL__Q5)
	   INST_top.INST_px.RL__Q5();
	 if (DEF_INST_top_INST_px_DEF_WILL_FIRE_RL__Q4)
	   INST_top.INST_px.RL__Q4();
	 if (DEF_INST_top_INST_px_DEF_WILL_FIRE_RL__Q3)
	   INST_top.INST_px.RL__Q3();
	 if (DEF_INST_top_INST_px_DEF_WILL_FIRE_RL__Q2)
	   INST_top.INST_px.RL__Q2();
	 if (DEF_INST_top_INST_px_DEF_WILL_FIRE_RL__Q1)
	   INST_top.INST_px.RL__Q1();
	 if (DEF_INST_top_INST_px_DEF_WILL_FIRE_RL__Q7_1)
	   INST_top.INST_px.RL__Q7_1();
	 if (DEF_INST_top_INST_px_DEF_WILL_FIRE_RL__Q6_1)
	   INST_top.INST_px.RL__Q6_1();
	 if (DEF_INST_top_INST_px_DEF_WILL_FIRE_RL__Q5_1)
	   INST_top.INST_px.RL__Q5_1();
	 if (DEF_INST_top_INST_px_DEF_WILL_FIRE_RL__Q4_1)
	   INST_top.INST_px.RL__Q4_1();
	 if (DEF_INST_top_INST_px_DEF_WILL_FIRE_RL__Q3_1)
	   INST_top.INST_px.RL__Q3_1();
	 if (DEF_INST_top_INST_px_DEF_WILL_FIRE_RL__Q2_1)
	   INST_top.INST_px.RL__Q2_1();
	 if (DEF_INST_top_INST_px_DEF_WILL_FIRE_RL__Q1_1)
	   INST_top.INST_px.RL__Q1_1();
	 if (DEF_INST_top_INST_px_DEF_WILL_FIRE_RL__Q6_2)
	   INST_top.INST_px.RL__Q6_2();
	 if (DEF_INST_top_INST_px_DEF_WILL_FIRE_RL__Q5_2)
	   INST_top.INST_px.RL__Q5_2();
	 if (DEF_INST_top_INST_px_DEF_WILL_FIRE_RL__Q4_2)
	   INST_top.INST_px.RL__Q4_2();
	 if (DEF_INST_top_INST_px_DEF_WILL_FIRE_RL__Q3_2)
	   INST_top.INST_px.RL__Q3_2();
	 if (DEF_INST_top_INST_px_DEF_WILL_FIRE_RL__Q2_2)
	   INST_top.INST_px.RL__Q2_2();
	 if (DEF_INST_top_INST_px_DEF_WILL_FIRE_RL__Q1_2)
	   INST_top.INST_px.RL__Q1_2();
	 if (DEF_INST_top_INST_px_DEF_WILL_FIRE_RL__Q5_3)
	   INST_top.INST_px.RL__Q5_3();
	 if (DEF_INST_top_INST_px_DEF_WILL_FIRE_RL__Q4_3)
	   INST_top.INST_px.RL__Q4_3();
	 if (DEF_INST_top_INST_px_DEF_WILL_FIRE_RL__Q3_3)
	   INST_top.INST_px.RL__Q3_3();
	 if (DEF_INST_top_INST_px_DEF_WILL_FIRE_RL__Q2_3)
	   INST_top.INST_px.RL__Q2_3();
	 if (DEF_INST_top_INST_px_DEF_WILL_FIRE_RL__Q1_3)
	   INST_top.INST_px.RL__Q1_3();
	 if (DEF_INST_top_INST_px_DEF_WILL_FIRE_RL__Q4_4)
	   INST_top.INST_px.RL__Q4_4();
	 if (DEF_INST_top_INST_px_DEF_WILL_FIRE_RL__Q3_4)
	   INST_top.INST_px.RL__Q3_4();
	 if (DEF_INST_top_INST_px_DEF_WILL_FIRE_RL__Q2_4)
	   INST_top.INST_px.RL__Q2_4();
	 if (DEF_INST_top_INST_px_DEF_WILL_FIRE_RL__Q1_4)
	   INST_top.INST_px.RL__Q1_4();
	 if (DEF_INST_top_INST_px_DEF_WILL_FIRE_RL__Q3_5)
	   INST_top.INST_px.RL__Q3_5();
	 if (DEF_INST_top_INST_px_DEF_WILL_FIRE_RL__Q2_5)
	   INST_top.INST_px.RL__Q2_5();
	 if (DEF_INST_top_INST_px_DEF_WILL_FIRE_RL__Q1_5)
	   INST_top.INST_px.RL__Q1_5();
	 if (DEF_INST_top_INST_px_DEF_WILL_FIRE_RL__Q2_6)
	   INST_top.INST_px.RL__Q2_6();
	 if (DEF_INST_top_INST_px_DEF_WILL_FIRE_RL__Q1_6)
	   INST_top.INST_px.RL__Q1_6();
	 if (DEF_INST_top_INST_px_DEF_WILL_FIRE_RL__activate67)
	   INST_top.INST_px.RL__activate67();
	 DEF_INST_top_INST_px_DEF_CAN_FIRE_RL__activate6 = (tUInt8)(INST_top.INST_px.INST_p5_rv.METH_port0__read() >> 1u) && !((tUInt8)(INST_top.INST_px.INST_p6_rv.METH_port1__read() >> 1u));
	 DEF_INST_top_INST_px_DEF_WILL_FIRE_RL__activate6 = DEF_INST_top_INST_px_DEF_CAN_FIRE_RL__activate6;
	 if (DEF_INST_top_INST_px_DEF_WILL_FIRE_RL__activate6)
	   INST_top.INST_px.RL__activate6();
	 DEF_INST_top_INST_px_DEF_CAN_FIRE_RL__activate5 = (tUInt8)(INST_top.INST_px.INST_p4_rv.METH_port0__read() >> 1u) && !((tUInt8)(INST_top.INST_px.INST_p5_rv.METH_port1__read() >> 1u));
	 DEF_INST_top_INST_px_DEF_WILL_FIRE_RL__activate5 = DEF_INST_top_INST_px_DEF_CAN_FIRE_RL__activate5;
	 if (DEF_INST_top_INST_px_DEF_WILL_FIRE_RL__activate5)
	   INST_top.INST_px.RL__activate5();
	 DEF_INST_top_INST_px_DEF_CAN_FIRE_RL__activate4 = (tUInt8)(INST_top.INST_px.INST_p3_rv.METH_port0__read() >> 1u) && !((tUInt8)(INST_top.INST_px.INST_p4_rv.METH_port1__read() >> 1u));
	 DEF_INST_top_INST_px_DEF_WILL_FIRE_RL__activate4 = DEF_INST_top_INST_px_DEF_CAN_FIRE_RL__activate4;
	 if (DEF_INST_top_INST_px_DEF_WILL_FIRE_RL__activate4)
	   INST_top.INST_px.RL__activate4();
	 DEF_INST_top_INST_px_DEF_CAN_FIRE_RL__activate3 = (tUInt8)(INST_top.INST_px.INST_p2_rv.METH_port0__read() >> 1u) && !((tUInt8)(INST_top.INST_px.INST_p3_rv.METH_port1__read() >> 1u));
	 DEF_INST_top_INST_px_DEF_WILL_FIRE_RL__activate3 = DEF_INST_top_INST_px_DEF_CAN_FIRE_RL__activate3;
	 if (DEF_INST_top_INST_px_DEF_WILL_FIRE_RL__activate3)
	   INST_top.INST_px.RL__activate3();
	 DEF_INST_top_INST_px_DEF_CAN_FIRE_RL__activate2 = (tUInt8)(INST_top.INST_px.INST_p1_rv.METH_port0__read() >> 1u) && !((tUInt8)(INST_top.INST_px.INST_p2_rv.METH_port1__read() >> 1u));
	 DEF_INST_top_INST_px_DEF_WILL_FIRE_RL__activate2 = DEF_INST_top_INST_px_DEF_CAN_FIRE_RL__activate2;
	 if (DEF_INST_top_INST_px_DEF_WILL_FIRE_RL__activate2)
	   INST_top.INST_px.RL__activate2();
	 DEF_INST_top_INST_px_DEF_NOT_cx2_78_ULT_width_79_80___d281 = !DEF_INST_top_INST_px_DEF_cx2_78_ULT_width_79___d280;
	 DEF_INST_top_INST_px_DEF_CAN_FIRE_RL__activate1 = (DEF_INST_top_INST_px_DEF_NOT_mem_rRdPtr_read__9_PLUS_100000_68_EQ_mem_r_ETC___d270 && ((tUInt8)(INST_top.INST_px.INST_p0_rv.METH_port0__read() >> 1u) && !((tUInt8)(INST_top.INST_px.INST_p1_rv.METH_port1__read() >> 1u)))) && DEF_INST_top_INST_px_DEF_NOT_cx2_78_ULT_width_79_80___d281;
	 DEF_INST_top_INST_px_DEF_WILL_FIRE_RL__activate1 = DEF_INST_top_INST_px_DEF_CAN_FIRE_RL__activate1;
	 if (DEF_INST_top_INST_px_DEF_WILL_FIRE_RL__activate1)
	   INST_top.INST_px.RL__activate1();
	 if (DEF_INST_top_INST_px_DEF_WILL_FIRE_RL_inCLK)
	   INST_top.INST_px.RL_inCLK();
	 if (DEF_INST_top_INST_px_DEF_WILL_FIRE_RL_initialLoad)
	   INST_top.INST_px.RL_initialLoad();
	 if (DEF_INST_top_INST_px_DEF_WILL_FIRE_RL_mem_portB_read_data)
	   INST_top.INST_px.RL_mem_portB_read_data();
	 DEF_INST_top_INST_px_DEF_CAN_FIRE_RL_lateralLoad = ((!((INST_top.INST_px.DEF_x__h6041) == (INST_top.INST_px.DEF_x__h5967)) && (DEF_INST_top_INST_px_DEF_inQ_i_notEmpty____d325 && (INST_top.INST_px.INST_mem_wDataOut.METH_whas() && !((tUInt8)(INST_top.INST_px.INST_p0_rv.METH_port1__read() >> 1u))))) && DEF_INST_top_INST_px_DEF_NOT_cx2_78_ULT_width_79_80___d281) && !DEF_INST_top_INST_px_DEF_CAN_FIRE_RL_initialLoad;
	 DEF_INST_top_INST_px_DEF_WILL_FIRE_RL_lateralLoad = DEF_INST_top_INST_px_DEF_CAN_FIRE_RL_lateralLoad;
	 if (DEF_INST_top_INST_px_DEF_WILL_FIRE_RL_lateralLoad)
	   INST_top.INST_px.RL_lateralLoad();
	 if (DEF_INST_top_INST_px_DEF_WILL_FIRE_RL_mem_portA)
	   INST_top.INST_px.RL_mem_portA();
	 if (DEF_INST_top_INST_px_DEF_WILL_FIRE_RL_mem_portB)
	   INST_top.INST_px.RL_mem_portB();
	 if (DEF_INST_top_INST_px_INST_coax_0_DEF_WILL_FIRE_RL_fill_window)
	   INST_top.INST_px.INST_coax_0.RL_fill_window();
	 DEF_INST_top_INST_px_INST_coax_0_DEF_CAN_FIRE_RL__activate2 = (tUInt8)(INST_top.INST_px.INST_coax_0.INST_p0_rv.METH_port0__read() >> 1u) && !((tUInt8)(INST_top.INST_px.INST_coax_0.INST_p1_rv.METH_port1__read() >> 1u));
	 DEF_INST_top_INST_px_INST_coax_0_DEF_WILL_FIRE_RL__activate2 = DEF_INST_top_INST_px_INST_coax_0_DEF_CAN_FIRE_RL__activate2;
	 if (DEF_INST_top_INST_px_INST_coax_0_DEF_WILL_FIRE_RL__Q1)
	   INST_top.INST_px.INST_coax_0.RL__Q1();
	 if (DEF_INST_top_INST_px_INST_coax_0_DEF_WILL_FIRE_RL__activate2)
	   INST_top.INST_px.INST_coax_0.RL__activate2();
	 DEF_INST_top_INST_px_INST_coax_0_DEF_CAN_FIRE_RL__activate1 = INST_top.INST_px.INST_coax_0.INST_inQ.METH_i_notEmpty() && !((tUInt8)(INST_top.INST_px.INST_coax_0.INST_p0_rv.METH_port1__read() >> 1u));
	 DEF_INST_top_INST_px_INST_coax_0_DEF_WILL_FIRE_RL__activate1 = DEF_INST_top_INST_px_INST_coax_0_DEF_CAN_FIRE_RL__activate1;
	 if (DEF_INST_top_INST_px_INST_coax_0_DEF_WILL_FIRE_RL__activate1)
	   INST_top.INST_px.INST_coax_0.RL__activate1();
	 if (DEF_INST_top_INST_px_INST_coax_1_DEF_WILL_FIRE_RL_fill_window)
	   INST_top.INST_px.INST_coax_1.RL_fill_window();
	 DEF_INST_top_INST_px_INST_coax_1_DEF_CAN_FIRE_RL__activate2 = (tUInt8)(INST_top.INST_px.INST_coax_1.INST_p0_rv.METH_port0__read() >> 1u) && !((tUInt8)(INST_top.INST_px.INST_coax_1.INST_p1_rv.METH_port1__read() >> 1u));
	 DEF_INST_top_INST_px_INST_coax_1_DEF_WILL_FIRE_RL__activate2 = DEF_INST_top_INST_px_INST_coax_1_DEF_CAN_FIRE_RL__activate2;
	 if (DEF_INST_top_INST_px_INST_coax_0_DEF_WILL_FIRE_RL_inCCLK)
	   INST_top.INST_px.INST_coax_0.RL_inCCLK();
	 if (DEF_INST_top_INST_px_INST_coax_1_DEF_WILL_FIRE_RL__Q1)
	   INST_top.INST_px.INST_coax_1.RL__Q1();
	 if (DEF_INST_top_INST_px_INST_coax_1_DEF_WILL_FIRE_RL__activate2)
	   INST_top.INST_px.INST_coax_1.RL__activate2();
	 DEF_INST_top_INST_px_INST_coax_1_DEF_CAN_FIRE_RL__activate1 = INST_top.INST_px.INST_coax_1.INST_inQ.METH_i_notEmpty() && !((tUInt8)(INST_top.INST_px.INST_coax_1.INST_p0_rv.METH_port1__read() >> 1u));
	 DEF_INST_top_INST_px_INST_coax_1_DEF_WILL_FIRE_RL__activate1 = DEF_INST_top_INST_px_INST_coax_1_DEF_CAN_FIRE_RL__activate1;
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_configure)
	   INST_top.RL_configure();
	 if (DEF_INST_top_INST_px_INST_coax_1_DEF_WILL_FIRE_RL__activate1)
	   INST_top.INST_px.INST_coax_1.RL__activate1();
	 if (DEF_INST_top_INST_px_INST_coax_1_DEF_WILL_FIRE_RL_inCCLK)
	   INST_top.INST_px.INST_coax_1.RL_inCCLK();
	 INST_top.INST_px.INST_mem_wDataOut.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_px.INST_mem_wDataIn.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_px.INST_mem_pwClear.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_px.INST_mem_pwEnqueue.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_px.INST_mem_pwDequeue.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_px.INST_mem_memory.clkA((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_px.INST_mem_memory.clkB((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_px.INST_p8_rv.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_px.INST_p7_rv.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_px.INST_p6_rv.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_px.INST_p5_rv.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_px.INST_p4_rv.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_px.INST_p3_rv.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_px.INST_p2_rv.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_px.INST_p1_rv.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_px.INST_p0_rv.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_px.INST_coax_1.INST_p3_rv.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_px.INST_coax_1.INST_p2_rv.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_px.INST_coax_1.INST_p1_rv.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_px.INST_coax_1.INST_p0_rv.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_px.INST_coax_0.INST_p3_rv.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_px.INST_coax_0.INST_p2_rv.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_px.INST_coax_0.INST_p1_rv.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_px.INST_coax_0.INST_p0_rv.clk((tUInt8)1u, (tUInt8)1u);
	 if (do_reset_ticks(simHdl))
	 {
	   INST_top.INST_px.INST_coax_0.INST__unnamed_.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_0.INST__unnamed__1.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_0.INST__unnamed__0_1.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_0.INST__unnamed__2.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_0.INST__unnamed__1_1.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_0.INST__unnamed__3.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_0.INST__unnamed__2_1.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_0.INST__unnamed__4.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_0.INST__unnamed__3_1.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_0.INST__unnamed__5.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_0.INST__unnamed__4_1.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_0.INST__unnamed__6.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_0.INST__unnamed__5_1.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_0.INST__unnamed__7.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_0.INST__unnamed__6_1.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_0.INST__unnamed__8.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_0.INST__unnamed__7_1.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_0.INST_window_0_0.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_0.INST_window2_0_0.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_0.INST_window_0_1.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_0.INST_window2_0_1.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_0.INST_window_0_2.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_0.INST_window2_0_2.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_0.INST_window_0_3.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_0.INST_window2_0_3.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_0.INST_window_0_4.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_0.INST_window2_0_4.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_0.INST_window_0_5.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_0.INST_window2_0_5.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_0.INST_window_0_6.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_0.INST_window2_0_6.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_0.INST_window_0_7.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_0.INST_window2_0_7.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_0.INST_window_1_0.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_0.INST_window2_1_0.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_0.INST_window_1_1.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_0.INST_window2_1_1.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_0.INST_window_1_2.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_0.INST_window2_1_2.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_0.INST_window_1_3.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_0.INST_window2_1_3.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_0.INST_window_1_4.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_0.INST_window2_1_4.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_0.INST_window_1_5.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_0.INST_window2_1_5.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_0.INST_window_1_6.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_0.INST_window2_1_6.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_0.INST_window_1_7.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_0.INST_window2_1_7.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_0.INST_window_2_0.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_0.INST_window2_2_0.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_0.INST_window_2_1.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_0.INST_window2_2_1.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_0.INST_window_2_2.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_0.INST_window2_2_2.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_0.INST_window_2_3.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_0.INST_window2_2_3.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_0.INST_window_2_4.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_0.INST_window2_2_4.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_0.INST_window_2_5.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_0.INST_window2_2_5.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_0.INST_window_2_6.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_0.INST_window2_2_6.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_0.INST_window_2_7.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_0.INST_window2_2_7.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_0.INST_window_3_0.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_0.INST_window2_3_0.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_0.INST_window_3_1.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_0.INST_window2_3_1.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_0.INST_window_3_2.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_0.INST_window2_3_2.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_0.INST_window_3_3.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_0.INST_window2_3_3.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_0.INST_window_3_4.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_0.INST_window2_3_4.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_0.INST_window_3_5.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_0.INST_window2_3_5.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_0.INST_window_3_6.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_0.INST_window2_3_6.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_0.INST_window_3_7.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_0.INST_window2_3_7.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_0.INST_window_4_0.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_0.INST_window2_4_0.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_0.INST_window_4_1.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_0.INST_window2_4_1.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_0.INST_window_4_2.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_0.INST_window2_4_2.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_0.INST_window_4_3.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_0.INST_window2_4_3.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_0.INST_window_4_4.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_0.INST_window2_4_4.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_0.INST_window_4_5.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_0.INST_window2_4_5.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_0.INST_window_4_6.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_0.INST_window2_4_6.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_0.INST_window_4_7.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_0.INST_window2_4_7.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_0.INST_window_5_0.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_0.INST_window2_5_0.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_0.INST_window_5_1.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_0.INST_window2_5_1.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_0.INST_window_5_2.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_0.INST_window2_5_2.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_0.INST_window_5_3.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_0.INST_window2_5_3.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_0.INST_window_5_4.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_0.INST_window2_5_4.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_0.INST_window_5_5.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_0.INST_window2_5_5.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_0.INST_window_5_6.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_0.INST_window2_5_6.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_0.INST_window_5_7.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_0.INST_window2_5_7.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_0.INST_window_6_0.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_0.INST_window2_6_0.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_0.INST_window_6_1.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_0.INST_window2_6_1.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_0.INST_window_6_2.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_0.INST_window2_6_2.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_0.INST_window_6_3.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_0.INST_window2_6_3.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_0.INST_window_6_4.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_0.INST_window2_6_4.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_0.INST_window_6_5.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_0.INST_window2_6_5.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_0.INST_window_6_6.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_0.INST_window2_6_6.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_0.INST_window_6_7.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_0.INST_window2_6_7.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_0.INST_window_7_0.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_0.INST_window2_7_0.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_0.INST_window_7_1.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_0.INST_window2_7_1.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_0.INST_window_7_2.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_0.INST_window2_7_2.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_0.INST_window_7_3.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_0.INST_window2_7_3.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_0.INST_window_7_4.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_0.INST_window2_7_4.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_0.INST_window_7_5.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_0.INST_window2_7_5.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_0.INST_window_7_6.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_0.INST_window2_7_6.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_0.INST_window_7_7.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_0.INST_window2_7_7.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_0.INST_cx.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_0.INST_kernel.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_0.INST_count.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_0.INST_width.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_0.INST_p0_rv.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_px.INST_coax_0.INST_p1_rv.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_px.INST_coax_0.INST_p2_rv.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_px.INST_coax_0.INST_p3_rv.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_px.INST_coax_0.INST_inQ.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_px.INST_coax_1.INST__unnamed_.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_1.INST__unnamed__1.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_1.INST__unnamed__0_1.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_1.INST__unnamed__2.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_1.INST__unnamed__1_1.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_1.INST__unnamed__3.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_1.INST__unnamed__2_1.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_1.INST__unnamed__4.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_1.INST__unnamed__3_1.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_1.INST__unnamed__5.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_1.INST__unnamed__4_1.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_1.INST__unnamed__6.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_1.INST__unnamed__5_1.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_1.INST__unnamed__7.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_1.INST__unnamed__6_1.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_1.INST__unnamed__8.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_1.INST__unnamed__7_1.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_1.INST_window_0_0.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_1.INST_window2_0_0.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_1.INST_window_0_1.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_1.INST_window2_0_1.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_1.INST_window_0_2.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_1.INST_window2_0_2.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_1.INST_window_0_3.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_1.INST_window2_0_3.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_1.INST_window_0_4.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_1.INST_window2_0_4.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_1.INST_window_0_5.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_1.INST_window2_0_5.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_1.INST_window_0_6.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_1.INST_window2_0_6.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_1.INST_window_0_7.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_1.INST_window2_0_7.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_1.INST_window_1_0.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_1.INST_window2_1_0.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_1.INST_window_1_1.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_1.INST_window2_1_1.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_1.INST_window_1_2.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_1.INST_window2_1_2.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_1.INST_window_1_3.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_1.INST_window2_1_3.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_1.INST_window_1_4.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_1.INST_window2_1_4.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_1.INST_window_1_5.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_1.INST_window2_1_5.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_1.INST_window_1_6.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_1.INST_window2_1_6.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_1.INST_window_1_7.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_1.INST_window2_1_7.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_1.INST_window_2_0.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_1.INST_window2_2_0.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_1.INST_window_2_1.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_1.INST_window2_2_1.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_1.INST_window_2_2.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_1.INST_window2_2_2.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_1.INST_window_2_3.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_1.INST_window2_2_3.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_1.INST_window_2_4.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_1.INST_window2_2_4.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_1.INST_window_2_5.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_1.INST_window2_2_5.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_1.INST_window_2_6.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_1.INST_window2_2_6.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_1.INST_window_2_7.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_1.INST_window2_2_7.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_1.INST_window_3_0.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_1.INST_window2_3_0.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_1.INST_window_3_1.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_1.INST_window2_3_1.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_1.INST_window_3_2.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_1.INST_window2_3_2.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_1.INST_window_3_3.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_1.INST_window2_3_3.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_1.INST_window_3_4.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_1.INST_window2_3_4.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_1.INST_window_3_5.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_1.INST_window2_3_5.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_1.INST_window_3_6.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_1.INST_window2_3_6.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_1.INST_window_3_7.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_1.INST_window2_3_7.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_1.INST_window_4_0.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_1.INST_window2_4_0.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_1.INST_window_4_1.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_1.INST_window2_4_1.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_1.INST_window_4_2.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_1.INST_window2_4_2.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_1.INST_window_4_3.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_1.INST_window2_4_3.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_1.INST_window_4_4.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_1.INST_window2_4_4.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_1.INST_window_4_5.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_1.INST_window2_4_5.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_1.INST_window_4_6.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_1.INST_window2_4_6.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_1.INST_window_4_7.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_1.INST_window2_4_7.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_1.INST_window_5_0.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_1.INST_window2_5_0.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_1.INST_window_5_1.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_1.INST_window2_5_1.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_1.INST_window_5_2.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_1.INST_window2_5_2.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_1.INST_window_5_3.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_1.INST_window2_5_3.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_1.INST_window_5_4.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_1.INST_window2_5_4.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_1.INST_window_5_5.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_1.INST_window2_5_5.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_1.INST_window_5_6.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_1.INST_window2_5_6.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_1.INST_window_5_7.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_1.INST_window2_5_7.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_1.INST_window_6_0.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_1.INST_window2_6_0.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_1.INST_window_6_1.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_1.INST_window2_6_1.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_1.INST_window_6_2.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_1.INST_window2_6_2.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_1.INST_window_6_3.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_1.INST_window2_6_3.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_1.INST_window_6_4.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_1.INST_window2_6_4.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_1.INST_window_6_5.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_1.INST_window2_6_5.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_1.INST_window_6_6.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_1.INST_window2_6_6.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_1.INST_window_6_7.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_1.INST_window2_6_7.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_1.INST_window_7_0.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_1.INST_window2_7_0.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_1.INST_window_7_1.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_1.INST_window2_7_1.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_1.INST_window_7_2.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_1.INST_window2_7_2.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_1.INST_window_7_3.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_1.INST_window2_7_3.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_1.INST_window_7_4.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_1.INST_window2_7_4.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_1.INST_window_7_5.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_1.INST_window2_7_5.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_1.INST_window_7_6.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_1.INST_window2_7_6.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_1.INST_window_7_7.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_1.INST_window2_7_7.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_1.INST_cx.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_1.INST_kernel.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_1.INST_count.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_1.INST_width.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_coax_1.INST_p0_rv.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_px.INST_coax_1.INST_p1_rv.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_px.INST_coax_1.INST_p2_rv.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_px.INST_coax_1.INST_p3_rv.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_px.INST_coax_1.INST_inQ.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_px.INST_kernel.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_mx.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_cx.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_cx2.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_width.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST__unnamed_.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST__unnamed__1.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST__unnamed__0_1.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST__unnamed__0_2.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST__unnamed__0_3.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST__unnamed__0_4.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST__unnamed__0_5.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST__unnamed__0_6.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST__unnamed__0_7.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST__unnamed__2.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST__unnamed__1_1.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST__unnamed__1_2.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST__unnamed__1_3.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST__unnamed__1_4.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST__unnamed__1_5.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST__unnamed__1_6.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST__unnamed__1_7.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST__unnamed__3.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST__unnamed__2_1.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST__unnamed__2_2.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST__unnamed__2_3.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST__unnamed__2_4.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST__unnamed__2_5.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST__unnamed__2_6.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST__unnamed__2_7.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST__unnamed__4.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST__unnamed__3_1.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST__unnamed__3_2.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST__unnamed__3_3.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST__unnamed__3_4.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST__unnamed__3_5.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST__unnamed__3_6.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST__unnamed__3_7.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST__unnamed__5.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST__unnamed__4_1.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST__unnamed__4_2.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST__unnamed__4_3.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST__unnamed__4_4.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST__unnamed__4_5.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST__unnamed__4_6.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST__unnamed__4_7.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST__unnamed__6.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST__unnamed__5_1.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST__unnamed__5_2.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST__unnamed__5_3.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST__unnamed__5_4.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST__unnamed__5_5.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST__unnamed__5_6.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST__unnamed__5_7.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST__unnamed__7.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST__unnamed__6_1.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST__unnamed__6_2.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST__unnamed__6_3.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST__unnamed__6_4.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST__unnamed__6_5.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST__unnamed__6_6.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST__unnamed__6_7.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST__unnamed__8.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST__unnamed__7_1.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST__unnamed__7_2.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST__unnamed__7_3.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST__unnamed__7_4.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST__unnamed__7_5.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST__unnamed__7_6.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST__unnamed__7_7.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_p0_rv.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_px.INST_p1_rv.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_px.INST_p2_rv.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_px.INST_p3_rv.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_px.INST_p4_rv.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_px.INST_p5_rv.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_px.INST_p6_rv.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_px.INST_p7_rv.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_px.INST_p8_rv.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_px.INST_mem_rWrPtr.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_mem_rRdPtr.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_mem_rCache.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_px.INST_inQ.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_px.INST__unnamed__9.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_init.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_inL.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_value.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_value2.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_count.rst_tick__clk__1((tUInt8)1u);
	 }
       };

/* Model creation/destruction functions */

void MODEL_mkFlowTest::create_model(tSimStateHdl simHdl, bool master)
{
  sim_hdl = simHdl;
  init_reset_request_counters(sim_hdl);
  mkFlowTest_instance = new MOD_mkFlowTest(sim_hdl, "top", NULL);
  bk_get_or_define_clock(sim_hdl, "CLK");
  if (master)
  {
    bk_alter_clock(sim_hdl, bk_get_clock_by_name(sim_hdl, "CLK"), CLK_LOW, false, 0llu, 5llu, 5llu);
    bk_use_default_reset(sim_hdl);
  }
  bk_set_clock_event_fn(sim_hdl,
			bk_get_clock_by_name(sim_hdl, "CLK"),
			schedule_posedge_CLK,
			NULL,
			(tEdgeDirection)(POSEDGE));
  (mkFlowTest_instance->INST_px.INST_coax_0.INST_p0_rv.set_clk_0)("CLK");
  (mkFlowTest_instance->INST_px.INST_coax_0.INST_p1_rv.set_clk_0)("CLK");
  (mkFlowTest_instance->INST_px.INST_coax_0.INST_p2_rv.set_clk_0)("CLK");
  (mkFlowTest_instance->INST_px.INST_coax_0.INST_p3_rv.set_clk_0)("CLK");
  (mkFlowTest_instance->INST_px.INST_coax_0.INST_inQ.set_clk_0)("CLK");
  (mkFlowTest_instance->INST_px.INST_coax_0.set_clk_0)("CLK");
  (mkFlowTest_instance->INST_px.INST_coax_1.INST_p0_rv.set_clk_0)("CLK");
  (mkFlowTest_instance->INST_px.INST_coax_1.INST_p1_rv.set_clk_0)("CLK");
  (mkFlowTest_instance->INST_px.INST_coax_1.INST_p2_rv.set_clk_0)("CLK");
  (mkFlowTest_instance->INST_px.INST_coax_1.INST_p3_rv.set_clk_0)("CLK");
  (mkFlowTest_instance->INST_px.INST_coax_1.INST_inQ.set_clk_0)("CLK");
  (mkFlowTest_instance->INST_px.INST_coax_1.set_clk_0)("CLK");
  (mkFlowTest_instance->INST_px.INST_p0_rv.set_clk_0)("CLK");
  (mkFlowTest_instance->INST_px.INST_p1_rv.set_clk_0)("CLK");
  (mkFlowTest_instance->INST_px.INST_p2_rv.set_clk_0)("CLK");
  (mkFlowTest_instance->INST_px.INST_p3_rv.set_clk_0)("CLK");
  (mkFlowTest_instance->INST_px.INST_p4_rv.set_clk_0)("CLK");
  (mkFlowTest_instance->INST_px.INST_p5_rv.set_clk_0)("CLK");
  (mkFlowTest_instance->INST_px.INST_p6_rv.set_clk_0)("CLK");
  (mkFlowTest_instance->INST_px.INST_p7_rv.set_clk_0)("CLK");
  (mkFlowTest_instance->INST_px.INST_p8_rv.set_clk_0)("CLK");
  (mkFlowTest_instance->INST_px.INST_mem_memory.set_clk_1)("CLK");
  (mkFlowTest_instance->INST_px.INST_mem_memory.set_clk_0)("CLK");
  (mkFlowTest_instance->INST_px.INST_mem_pwDequeue.set_clk_0)("CLK");
  (mkFlowTest_instance->INST_px.INST_mem_pwEnqueue.set_clk_0)("CLK");
  (mkFlowTest_instance->INST_px.INST_mem_pwClear.set_clk_0)("CLK");
  (mkFlowTest_instance->INST_px.INST_mem_wDataIn.set_clk_0)("CLK");
  (mkFlowTest_instance->INST_px.INST_mem_wDataOut.set_clk_0)("CLK");
  (mkFlowTest_instance->INST_px.INST_inQ.set_clk_0)("CLK");
  (mkFlowTest_instance->INST_px.set_clk_0)("CLK");
  (mkFlowTest_instance->set_clk_0)("CLK");
}
void MODEL_mkFlowTest::destroy_model()
{
  delete mkFlowTest_instance;
  mkFlowTest_instance = NULL;
}
void MODEL_mkFlowTest::reset_model(bool asserted)
{
  (mkFlowTest_instance->reset_RST_N)(asserted ? (tUInt8)0u : (tUInt8)1u);
}
void * MODEL_mkFlowTest::get_instance()
{
  return mkFlowTest_instance;
}

/* Fill in version numbers */
void MODEL_mkFlowTest::get_version(char const **name, char const **build)
{
  *name = "2023.01-6-g034050db";
  *build = "034050db";
}

/* Get the model creation time */
time_t MODEL_mkFlowTest::get_creation_time()
{
  
  /* Fri May 12 11:35:38 UTC 2023 */
  return 1683891338llu;
}

/* State dumping function */
void MODEL_mkFlowTest::dump_state()
{
  (mkFlowTest_instance->dump_state)(0u);
}

/* VCD dumping functions */
MOD_mkFlowTest & mkFlowTest_backing(tSimStateHdl simHdl)
{
  static MOD_mkFlowTest *instance = NULL;
  if (instance == NULL)
  {
    vcd_set_backing_instance(simHdl, true);
    instance = new MOD_mkFlowTest(simHdl, "top", NULL);
    vcd_set_backing_instance(simHdl, false);
  }
  return *instance;
}
void MODEL_mkFlowTest::dump_VCD_defs()
{
  (mkFlowTest_instance->dump_VCD_defs)(vcd_depth(sim_hdl));
}
void MODEL_mkFlowTest::dump_VCD(tVCDDumpType dt)
{
  (mkFlowTest_instance->dump_VCD)(dt, vcd_depth(sim_hdl), mkFlowTest_backing(sim_hdl));
}
