//
// Generated by Bluespec Compiler, version untagged-gad02e931 (build ad02e931)
//
// On Fri Jan 21 12:29:21 GMT 2022
//
//
// Ports:
// Name                         I/O  size props
// RDY_put                        O     1 reg
// get                            O   784 reg
// RDY_get                        O     1
// RDY_configure                  O     1 const
// CLK                            I     1 clock
// RST_N                          I     1 reset
// put_datas                      I    64 reg
// configure_a                    I     4 reg
// configure_m                    I     8 reg
// configure_wx                   I    12 reg
// EN_put                         I     1
// EN_configure                   I     1
// EN_get                         I     1
//
// No combinational paths from inputs to outputs
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkMerge(CLK,
	       RST_N,

	       put_datas,
	       EN_put,
	       RDY_put,

	       EN_get,
	       get,
	       RDY_get,

	       configure_a,
	       configure_m,
	       configure_wx,
	       EN_configure,
	       RDY_configure);
  input  CLK;
  input  RST_N;

  // action method put
  input  [63 : 0] put_datas;
  input  EN_put;
  output RDY_put;

  // actionvalue method get
  input  EN_get;
  output [783 : 0] get;
  output RDY_get;

  // action method configure
  input  [3 : 0] configure_a;
  input  [7 : 0] configure_m;
  input  [11 : 0] configure_wx;
  input  EN_configure;
  output RDY_configure;

  // signals for module outputs
  wire [783 : 0] get;
  wire RDY_configure, RDY_get, RDY_put;

  // inlined wires
  wire [1 : 0] p0_rv$port1__read,
	       p0_rv$port2__read,
	       p1_rv$port1__read,
	       p1_rv$port2__read,
	       p2_rv$port1__read,
	       p2_rv$port2__read,
	       p3_rv$port1__read,
	       p3_rv$port2__read,
	       p4_rv$port1__read,
	       p4_rv$port2__read,
	       p5_rv$port1__read,
	       p5_rv$port2__read,
	       p6_rv$port1__read,
	       p6_rv$port2__read,
	       p7_rv$port1__read,
	       p7_rv$port2__read;
  wire mem_pwDequeue$whas,
       mem_pwEnqueue$whas,
       p0_rv$EN_port1__write,
       p1_rv$EN_port0__write,
       p2_rv$EN_port0__write,
       p2_rv$EN_port1__write,
       p3_rv$EN_port0__write,
       p3_rv$EN_port1__write,
       p4_rv$EN_port0__write,
       p4_rv$EN_port1__write,
       p5_rv$EN_port0__write,
       p5_rv$EN_port1__write,
       p6_rv$EN_port0__write,
       p6_rv$EN_port1__write,
       p7_rv$EN_port1__write;

  // register _unnamed_
  reg [7 : 0] _unnamed_;
  wire [7 : 0] _unnamed_$D_IN;
  wire _unnamed_$EN;

  // register _unnamed__0_1
  reg [15 : 0] _unnamed__0_1;
  wire [15 : 0] _unnamed__0_1$D_IN;
  wire _unnamed__0_1$EN;

  // register _unnamed__0_2
  reg [23 : 0] _unnamed__0_2;
  wire [23 : 0] _unnamed__0_2$D_IN;
  wire _unnamed__0_2$EN;

  // register _unnamed__0_3
  reg [31 : 0] _unnamed__0_3;
  wire [31 : 0] _unnamed__0_3$D_IN;
  wire _unnamed__0_3$EN;

  // register _unnamed__0_4
  reg [39 : 0] _unnamed__0_4;
  wire [39 : 0] _unnamed__0_4$D_IN;
  wire _unnamed__0_4$EN;

  // register _unnamed__0_5
  reg [47 : 0] _unnamed__0_5;
  wire [47 : 0] _unnamed__0_5$D_IN;
  wire _unnamed__0_5$EN;

  // register _unnamed__0_6
  reg [55 : 0] _unnamed__0_6;
  wire [55 : 0] _unnamed__0_6$D_IN;
  wire _unnamed__0_6$EN;

  // register _unnamed__1
  reg [7 : 0] _unnamed__1;
  wire [7 : 0] _unnamed__1$D_IN;
  wire _unnamed__1$EN;

  // register _unnamed__10
  reg [55 : 0] _unnamed__10;
  wire [55 : 0] _unnamed__10$D_IN;
  wire _unnamed__10$EN;

  // register _unnamed__11
  reg [55 : 0] _unnamed__11;
  wire [55 : 0] _unnamed__11$D_IN;
  wire _unnamed__11$EN;

  // register _unnamed__12
  reg [55 : 0] _unnamed__12;
  wire [55 : 0] _unnamed__12$D_IN;
  wire _unnamed__12$EN;

  // register _unnamed__13
  reg [55 : 0] _unnamed__13;
  wire [55 : 0] _unnamed__13$D_IN;
  wire _unnamed__13$EN;

  // register _unnamed__14
  reg [55 : 0] _unnamed__14;
  wire [55 : 0] _unnamed__14$D_IN;
  wire _unnamed__14$EN;

  // register _unnamed__15
  reg [55 : 0] _unnamed__15;
  wire [55 : 0] _unnamed__15$D_IN;
  wire _unnamed__15$EN;

  // register _unnamed__16
  reg [55 : 0] _unnamed__16;
  wire [55 : 0] _unnamed__16$D_IN;
  wire _unnamed__16$EN;

  // register _unnamed__17
  reg [55 : 0] _unnamed__17;
  wire [55 : 0] _unnamed__17$D_IN;
  wire _unnamed__17$EN;

  // register _unnamed__18
  reg [55 : 0] _unnamed__18;
  wire [55 : 0] _unnamed__18$D_IN;
  wire _unnamed__18$EN;

  // register _unnamed__19
  reg [55 : 0] _unnamed__19;
  wire [55 : 0] _unnamed__19$D_IN;
  wire _unnamed__19$EN;

  // register _unnamed__1_1
  reg [15 : 0] _unnamed__1_1;
  wire [15 : 0] _unnamed__1_1$D_IN;
  wire _unnamed__1_1$EN;

  // register _unnamed__1_2
  reg [23 : 0] _unnamed__1_2;
  wire [23 : 0] _unnamed__1_2$D_IN;
  wire _unnamed__1_2$EN;

  // register _unnamed__1_3
  reg [31 : 0] _unnamed__1_3;
  wire [31 : 0] _unnamed__1_3$D_IN;
  wire _unnamed__1_3$EN;

  // register _unnamed__1_4
  reg [39 : 0] _unnamed__1_4;
  wire [39 : 0] _unnamed__1_4$D_IN;
  wire _unnamed__1_4$EN;

  // register _unnamed__1_5
  reg [47 : 0] _unnamed__1_5;
  wire [47 : 0] _unnamed__1_5$D_IN;
  wire _unnamed__1_5$EN;

  // register _unnamed__1_6
  reg [55 : 0] _unnamed__1_6;
  wire [55 : 0] _unnamed__1_6$D_IN;
  wire _unnamed__1_6$EN;

  // register _unnamed__2
  reg [7 : 0] _unnamed__2;
  wire [7 : 0] _unnamed__2$D_IN;
  wire _unnamed__2$EN;

  // register _unnamed__20
  reg [55 : 0] _unnamed__20;
  wire [55 : 0] _unnamed__20$D_IN;
  wire _unnamed__20$EN;

  // register _unnamed__21
  reg [55 : 0] _unnamed__21;
  wire [55 : 0] _unnamed__21$D_IN;
  wire _unnamed__21$EN;

  // register _unnamed__22
  reg [55 : 0] _unnamed__22;
  wire [55 : 0] _unnamed__22$D_IN;
  wire _unnamed__22$EN;

  // register _unnamed__23
  reg [55 : 0] _unnamed__23;
  wire [55 : 0] _unnamed__23$D_IN;
  wire _unnamed__23$EN;

  // register _unnamed__24
  reg [55 : 0] _unnamed__24;
  wire [55 : 0] _unnamed__24$D_IN;
  wire _unnamed__24$EN;

  // register _unnamed__25
  reg [55 : 0] _unnamed__25;
  wire [55 : 0] _unnamed__25$D_IN;
  wire _unnamed__25$EN;

  // register _unnamed__26
  reg [55 : 0] _unnamed__26;
  wire [55 : 0] _unnamed__26$D_IN;
  wire _unnamed__26$EN;

  // register _unnamed__27
  reg [55 : 0] _unnamed__27;
  wire [55 : 0] _unnamed__27$D_IN;
  wire _unnamed__27$EN;

  // register _unnamed__28
  reg [55 : 0] _unnamed__28;
  wire [55 : 0] _unnamed__28$D_IN;
  wire _unnamed__28$EN;

  // register _unnamed__29
  reg [55 : 0] _unnamed__29;
  wire [55 : 0] _unnamed__29$D_IN;
  wire _unnamed__29$EN;

  // register _unnamed__2_1
  reg [15 : 0] _unnamed__2_1;
  wire [15 : 0] _unnamed__2_1$D_IN;
  wire _unnamed__2_1$EN;

  // register _unnamed__2_2
  reg [23 : 0] _unnamed__2_2;
  wire [23 : 0] _unnamed__2_2$D_IN;
  wire _unnamed__2_2$EN;

  // register _unnamed__2_3
  reg [31 : 0] _unnamed__2_3;
  wire [31 : 0] _unnamed__2_3$D_IN;
  wire _unnamed__2_3$EN;

  // register _unnamed__2_4
  reg [39 : 0] _unnamed__2_4;
  wire [39 : 0] _unnamed__2_4$D_IN;
  wire _unnamed__2_4$EN;

  // register _unnamed__2_5
  reg [47 : 0] _unnamed__2_5;
  wire [47 : 0] _unnamed__2_5$D_IN;
  wire _unnamed__2_5$EN;

  // register _unnamed__2_6
  reg [55 : 0] _unnamed__2_6;
  wire [55 : 0] _unnamed__2_6$D_IN;
  wire _unnamed__2_6$EN;

  // register _unnamed__3
  reg [7 : 0] _unnamed__3;
  wire [7 : 0] _unnamed__3$D_IN;
  wire _unnamed__3$EN;

  // register _unnamed__30
  reg [55 : 0] _unnamed__30;
  wire [55 : 0] _unnamed__30$D_IN;
  wire _unnamed__30$EN;

  // register _unnamed__31
  reg [55 : 0] _unnamed__31;
  wire [55 : 0] _unnamed__31$D_IN;
  wire _unnamed__31$EN;

  // register _unnamed__32
  reg [55 : 0] _unnamed__32;
  wire [55 : 0] _unnamed__32$D_IN;
  wire _unnamed__32$EN;

  // register _unnamed__33
  reg [55 : 0] _unnamed__33;
  wire [55 : 0] _unnamed__33$D_IN;
  wire _unnamed__33$EN;

  // register _unnamed__34
  reg [55 : 0] _unnamed__34;
  wire [55 : 0] _unnamed__34$D_IN;
  wire _unnamed__34$EN;

  // register _unnamed__35
  reg [55 : 0] _unnamed__35;
  wire [55 : 0] _unnamed__35$D_IN;
  wire _unnamed__35$EN;

  // register _unnamed__36
  reg [55 : 0] _unnamed__36;
  wire [55 : 0] _unnamed__36$D_IN;
  wire _unnamed__36$EN;

  // register _unnamed__37
  reg [55 : 0] _unnamed__37;
  wire [55 : 0] _unnamed__37$D_IN;
  wire _unnamed__37$EN;

  // register _unnamed__38
  reg [55 : 0] _unnamed__38;
  wire [55 : 0] _unnamed__38$D_IN;
  wire _unnamed__38$EN;

  // register _unnamed__39
  reg [55 : 0] _unnamed__39;
  wire [55 : 0] _unnamed__39$D_IN;
  wire _unnamed__39$EN;

  // register _unnamed__3_1
  reg [15 : 0] _unnamed__3_1;
  wire [15 : 0] _unnamed__3_1$D_IN;
  wire _unnamed__3_1$EN;

  // register _unnamed__3_2
  reg [23 : 0] _unnamed__3_2;
  wire [23 : 0] _unnamed__3_2$D_IN;
  wire _unnamed__3_2$EN;

  // register _unnamed__3_3
  reg [31 : 0] _unnamed__3_3;
  wire [31 : 0] _unnamed__3_3$D_IN;
  wire _unnamed__3_3$EN;

  // register _unnamed__3_4
  reg [39 : 0] _unnamed__3_4;
  wire [39 : 0] _unnamed__3_4$D_IN;
  wire _unnamed__3_4$EN;

  // register _unnamed__3_5
  reg [47 : 0] _unnamed__3_5;
  wire [47 : 0] _unnamed__3_5$D_IN;
  wire _unnamed__3_5$EN;

  // register _unnamed__3_6
  reg [55 : 0] _unnamed__3_6;
  wire [55 : 0] _unnamed__3_6$D_IN;
  wire _unnamed__3_6$EN;

  // register _unnamed__4
  reg [7 : 0] _unnamed__4;
  wire [7 : 0] _unnamed__4$D_IN;
  wire _unnamed__4$EN;

  // register _unnamed__40
  reg [55 : 0] _unnamed__40;
  wire [55 : 0] _unnamed__40$D_IN;
  wire _unnamed__40$EN;

  // register _unnamed__41
  reg [55 : 0] _unnamed__41;
  wire [55 : 0] _unnamed__41$D_IN;
  wire _unnamed__41$EN;

  // register _unnamed__42
  reg [55 : 0] _unnamed__42;
  wire [55 : 0] _unnamed__42$D_IN;
  wire _unnamed__42$EN;

  // register _unnamed__43
  reg [55 : 0] _unnamed__43;
  wire [55 : 0] _unnamed__43$D_IN;
  wire _unnamed__43$EN;

  // register _unnamed__44
  reg [55 : 0] _unnamed__44;
  wire [55 : 0] _unnamed__44$D_IN;
  wire _unnamed__44$EN;

  // register _unnamed__45
  reg [55 : 0] _unnamed__45;
  wire [55 : 0] _unnamed__45$D_IN;
  wire _unnamed__45$EN;

  // register _unnamed__46
  reg [55 : 0] _unnamed__46;
  wire [55 : 0] _unnamed__46$D_IN;
  wire _unnamed__46$EN;

  // register _unnamed__47
  reg [55 : 0] _unnamed__47;
  wire [55 : 0] _unnamed__47$D_IN;
  wire _unnamed__47$EN;

  // register _unnamed__48
  reg [55 : 0] _unnamed__48;
  wire [55 : 0] _unnamed__48$D_IN;
  wire _unnamed__48$EN;

  // register _unnamed__49
  reg [55 : 0] _unnamed__49;
  wire [55 : 0] _unnamed__49$D_IN;
  wire _unnamed__49$EN;

  // register _unnamed__4_1
  reg [15 : 0] _unnamed__4_1;
  wire [15 : 0] _unnamed__4_1$D_IN;
  wire _unnamed__4_1$EN;

  // register _unnamed__4_2
  reg [23 : 0] _unnamed__4_2;
  wire [23 : 0] _unnamed__4_2$D_IN;
  wire _unnamed__4_2$EN;

  // register _unnamed__4_3
  reg [31 : 0] _unnamed__4_3;
  wire [31 : 0] _unnamed__4_3$D_IN;
  wire _unnamed__4_3$EN;

  // register _unnamed__4_4
  reg [39 : 0] _unnamed__4_4;
  wire [39 : 0] _unnamed__4_4$D_IN;
  wire _unnamed__4_4$EN;

  // register _unnamed__4_5
  reg [47 : 0] _unnamed__4_5;
  wire [47 : 0] _unnamed__4_5$D_IN;
  wire _unnamed__4_5$EN;

  // register _unnamed__4_6
  reg [55 : 0] _unnamed__4_6;
  wire [55 : 0] _unnamed__4_6$D_IN;
  wire _unnamed__4_6$EN;

  // register _unnamed__5
  reg [7 : 0] _unnamed__5;
  wire [7 : 0] _unnamed__5$D_IN;
  wire _unnamed__5$EN;

  // register _unnamed__50
  reg [55 : 0] _unnamed__50;
  wire [55 : 0] _unnamed__50$D_IN;
  wire _unnamed__50$EN;

  // register _unnamed__51
  reg [55 : 0] _unnamed__51;
  wire [55 : 0] _unnamed__51$D_IN;
  wire _unnamed__51$EN;

  // register _unnamed__52
  reg [55 : 0] _unnamed__52;
  wire [55 : 0] _unnamed__52$D_IN;
  wire _unnamed__52$EN;

  // register _unnamed__53
  reg [55 : 0] _unnamed__53;
  wire [55 : 0] _unnamed__53$D_IN;
  wire _unnamed__53$EN;

  // register _unnamed__54
  reg [55 : 0] _unnamed__54;
  wire [55 : 0] _unnamed__54$D_IN;
  wire _unnamed__54$EN;

  // register _unnamed__55
  reg [55 : 0] _unnamed__55;
  wire [55 : 0] _unnamed__55$D_IN;
  wire _unnamed__55$EN;

  // register _unnamed__56
  reg [55 : 0] _unnamed__56;
  wire [55 : 0] _unnamed__56$D_IN;
  wire _unnamed__56$EN;

  // register _unnamed__57
  reg [55 : 0] _unnamed__57;
  wire [55 : 0] _unnamed__57$D_IN;
  wire _unnamed__57$EN;

  // register _unnamed__58
  reg [55 : 0] _unnamed__58;
  wire [55 : 0] _unnamed__58$D_IN;
  wire _unnamed__58$EN;

  // register _unnamed__59
  reg [55 : 0] _unnamed__59;
  wire [55 : 0] _unnamed__59$D_IN;
  wire _unnamed__59$EN;

  // register _unnamed__5_1
  reg [15 : 0] _unnamed__5_1;
  wire [15 : 0] _unnamed__5_1$D_IN;
  wire _unnamed__5_1$EN;

  // register _unnamed__5_2
  reg [23 : 0] _unnamed__5_2;
  wire [23 : 0] _unnamed__5_2$D_IN;
  wire _unnamed__5_2$EN;

  // register _unnamed__5_3
  reg [31 : 0] _unnamed__5_3;
  wire [31 : 0] _unnamed__5_3$D_IN;
  wire _unnamed__5_3$EN;

  // register _unnamed__5_4
  reg [39 : 0] _unnamed__5_4;
  wire [39 : 0] _unnamed__5_4$D_IN;
  wire _unnamed__5_4$EN;

  // register _unnamed__5_5
  reg [47 : 0] _unnamed__5_5;
  wire [47 : 0] _unnamed__5_5$D_IN;
  wire _unnamed__5_5$EN;

  // register _unnamed__5_6
  reg [55 : 0] _unnamed__5_6;
  wire [55 : 0] _unnamed__5_6$D_IN;
  wire _unnamed__5_6$EN;

  // register _unnamed__6
  reg [7 : 0] _unnamed__6;
  wire [7 : 0] _unnamed__6$D_IN;
  wire _unnamed__6$EN;

  // register _unnamed__60
  reg [55 : 0] _unnamed__60;
  wire [55 : 0] _unnamed__60$D_IN;
  wire _unnamed__60$EN;

  // register _unnamed__61
  reg [55 : 0] _unnamed__61;
  wire [55 : 0] _unnamed__61$D_IN;
  wire _unnamed__61$EN;

  // register _unnamed__62
  reg [55 : 0] _unnamed__62;
  wire [55 : 0] _unnamed__62$D_IN;
  wire _unnamed__62$EN;

  // register _unnamed__63
  reg [55 : 0] _unnamed__63;
  wire [55 : 0] _unnamed__63$D_IN;
  wire _unnamed__63$EN;

  // register _unnamed__64
  reg [63 : 0] _unnamed__64;
  wire [63 : 0] _unnamed__64$D_IN;
  wire _unnamed__64$EN;

  // register _unnamed__6_1
  reg [15 : 0] _unnamed__6_1;
  wire [15 : 0] _unnamed__6_1$D_IN;
  wire _unnamed__6_1$EN;

  // register _unnamed__6_2
  reg [23 : 0] _unnamed__6_2;
  wire [23 : 0] _unnamed__6_2$D_IN;
  wire _unnamed__6_2$EN;

  // register _unnamed__6_3
  reg [31 : 0] _unnamed__6_3;
  wire [31 : 0] _unnamed__6_3$D_IN;
  wire _unnamed__6_3$EN;

  // register _unnamed__6_4
  reg [39 : 0] _unnamed__6_4;
  wire [39 : 0] _unnamed__6_4$D_IN;
  wire _unnamed__6_4$EN;

  // register _unnamed__6_5
  reg [47 : 0] _unnamed__6_5;
  wire [47 : 0] _unnamed__6_5$D_IN;
  wire _unnamed__6_5$EN;

  // register _unnamed__6_6
  reg [55 : 0] _unnamed__6_6;
  wire [55 : 0] _unnamed__6_6$D_IN;
  wire _unnamed__6_6$EN;

  // register _unnamed__7
  reg [7 : 0] _unnamed__7;
  wire [7 : 0] _unnamed__7$D_IN;
  wire _unnamed__7$EN;

  // register _unnamed__7_1
  reg [15 : 0] _unnamed__7_1;
  wire [15 : 0] _unnamed__7_1$D_IN;
  wire _unnamed__7_1$EN;

  // register _unnamed__7_2
  reg [23 : 0] _unnamed__7_2;
  wire [23 : 0] _unnamed__7_2$D_IN;
  wire _unnamed__7_2$EN;

  // register _unnamed__7_3
  reg [31 : 0] _unnamed__7_3;
  wire [31 : 0] _unnamed__7_3$D_IN;
  wire _unnamed__7_3$EN;

  // register _unnamed__7_4
  reg [39 : 0] _unnamed__7_4;
  wire [39 : 0] _unnamed__7_4$D_IN;
  wire _unnamed__7_4$EN;

  // register _unnamed__7_5
  reg [47 : 0] _unnamed__7_5;
  wire [47 : 0] _unnamed__7_5$D_IN;
  wire _unnamed__7_5$EN;

  // register _unnamed__7_6
  reg [55 : 0] _unnamed__7_6;
  wire [55 : 0] _unnamed__7_6$D_IN;
  wire _unnamed__7_6$EN;

  // register _unnamed__8
  reg [55 : 0] _unnamed__8;
  wire [55 : 0] _unnamed__8$D_IN;
  wire _unnamed__8$EN;

  // register _unnamed__9
  reg [55 : 0] _unnamed__9;
  wire [55 : 0] _unnamed__9$D_IN;
  wire _unnamed__9$EN;

  // register cx
  reg [11 : 0] cx;
  wire [11 : 0] cx$D_IN;
  wire cx$EN;

  // register cx2
  reg [11 : 0] cx2;
  wire [11 : 0] cx2$D_IN;
  wire cx2$EN;

  // register kernel
  reg [3 : 0] kernel;
  wire [3 : 0] kernel$D_IN;
  wire kernel$EN;

  // register mem_rCache
  reg [77 : 0] mem_rCache;
  wire [77 : 0] mem_rCache$D_IN;
  wire mem_rCache$EN;

  // register mem_rRdPtr
  reg [12 : 0] mem_rRdPtr;
  wire [12 : 0] mem_rRdPtr$D_IN;
  wire mem_rRdPtr$EN;

  // register mem_rWrPtr
  reg [12 : 0] mem_rWrPtr;
  wire [12 : 0] mem_rWrPtr$D_IN;
  wire mem_rWrPtr$EN;

  // register mx
  reg [7 : 0] mx;
  wire [7 : 0] mx$D_IN;
  wire mx$EN;

  // register p0_rv
  reg [1 : 0] p0_rv;
  wire [1 : 0] p0_rv$D_IN;
  wire p0_rv$EN;

  // register p1_rv
  reg [1 : 0] p1_rv;
  wire [1 : 0] p1_rv$D_IN;
  wire p1_rv$EN;

  // register p2_rv
  reg [1 : 0] p2_rv;
  wire [1 : 0] p2_rv$D_IN;
  wire p2_rv$EN;

  // register p3_rv
  reg [1 : 0] p3_rv;
  wire [1 : 0] p3_rv$D_IN;
  wire p3_rv$EN;

  // register p4_rv
  reg [1 : 0] p4_rv;
  wire [1 : 0] p4_rv$D_IN;
  wire p4_rv$EN;

  // register p5_rv
  reg [1 : 0] p5_rv;
  wire [1 : 0] p5_rv$D_IN;
  wire p5_rv$EN;

  // register p6_rv
  reg [1 : 0] p6_rv;
  wire [1 : 0] p6_rv$D_IN;
  wire p6_rv$EN;

  // register p7_rv
  reg [1 : 0] p7_rv;
  wire [1 : 0] p7_rv$D_IN;
  wire p7_rv$EN;

  // register width
  reg [11 : 0] width;
  wire [11 : 0] width$D_IN;
  wire width$EN;

  // ports of submodule inQ
  wire [63 : 0] inQ$D_IN, inQ$D_OUT;
  wire inQ$CLR, inQ$DEQ, inQ$EMPTY_N, inQ$ENQ, inQ$FULL_N;

  // ports of submodule mem_memory
  wire [63 : 0] mem_memory$DIA, mem_memory$DIB, mem_memory$DOB;
  wire [11 : 0] mem_memory$ADDRA, mem_memory$ADDRB;
  wire mem_memory$ENA, mem_memory$ENB, mem_memory$WEA, mem_memory$WEB;

  // rule scheduling signals
  wire WILL_FIRE_RL__activate1, WILL_FIRE_RL_initialLoad;

  // inputs to muxes for submodule ports
  wire [63 : 0] MUX_mem_wDataIn$wset_1__VAL_2;

  // remaining internal signals
  wire [63 : 0] IF_mem_wDataOut_whas__28_THEN_mem_wDataOut_wge_ETC___d239,
		d1__h16638,
		x3__h10014,
		x_wget__h9796;
  wire [47 : 0] x2__h11949,
		x2__h12872,
		x2__h13370,
		x2__h13868,
		x2__h14366,
		x2__h14864,
		x2__h15362,
		x__h12209,
		x__h12902,
		x__h13400,
		x__h13898,
		x__h14396,
		x__h14894,
		x__h15392;
  wire [39 : 0] x2__h11632,
		x2__h12787,
		x2__h13285,
		x2__h13783,
		x2__h14281,
		x2__h14779,
		x2__h15277,
		x__h11892,
		x__h12816,
		x__h13314,
		x__h13812,
		x__h14310,
		x__h14808,
		x__h15306;
  wire [31 : 0] x2__h11315,
		x2__h12702,
		x2__h13200,
		x2__h13698,
		x2__h14196,
		x2__h14694,
		x2__h15192,
		x__h11575,
		x__h12731,
		x__h13229,
		x__h13727,
		x__h14225,
		x__h14723,
		x__h15221;
  wire [23 : 0] x2__h10998,
		x2__h12617,
		x2__h13115,
		x2__h13613,
		x2__h14111,
		x2__h14609,
		x2__h15107,
		x__h11258,
		x__h12646,
		x__h13144,
		x__h13642,
		x__h14140,
		x__h14638,
		x__h15136;
  wire [12 : 0] x__h10097, x__h10186;
  wire NOT_mem_rRdPtr_read__7_EQ_mem_rWrPtr_read_25_2_ETC___d234,
       NOT_mem_rRdPtr_read__7_PLUS_2048_76_EQ_mem_rWr_ETC___d178,
       cx2_86_ULT_width_87___d188;

  // action method put
  assign RDY_put = inQ$FULL_N ;

  // actionvalue method get
  assign get =
	     { _unnamed__21,
	       _unnamed__20,
	       _unnamed__19,
	       _unnamed__18,
	       _unnamed__17,
	       _unnamed__16,
	       _unnamed__15,
	       _unnamed__14,
	       _unnamed__13,
	       _unnamed__12,
	       _unnamed__11,
	       _unnamed__10,
	       _unnamed__9,
	       _unnamed__8 } ;
  assign RDY_get = p7_rv[1] ;

  // action method configure
  assign RDY_configure = 1'd1 ;

  // submodule inQ
  FIFO2 #(.width(32'd64), .guarded(1'd1)) inQ(.RST(RST_N),
					      .CLK(CLK),
					      .D_IN(inQ$D_IN),
					      .ENQ(inQ$ENQ),
					      .DEQ(inQ$DEQ),
					      .CLR(inQ$CLR),
					      .D_OUT(inQ$D_OUT),
					      .FULL_N(inQ$FULL_N),
					      .EMPTY_N(inQ$EMPTY_N));

  // submodule mem_memory
  BRAM2 #(.PIPELINED(1'd0),
	  .ADDR_WIDTH(32'd12),
	  .DATA_WIDTH(32'd64),
	  .MEMSIZE(13'd4096)) mem_memory(.CLKA(CLK),
					 .CLKB(CLK),
					 .ADDRA(mem_memory$ADDRA),
					 .ADDRB(mem_memory$ADDRB),
					 .DIA(mem_memory$DIA),
					 .DIB(mem_memory$DIB),
					 .WEA(mem_memory$WEA),
					 .WEB(mem_memory$WEB),
					 .ENA(mem_memory$ENA),
					 .ENB(mem_memory$ENB),
					 .DOA(),
					 .DOB(mem_memory$DOB));

  // rule RL_initialLoad
  assign WILL_FIRE_RL_initialLoad =
	     NOT_mem_rRdPtr_read__7_PLUS_2048_76_EQ_mem_rWr_ETC___d178 &&
	     inQ$EMPTY_N &&
	     cx2_86_ULT_width_87___d188 ;

  // rule RL__activate1
  assign WILL_FIRE_RL__activate1 =
	     NOT_mem_rRdPtr_read__7_PLUS_2048_76_EQ_mem_rWr_ETC___d178 &&
	     p0_rv[1] &&
	     !p1_rv$port1__read[1] &&
	     !cx2_86_ULT_width_87___d188 ;

  // inputs to muxes for submodule ports
  assign MUX_mem_wDataIn$wset_1__VAL_2 = { 16'd0, _unnamed__64[63:16] } ;

  // inlined wires
  assign mem_pwDequeue$whas =
	     NOT_mem_rRdPtr_read__7_EQ_mem_rWrPtr_read_25_2_ETC___d234 &&
	     !cx2_86_ULT_width_87___d188 ;
  assign mem_pwEnqueue$whas =
	     WILL_FIRE_RL_initialLoad || WILL_FIRE_RL__activate1 ;
  assign p0_rv$port1__read = WILL_FIRE_RL__activate1 ? 2'd0 : p0_rv ;
  assign p0_rv$EN_port1__write =
	     NOT_mem_rRdPtr_read__7_EQ_mem_rWrPtr_read_25_2_ETC___d234 &&
	     !cx2_86_ULT_width_87___d188 ;
  assign p0_rv$port2__read =
	     p0_rv$EN_port1__write ? 2'd3 : p0_rv$port1__read ;
  assign p1_rv$EN_port0__write = p1_rv[1] && !p2_rv$port1__read[1] ;
  assign p1_rv$port1__read = p1_rv$EN_port0__write ? 2'd0 : p1_rv ;
  assign p1_rv$port2__read =
	     WILL_FIRE_RL__activate1 ? 2'd3 : p1_rv$port1__read ;
  assign p2_rv$EN_port0__write = p2_rv[1] && !p3_rv$port1__read[1] ;
  assign p2_rv$port1__read = p2_rv$EN_port0__write ? 2'd0 : p2_rv ;
  assign p2_rv$EN_port1__write = p1_rv[1] && !p2_rv$port1__read[1] ;
  assign p2_rv$port2__read =
	     p2_rv$EN_port1__write ? 2'd3 : p2_rv$port1__read ;
  assign p3_rv$EN_port0__write = p3_rv[1] && !p4_rv$port1__read[1] ;
  assign p3_rv$port1__read = p3_rv$EN_port0__write ? 2'd0 : p3_rv ;
  assign p3_rv$EN_port1__write = p2_rv[1] && !p3_rv$port1__read[1] ;
  assign p3_rv$port2__read =
	     p3_rv$EN_port1__write ? 2'd3 : p3_rv$port1__read ;
  assign p4_rv$EN_port0__write = p4_rv[1] && !p5_rv$port1__read[1] ;
  assign p4_rv$port1__read = p4_rv$EN_port0__write ? 2'd0 : p4_rv ;
  assign p4_rv$EN_port1__write = p3_rv[1] && !p4_rv$port1__read[1] ;
  assign p4_rv$port2__read =
	     p4_rv$EN_port1__write ? 2'd3 : p4_rv$port1__read ;
  assign p5_rv$EN_port0__write = p5_rv[1] && !p6_rv$port1__read[1] ;
  assign p5_rv$port1__read = p5_rv$EN_port0__write ? 2'd0 : p5_rv ;
  assign p5_rv$EN_port1__write = p4_rv[1] && !p5_rv$port1__read[1] ;
  assign p5_rv$port2__read =
	     p5_rv$EN_port1__write ? 2'd3 : p5_rv$port1__read ;
  assign p6_rv$EN_port0__write = p6_rv[1] && !p7_rv$port1__read[1] ;
  assign p6_rv$port1__read = p6_rv$EN_port0__write ? 2'd0 : p6_rv ;
  assign p6_rv$EN_port1__write = p5_rv[1] && !p6_rv$port1__read[1] ;
  assign p6_rv$port2__read =
	     p6_rv$EN_port1__write ? 2'd3 : p6_rv$port1__read ;
  assign p7_rv$port1__read = EN_get ? 2'd0 : p7_rv ;
  assign p7_rv$EN_port1__write =
	     p6_rv[1] && !p7_rv$port1__read[1] &&
	     cx >= { 8'd0, kernel - 4'd1 } ;
  assign p7_rv$port2__read =
	     p7_rv$EN_port1__write ? 2'd3 : p7_rv$port1__read ;

  // register _unnamed_
  assign _unnamed_$D_IN =
	     IF_mem_wDataOut_whas__28_THEN_mem_wDataOut_wge_ETC___d239[7:0] ;
  assign _unnamed_$EN = mem_pwDequeue$whas ;

  // register _unnamed__0_1
  assign _unnamed__0_1$D_IN = { _unnamed_, _unnamed__1 } ;
  assign _unnamed__0_1$EN = 1'd1 ;

  // register _unnamed__0_2
  assign _unnamed__0_2$D_IN = x__h11258 | x2__h10998 ;
  assign _unnamed__0_2$EN = 1'd1 ;

  // register _unnamed__0_3
  assign _unnamed__0_3$D_IN = x__h11575 | x2__h11315 ;
  assign _unnamed__0_3$EN = 1'd1 ;

  // register _unnamed__0_4
  assign _unnamed__0_4$D_IN = x__h11892 | x2__h11632 ;
  assign _unnamed__0_4$EN = 1'd1 ;

  // register _unnamed__0_5
  assign _unnamed__0_5$D_IN = x__h12209 | x2__h11949 ;
  assign _unnamed__0_5$EN = 1'd1 ;

  // register _unnamed__0_6
  assign _unnamed__0_6$D_IN = { 8'd0, _unnamed__0_5 } ;
  assign _unnamed__0_6$EN = 1'd1 ;

  // register _unnamed__1
  assign _unnamed__1$D_IN =
	     IF_mem_wDataOut_whas__28_THEN_mem_wDataOut_wge_ETC___d239[15:8] ;
  assign _unnamed__1$EN = mem_pwDequeue$whas ;

  // register _unnamed__10
  assign _unnamed__10$D_IN = { _unnamed__10[47:0], _unnamed__0_6[23:16] } ;
  assign _unnamed__10$EN = p6_rv[1] && !p7_rv$port1__read[1] ;

  // register _unnamed__11
  assign _unnamed__11$D_IN = { _unnamed__11[47:0], _unnamed__0_6[31:24] } ;
  assign _unnamed__11$EN = p6_rv[1] && !p7_rv$port1__read[1] ;

  // register _unnamed__12
  assign _unnamed__12$D_IN = { _unnamed__12[47:0], _unnamed__0_6[39:32] } ;
  assign _unnamed__12$EN = p6_rv[1] && !p7_rv$port1__read[1] ;

  // register _unnamed__13
  assign _unnamed__13$D_IN = { _unnamed__13[47:0], _unnamed__0_6[47:40] } ;
  assign _unnamed__13$EN = p6_rv[1] && !p7_rv$port1__read[1] ;

  // register _unnamed__14
  assign _unnamed__14$D_IN = { _unnamed__14[47:0], _unnamed__0_6[55:48] } ;
  assign _unnamed__14$EN = p6_rv[1] && !p7_rv$port1__read[1] ;

  // register _unnamed__15
  assign _unnamed__15$D_IN = { _unnamed__15[47:0], _unnamed__1_6[7:0] } ;
  assign _unnamed__15$EN = p6_rv[1] && !p7_rv$port1__read[1] ;

  // register _unnamed__16
  assign _unnamed__16$D_IN = { _unnamed__16[47:0], _unnamed__1_6[15:8] } ;
  assign _unnamed__16$EN = p6_rv[1] && !p7_rv$port1__read[1] ;

  // register _unnamed__17
  assign _unnamed__17$D_IN = { _unnamed__17[47:0], _unnamed__1_6[23:16] } ;
  assign _unnamed__17$EN = p6_rv[1] && !p7_rv$port1__read[1] ;

  // register _unnamed__18
  assign _unnamed__18$D_IN = { _unnamed__18[47:0], _unnamed__1_6[31:24] } ;
  assign _unnamed__18$EN = p6_rv[1] && !p7_rv$port1__read[1] ;

  // register _unnamed__19
  assign _unnamed__19$D_IN = { _unnamed__19[47:0], _unnamed__1_6[39:32] } ;
  assign _unnamed__19$EN = p6_rv[1] && !p7_rv$port1__read[1] ;

  // register _unnamed__1_1
  assign _unnamed__1_1$D_IN = { _unnamed__1, _unnamed__2 } ;
  assign _unnamed__1_1$EN = 1'd1 ;

  // register _unnamed__1_2
  assign _unnamed__1_2$D_IN = x__h12646 | x2__h12617 ;
  assign _unnamed__1_2$EN = 1'd1 ;

  // register _unnamed__1_3
  assign _unnamed__1_3$D_IN = x__h12731 | x2__h12702 ;
  assign _unnamed__1_3$EN = 1'd1 ;

  // register _unnamed__1_4
  assign _unnamed__1_4$D_IN = x__h12816 | x2__h12787 ;
  assign _unnamed__1_4$EN = 1'd1 ;

  // register _unnamed__1_5
  assign _unnamed__1_5$D_IN = x__h12902 | x2__h12872 ;
  assign _unnamed__1_5$EN = 1'd1 ;

  // register _unnamed__1_6
  assign _unnamed__1_6$D_IN = { 8'd0, _unnamed__1_5 } ;
  assign _unnamed__1_6$EN = 1'd1 ;

  // register _unnamed__2
  assign _unnamed__2$D_IN =
	     IF_mem_wDataOut_whas__28_THEN_mem_wDataOut_wge_ETC___d239[23:16] ;
  assign _unnamed__2$EN = mem_pwDequeue$whas ;

  // register _unnamed__20
  assign _unnamed__20$D_IN = { _unnamed__20[47:0], _unnamed__1_6[47:40] } ;
  assign _unnamed__20$EN = p6_rv[1] && !p7_rv$port1__read[1] ;

  // register _unnamed__21
  assign _unnamed__21$D_IN = { _unnamed__21[47:0], _unnamed__1_6[55:48] } ;
  assign _unnamed__21$EN = p6_rv[1] && !p7_rv$port1__read[1] ;

  // register _unnamed__22
  assign _unnamed__22$D_IN = { _unnamed__22[47:0], _unnamed__2_6[7:0] } ;
  assign _unnamed__22$EN = p6_rv[1] && !p7_rv$port1__read[1] ;

  // register _unnamed__23
  assign _unnamed__23$D_IN = { _unnamed__23[47:0], _unnamed__2_6[15:8] } ;
  assign _unnamed__23$EN = p6_rv[1] && !p7_rv$port1__read[1] ;

  // register _unnamed__24
  assign _unnamed__24$D_IN = { _unnamed__24[47:0], _unnamed__2_6[23:16] } ;
  assign _unnamed__24$EN = p6_rv[1] && !p7_rv$port1__read[1] ;

  // register _unnamed__25
  assign _unnamed__25$D_IN = { _unnamed__25[47:0], _unnamed__2_6[31:24] } ;
  assign _unnamed__25$EN = p6_rv[1] && !p7_rv$port1__read[1] ;

  // register _unnamed__26
  assign _unnamed__26$D_IN = { _unnamed__26[47:0], _unnamed__2_6[39:32] } ;
  assign _unnamed__26$EN = p6_rv[1] && !p7_rv$port1__read[1] ;

  // register _unnamed__27
  assign _unnamed__27$D_IN = { _unnamed__27[47:0], _unnamed__2_6[47:40] } ;
  assign _unnamed__27$EN = p6_rv[1] && !p7_rv$port1__read[1] ;

  // register _unnamed__28
  assign _unnamed__28$D_IN = { _unnamed__28[47:0], _unnamed__2_6[55:48] } ;
  assign _unnamed__28$EN = p6_rv[1] && !p7_rv$port1__read[1] ;

  // register _unnamed__29
  assign _unnamed__29$D_IN = { _unnamed__29[47:0], _unnamed__3_6[7:0] } ;
  assign _unnamed__29$EN = p6_rv[1] && !p7_rv$port1__read[1] ;

  // register _unnamed__2_1
  assign _unnamed__2_1$D_IN = { _unnamed__2, _unnamed__3 } ;
  assign _unnamed__2_1$EN = 1'd1 ;

  // register _unnamed__2_2
  assign _unnamed__2_2$D_IN = x__h13144 | x2__h13115 ;
  assign _unnamed__2_2$EN = 1'd1 ;

  // register _unnamed__2_3
  assign _unnamed__2_3$D_IN = x__h13229 | x2__h13200 ;
  assign _unnamed__2_3$EN = 1'd1 ;

  // register _unnamed__2_4
  assign _unnamed__2_4$D_IN = x__h13314 | x2__h13285 ;
  assign _unnamed__2_4$EN = 1'd1 ;

  // register _unnamed__2_5
  assign _unnamed__2_5$D_IN = x__h13400 | x2__h13370 ;
  assign _unnamed__2_5$EN = 1'd1 ;

  // register _unnamed__2_6
  assign _unnamed__2_6$D_IN = { 8'd0, _unnamed__2_5 } ;
  assign _unnamed__2_6$EN = 1'd1 ;

  // register _unnamed__3
  assign _unnamed__3$D_IN =
	     IF_mem_wDataOut_whas__28_THEN_mem_wDataOut_wge_ETC___d239[31:24] ;
  assign _unnamed__3$EN = mem_pwDequeue$whas ;

  // register _unnamed__30
  assign _unnamed__30$D_IN = { _unnamed__30[47:0], _unnamed__3_6[15:8] } ;
  assign _unnamed__30$EN = p6_rv[1] && !p7_rv$port1__read[1] ;

  // register _unnamed__31
  assign _unnamed__31$D_IN = { _unnamed__31[47:0], _unnamed__3_6[23:16] } ;
  assign _unnamed__31$EN = p6_rv[1] && !p7_rv$port1__read[1] ;

  // register _unnamed__32
  assign _unnamed__32$D_IN = { _unnamed__32[47:0], _unnamed__3_6[31:24] } ;
  assign _unnamed__32$EN = p6_rv[1] && !p7_rv$port1__read[1] ;

  // register _unnamed__33
  assign _unnamed__33$D_IN = { _unnamed__33[47:0], _unnamed__3_6[39:32] } ;
  assign _unnamed__33$EN = p6_rv[1] && !p7_rv$port1__read[1] ;

  // register _unnamed__34
  assign _unnamed__34$D_IN = { _unnamed__34[47:0], _unnamed__3_6[47:40] } ;
  assign _unnamed__34$EN = p6_rv[1] && !p7_rv$port1__read[1] ;

  // register _unnamed__35
  assign _unnamed__35$D_IN = { _unnamed__35[47:0], _unnamed__3_6[55:48] } ;
  assign _unnamed__35$EN = p6_rv[1] && !p7_rv$port1__read[1] ;

  // register _unnamed__36
  assign _unnamed__36$D_IN = { _unnamed__36[47:0], _unnamed__4_6[7:0] } ;
  assign _unnamed__36$EN = p6_rv[1] && !p7_rv$port1__read[1] ;

  // register _unnamed__37
  assign _unnamed__37$D_IN = { _unnamed__37[47:0], _unnamed__4_6[15:8] } ;
  assign _unnamed__37$EN = p6_rv[1] && !p7_rv$port1__read[1] ;

  // register _unnamed__38
  assign _unnamed__38$D_IN = { _unnamed__38[47:0], _unnamed__4_6[23:16] } ;
  assign _unnamed__38$EN = p6_rv[1] && !p7_rv$port1__read[1] ;

  // register _unnamed__39
  assign _unnamed__39$D_IN = { _unnamed__39[47:0], _unnamed__4_6[31:24] } ;
  assign _unnamed__39$EN = p6_rv[1] && !p7_rv$port1__read[1] ;

  // register _unnamed__3_1
  assign _unnamed__3_1$D_IN = { _unnamed__3, _unnamed__4 } ;
  assign _unnamed__3_1$EN = 1'd1 ;

  // register _unnamed__3_2
  assign _unnamed__3_2$D_IN = x__h13642 | x2__h13613 ;
  assign _unnamed__3_2$EN = 1'd1 ;

  // register _unnamed__3_3
  assign _unnamed__3_3$D_IN = x__h13727 | x2__h13698 ;
  assign _unnamed__3_3$EN = 1'd1 ;

  // register _unnamed__3_4
  assign _unnamed__3_4$D_IN = x__h13812 | x2__h13783 ;
  assign _unnamed__3_4$EN = 1'd1 ;

  // register _unnamed__3_5
  assign _unnamed__3_5$D_IN = x__h13898 | x2__h13868 ;
  assign _unnamed__3_5$EN = 1'd1 ;

  // register _unnamed__3_6
  assign _unnamed__3_6$D_IN = { 8'd0, _unnamed__3_5 } ;
  assign _unnamed__3_6$EN = 1'd1 ;

  // register _unnamed__4
  assign _unnamed__4$D_IN =
	     IF_mem_wDataOut_whas__28_THEN_mem_wDataOut_wge_ETC___d239[39:32] ;
  assign _unnamed__4$EN = mem_pwDequeue$whas ;

  // register _unnamed__40
  assign _unnamed__40$D_IN = { _unnamed__40[47:0], _unnamed__4_6[39:32] } ;
  assign _unnamed__40$EN = p6_rv[1] && !p7_rv$port1__read[1] ;

  // register _unnamed__41
  assign _unnamed__41$D_IN = { _unnamed__41[47:0], _unnamed__4_6[47:40] } ;
  assign _unnamed__41$EN = p6_rv[1] && !p7_rv$port1__read[1] ;

  // register _unnamed__42
  assign _unnamed__42$D_IN = { _unnamed__42[47:0], _unnamed__4_6[55:48] } ;
  assign _unnamed__42$EN = p6_rv[1] && !p7_rv$port1__read[1] ;

  // register _unnamed__43
  assign _unnamed__43$D_IN = { _unnamed__43[47:0], _unnamed__5_6[7:0] } ;
  assign _unnamed__43$EN = p6_rv[1] && !p7_rv$port1__read[1] ;

  // register _unnamed__44
  assign _unnamed__44$D_IN = { _unnamed__44[47:0], _unnamed__5_6[15:8] } ;
  assign _unnamed__44$EN = p6_rv[1] && !p7_rv$port1__read[1] ;

  // register _unnamed__45
  assign _unnamed__45$D_IN = { _unnamed__45[47:0], _unnamed__5_6[23:16] } ;
  assign _unnamed__45$EN = p6_rv[1] && !p7_rv$port1__read[1] ;

  // register _unnamed__46
  assign _unnamed__46$D_IN = { _unnamed__46[47:0], _unnamed__5_6[31:24] } ;
  assign _unnamed__46$EN = p6_rv[1] && !p7_rv$port1__read[1] ;

  // register _unnamed__47
  assign _unnamed__47$D_IN = { _unnamed__47[47:0], _unnamed__5_6[39:32] } ;
  assign _unnamed__47$EN = p6_rv[1] && !p7_rv$port1__read[1] ;

  // register _unnamed__48
  assign _unnamed__48$D_IN = { _unnamed__48[47:0], _unnamed__5_6[47:40] } ;
  assign _unnamed__48$EN = p6_rv[1] && !p7_rv$port1__read[1] ;

  // register _unnamed__49
  assign _unnamed__49$D_IN = { _unnamed__49[47:0], _unnamed__5_6[55:48] } ;
  assign _unnamed__49$EN = p6_rv[1] && !p7_rv$port1__read[1] ;

  // register _unnamed__4_1
  assign _unnamed__4_1$D_IN = { _unnamed__4, _unnamed__5 } ;
  assign _unnamed__4_1$EN = 1'd1 ;

  // register _unnamed__4_2
  assign _unnamed__4_2$D_IN = x__h14140 | x2__h14111 ;
  assign _unnamed__4_2$EN = 1'd1 ;

  // register _unnamed__4_3
  assign _unnamed__4_3$D_IN = x__h14225 | x2__h14196 ;
  assign _unnamed__4_3$EN = 1'd1 ;

  // register _unnamed__4_4
  assign _unnamed__4_4$D_IN = x__h14310 | x2__h14281 ;
  assign _unnamed__4_4$EN = 1'd1 ;

  // register _unnamed__4_5
  assign _unnamed__4_5$D_IN = x__h14396 | x2__h14366 ;
  assign _unnamed__4_5$EN = 1'd1 ;

  // register _unnamed__4_6
  assign _unnamed__4_6$D_IN = { 8'd0, _unnamed__4_5 } ;
  assign _unnamed__4_6$EN = 1'd1 ;

  // register _unnamed__5
  assign _unnamed__5$D_IN =
	     IF_mem_wDataOut_whas__28_THEN_mem_wDataOut_wge_ETC___d239[47:40] ;
  assign _unnamed__5$EN = mem_pwDequeue$whas ;

  // register _unnamed__50
  assign _unnamed__50$D_IN = { _unnamed__50[47:0], _unnamed__6_6[7:0] } ;
  assign _unnamed__50$EN = p6_rv[1] && !p7_rv$port1__read[1] ;

  // register _unnamed__51
  assign _unnamed__51$D_IN = { _unnamed__51[47:0], _unnamed__6_6[15:8] } ;
  assign _unnamed__51$EN = p6_rv[1] && !p7_rv$port1__read[1] ;

  // register _unnamed__52
  assign _unnamed__52$D_IN = { _unnamed__52[47:0], _unnamed__6_6[23:16] } ;
  assign _unnamed__52$EN = p6_rv[1] && !p7_rv$port1__read[1] ;

  // register _unnamed__53
  assign _unnamed__53$D_IN = { _unnamed__53[47:0], _unnamed__6_6[31:24] } ;
  assign _unnamed__53$EN = p6_rv[1] && !p7_rv$port1__read[1] ;

  // register _unnamed__54
  assign _unnamed__54$D_IN = { _unnamed__54[47:0], _unnamed__6_6[39:32] } ;
  assign _unnamed__54$EN = p6_rv[1] && !p7_rv$port1__read[1] ;

  // register _unnamed__55
  assign _unnamed__55$D_IN = { _unnamed__55[47:0], _unnamed__6_6[47:40] } ;
  assign _unnamed__55$EN = p6_rv[1] && !p7_rv$port1__read[1] ;

  // register _unnamed__56
  assign _unnamed__56$D_IN = { _unnamed__56[47:0], _unnamed__6_6[55:48] } ;
  assign _unnamed__56$EN = p6_rv[1] && !p7_rv$port1__read[1] ;

  // register _unnamed__57
  assign _unnamed__57$D_IN = { _unnamed__57[47:0], _unnamed__7_6[7:0] } ;
  assign _unnamed__57$EN = p6_rv[1] && !p7_rv$port1__read[1] ;

  // register _unnamed__58
  assign _unnamed__58$D_IN = { _unnamed__58[47:0], _unnamed__7_6[15:8] } ;
  assign _unnamed__58$EN = p6_rv[1] && !p7_rv$port1__read[1] ;

  // register _unnamed__59
  assign _unnamed__59$D_IN = { _unnamed__59[47:0], _unnamed__7_6[23:16] } ;
  assign _unnamed__59$EN = p6_rv[1] && !p7_rv$port1__read[1] ;

  // register _unnamed__5_1
  assign _unnamed__5_1$D_IN = { _unnamed__5, _unnamed__6 } ;
  assign _unnamed__5_1$EN = 1'd1 ;

  // register _unnamed__5_2
  assign _unnamed__5_2$D_IN = x__h14638 | x2__h14609 ;
  assign _unnamed__5_2$EN = 1'd1 ;

  // register _unnamed__5_3
  assign _unnamed__5_3$D_IN = x__h14723 | x2__h14694 ;
  assign _unnamed__5_3$EN = 1'd1 ;

  // register _unnamed__5_4
  assign _unnamed__5_4$D_IN = x__h14808 | x2__h14779 ;
  assign _unnamed__5_4$EN = 1'd1 ;

  // register _unnamed__5_5
  assign _unnamed__5_5$D_IN = x__h14894 | x2__h14864 ;
  assign _unnamed__5_5$EN = 1'd1 ;

  // register _unnamed__5_6
  assign _unnamed__5_6$D_IN = { 8'd0, _unnamed__5_5 } ;
  assign _unnamed__5_6$EN = 1'd1 ;

  // register _unnamed__6
  assign _unnamed__6$D_IN =
	     IF_mem_wDataOut_whas__28_THEN_mem_wDataOut_wge_ETC___d239[55:48] ;
  assign _unnamed__6$EN = mem_pwDequeue$whas ;

  // register _unnamed__60
  assign _unnamed__60$D_IN = { _unnamed__60[47:0], _unnamed__7_6[31:24] } ;
  assign _unnamed__60$EN = p6_rv[1] && !p7_rv$port1__read[1] ;

  // register _unnamed__61
  assign _unnamed__61$D_IN = { _unnamed__61[47:0], _unnamed__7_6[39:32] } ;
  assign _unnamed__61$EN = p6_rv[1] && !p7_rv$port1__read[1] ;

  // register _unnamed__62
  assign _unnamed__62$D_IN = { _unnamed__62[47:0], _unnamed__7_6[47:40] } ;
  assign _unnamed__62$EN = p6_rv[1] && !p7_rv$port1__read[1] ;

  // register _unnamed__63
  assign _unnamed__63$D_IN = { _unnamed__63[47:0], _unnamed__7_6[55:48] } ;
  assign _unnamed__63$EN = p6_rv[1] && !p7_rv$port1__read[1] ;

  // register _unnamed__64
  assign _unnamed__64$D_IN = 64'h0 ;
  assign _unnamed__64$EN = 1'b0 ;

  // register _unnamed__6_1
  assign _unnamed__6_1$D_IN = { _unnamed__6, _unnamed__7 } ;
  assign _unnamed__6_1$EN = 1'd1 ;

  // register _unnamed__6_2
  assign _unnamed__6_2$D_IN = x__h15136 | x2__h15107 ;
  assign _unnamed__6_2$EN = 1'd1 ;

  // register _unnamed__6_3
  assign _unnamed__6_3$D_IN = x__h15221 | x2__h15192 ;
  assign _unnamed__6_3$EN = 1'd1 ;

  // register _unnamed__6_4
  assign _unnamed__6_4$D_IN = x__h15306 | x2__h15277 ;
  assign _unnamed__6_4$EN = 1'd1 ;

  // register _unnamed__6_5
  assign _unnamed__6_5$D_IN = x__h15392 | x2__h15362 ;
  assign _unnamed__6_5$EN = 1'd1 ;

  // register _unnamed__6_6
  assign _unnamed__6_6$D_IN = { 8'd0, _unnamed__6_5 } ;
  assign _unnamed__6_6$EN = 1'd1 ;

  // register _unnamed__7
  assign _unnamed__7$D_IN =
	     IF_mem_wDataOut_whas__28_THEN_mem_wDataOut_wge_ETC___d239[63:56] ;
  assign _unnamed__7$EN = mem_pwDequeue$whas ;

  // register _unnamed__7_1
  assign _unnamed__7_1$D_IN = 16'h0 ;
  assign _unnamed__7_1$EN = 1'b0 ;

  // register _unnamed__7_2
  assign _unnamed__7_2$D_IN = 24'h0 ;
  assign _unnamed__7_2$EN = 1'b0 ;

  // register _unnamed__7_3
  assign _unnamed__7_3$D_IN = 32'h0 ;
  assign _unnamed__7_3$EN = 1'b0 ;

  // register _unnamed__7_4
  assign _unnamed__7_4$D_IN = 40'h0 ;
  assign _unnamed__7_4$EN = 1'b0 ;

  // register _unnamed__7_5
  assign _unnamed__7_5$D_IN = 48'h0 ;
  assign _unnamed__7_5$EN = 1'b0 ;

  // register _unnamed__7_6
  assign _unnamed__7_6$D_IN = 56'h0 ;
  assign _unnamed__7_6$EN = 1'b0 ;

  // register _unnamed__8
  assign _unnamed__8$D_IN = { _unnamed__8[47:0], _unnamed__0_6[7:0] } ;
  assign _unnamed__8$EN = p6_rv[1] && !p7_rv$port1__read[1] ;

  // register _unnamed__9
  assign _unnamed__9$D_IN = { _unnamed__9[47:0], _unnamed__0_6[15:8] } ;
  assign _unnamed__9$EN = p6_rv[1] && !p7_rv$port1__read[1] ;

  // register cx
  assign cx$D_IN = (cx == width - 12'd1) ? 12'd0 : cx + 12'd1 ;
  assign cx$EN = p6_rv[1] && !p7_rv$port1__read[1] ;

  // register cx2
  assign cx2$D_IN = cx2 + 12'd1 ;
  assign cx2$EN = WILL_FIRE_RL_initialLoad ;

  // register kernel
  assign kernel$D_IN = configure_a ;
  assign kernel$EN = EN_configure ;

  // register mem_rCache
  assign mem_rCache$D_IN = { 1'd1, mem_rWrPtr, x3__h10014 } ;
  assign mem_rCache$EN = mem_pwEnqueue$whas ;

  // register mem_rRdPtr
  assign mem_rRdPtr$D_IN = x__h10186 ;
  assign mem_rRdPtr$EN = mem_pwDequeue$whas ;

  // register mem_rWrPtr
  assign mem_rWrPtr$D_IN = x__h10097 ;
  assign mem_rWrPtr$EN = mem_pwEnqueue$whas ;

  // register mx
  assign mx$D_IN = configure_m ;
  assign mx$EN = EN_configure ;

  // register p0_rv
  assign p0_rv$D_IN = p0_rv$port2__read ;
  assign p0_rv$EN = 1'b1 ;

  // register p1_rv
  assign p1_rv$D_IN = p1_rv$port2__read ;
  assign p1_rv$EN = 1'b1 ;

  // register p2_rv
  assign p2_rv$D_IN = p2_rv$port2__read ;
  assign p2_rv$EN = 1'b1 ;

  // register p3_rv
  assign p3_rv$D_IN = p3_rv$port2__read ;
  assign p3_rv$EN = 1'b1 ;

  // register p4_rv
  assign p4_rv$D_IN = p4_rv$port2__read ;
  assign p4_rv$EN = 1'b1 ;

  // register p5_rv
  assign p5_rv$D_IN = p5_rv$port2__read ;
  assign p5_rv$EN = 1'b1 ;

  // register p6_rv
  assign p6_rv$D_IN = p6_rv$port2__read ;
  assign p6_rv$EN = 1'b1 ;

  // register p7_rv
  assign p7_rv$D_IN = p7_rv$port2__read ;
  assign p7_rv$EN = 1'b1 ;

  // register width
  assign width$D_IN = configure_wx ;
  assign width$EN = EN_configure ;

  // submodule inQ
  assign inQ$D_IN = put_datas ;
  assign inQ$ENQ = EN_put ;
  assign inQ$DEQ =
	     WILL_FIRE_RL_initialLoad ||
	     NOT_mem_rRdPtr_read__7_EQ_mem_rWrPtr_read_25_2_ETC___d234 &&
	     !cx2_86_ULT_width_87___d188 ;
  assign inQ$CLR = 1'b0 ;

  // submodule mem_memory
  assign mem_memory$ADDRA = mem_rWrPtr[11:0] ;
  assign mem_memory$ADDRB =
	     mem_pwDequeue$whas ? x__h10186[11:0] : mem_rRdPtr[11:0] ;
  assign mem_memory$DIA = x3__h10014 ;
  assign mem_memory$DIB = 64'hAAAAAAAAAAAAAAAA /* unspecified value */  ;
  assign mem_memory$WEA = mem_pwEnqueue$whas ;
  assign mem_memory$WEB = 1'd0 ;
  assign mem_memory$ENA = 1'b1 ;
  assign mem_memory$ENB = 1'b1 ;

  // remaining internal signals
  assign IF_mem_wDataOut_whas__28_THEN_mem_wDataOut_wge_ETC___d239 =
	     d1__h16638 | inQ$D_OUT ;
  assign NOT_mem_rRdPtr_read__7_EQ_mem_rWrPtr_read_25_2_ETC___d234 =
	     mem_rRdPtr != mem_rWrPtr && inQ$EMPTY_N &&
	     !p0_rv$port1__read[1] ;
  assign NOT_mem_rRdPtr_read__7_PLUS_2048_76_EQ_mem_rWr_ETC___d178 =
	     mem_rRdPtr + 13'd2048 != mem_rWrPtr ;
  assign cx2_86_ULT_width_87___d188 = cx2 < width ;
  assign d1__h16638 =
	     (mem_rCache[77] && mem_rCache[76:64] == mem_rRdPtr) ?
	       mem_rCache[63:0] :
	       mem_memory$DOB ;
  assign x2__h10998 = { 8'd0, _unnamed__1_1 } ;
  assign x2__h11315 = { 8'd0, _unnamed__1_2 } ;
  assign x2__h11632 = { 8'd0, _unnamed__1_3 } ;
  assign x2__h11949 = { 8'd0, _unnamed__1_4 } ;
  assign x2__h12617 = { 8'd0, _unnamed__2_1 } ;
  assign x2__h12702 = { 8'd0, _unnamed__2_2 } ;
  assign x2__h12787 = { 8'd0, _unnamed__2_3 } ;
  assign x2__h12872 = { 8'd0, _unnamed__2_4 } ;
  assign x2__h13115 = { 8'd0, _unnamed__3_1 } ;
  assign x2__h13200 = { 8'd0, _unnamed__3_2 } ;
  assign x2__h13285 = { 8'd0, _unnamed__3_3 } ;
  assign x2__h13370 = { 8'd0, _unnamed__3_4 } ;
  assign x2__h13613 = { 8'd0, _unnamed__4_1 } ;
  assign x2__h13698 = { 8'd0, _unnamed__4_2 } ;
  assign x2__h13783 = { 8'd0, _unnamed__4_3 } ;
  assign x2__h13868 = { 8'd0, _unnamed__4_4 } ;
  assign x2__h14111 = { 8'd0, _unnamed__5_1 } ;
  assign x2__h14196 = { 8'd0, _unnamed__5_2 } ;
  assign x2__h14281 = { 8'd0, _unnamed__5_3 } ;
  assign x2__h14366 = { 8'd0, _unnamed__5_4 } ;
  assign x2__h14609 = { 8'd0, _unnamed__6_1 } ;
  assign x2__h14694 = { 8'd0, _unnamed__6_2 } ;
  assign x2__h14779 = { 8'd0, _unnamed__6_3 } ;
  assign x2__h14864 = { 8'd0, _unnamed__6_4 } ;
  assign x2__h15107 = { 8'd0, _unnamed__7_1 } ;
  assign x2__h15192 = { 8'd0, _unnamed__7_2 } ;
  assign x2__h15277 = { 8'd0, _unnamed__7_3 } ;
  assign x2__h15362 = { 8'd0, _unnamed__7_4 } ;
  assign x3__h10014 = mem_pwEnqueue$whas ? x_wget__h9796 : 64'd0 ;
  assign x__h10097 = mem_rWrPtr + 13'd1 ;
  assign x__h10186 = mem_rRdPtr + 13'd1 ;
  assign x__h11258 = { _unnamed__0_1, 8'd0 } ;
  assign x__h11575 = { _unnamed__0_2, 8'd0 } ;
  assign x__h11892 = { _unnamed__0_3, 8'd0 } ;
  assign x__h12209 = { _unnamed__0_4, 8'd0 } ;
  assign x__h12646 = { _unnamed__1_1, 8'd0 } ;
  assign x__h12731 = { _unnamed__1_2, 8'd0 } ;
  assign x__h12816 = { _unnamed__1_3, 8'd0 } ;
  assign x__h12902 = { _unnamed__1_4, 8'd0 } ;
  assign x__h13144 = { _unnamed__2_1, 8'd0 } ;
  assign x__h13229 = { _unnamed__2_2, 8'd0 } ;
  assign x__h13314 = { _unnamed__2_3, 8'd0 } ;
  assign x__h13400 = { _unnamed__2_4, 8'd0 } ;
  assign x__h13642 = { _unnamed__3_1, 8'd0 } ;
  assign x__h13727 = { _unnamed__3_2, 8'd0 } ;
  assign x__h13812 = { _unnamed__3_3, 8'd0 } ;
  assign x__h13898 = { _unnamed__3_4, 8'd0 } ;
  assign x__h14140 = { _unnamed__4_1, 8'd0 } ;
  assign x__h14225 = { _unnamed__4_2, 8'd0 } ;
  assign x__h14310 = { _unnamed__4_3, 8'd0 } ;
  assign x__h14396 = { _unnamed__4_4, 8'd0 } ;
  assign x__h14638 = { _unnamed__5_1, 8'd0 } ;
  assign x__h14723 = { _unnamed__5_2, 8'd0 } ;
  assign x__h14808 = { _unnamed__5_3, 8'd0 } ;
  assign x__h14894 = { _unnamed__5_4, 8'd0 } ;
  assign x__h15136 = { _unnamed__6_1, 8'd0 } ;
  assign x__h15221 = { _unnamed__6_2, 8'd0 } ;
  assign x__h15306 = { _unnamed__6_3, 8'd0 } ;
  assign x__h15392 = { _unnamed__6_4, 8'd0 } ;
  assign x_wget__h9796 =
	     WILL_FIRE_RL_initialLoad ?
	       inQ$D_OUT :
	       MUX_mem_wDataIn$wset_1__VAL_2 ;

  // handling of inlined registers

  always@(posedge CLK)
  begin
    if (RST_N == `BSV_RESET_VALUE)
      begin
        _unnamed_ <= `BSV_ASSIGNMENT_DELAY 8'd0;
	_unnamed__0_1 <= `BSV_ASSIGNMENT_DELAY 16'd0;
	_unnamed__0_2 <= `BSV_ASSIGNMENT_DELAY 24'd0;
	_unnamed__0_3 <= `BSV_ASSIGNMENT_DELAY 32'd0;
	_unnamed__0_4 <= `BSV_ASSIGNMENT_DELAY 40'd0;
	_unnamed__0_5 <= `BSV_ASSIGNMENT_DELAY 48'd0;
	_unnamed__0_6 <= `BSV_ASSIGNMENT_DELAY 56'd0;
	_unnamed__1 <= `BSV_ASSIGNMENT_DELAY 8'd0;
	_unnamed__10 <= `BSV_ASSIGNMENT_DELAY 56'd0;
	_unnamed__11 <= `BSV_ASSIGNMENT_DELAY 56'd0;
	_unnamed__12 <= `BSV_ASSIGNMENT_DELAY 56'd0;
	_unnamed__13 <= `BSV_ASSIGNMENT_DELAY 56'd0;
	_unnamed__14 <= `BSV_ASSIGNMENT_DELAY 56'd0;
	_unnamed__15 <= `BSV_ASSIGNMENT_DELAY 56'd0;
	_unnamed__16 <= `BSV_ASSIGNMENT_DELAY 56'd0;
	_unnamed__17 <= `BSV_ASSIGNMENT_DELAY 56'd0;
	_unnamed__18 <= `BSV_ASSIGNMENT_DELAY 56'd0;
	_unnamed__19 <= `BSV_ASSIGNMENT_DELAY 56'd0;
	_unnamed__1_1 <= `BSV_ASSIGNMENT_DELAY 16'd0;
	_unnamed__1_2 <= `BSV_ASSIGNMENT_DELAY 24'd0;
	_unnamed__1_3 <= `BSV_ASSIGNMENT_DELAY 32'd0;
	_unnamed__1_4 <= `BSV_ASSIGNMENT_DELAY 40'd0;
	_unnamed__1_5 <= `BSV_ASSIGNMENT_DELAY 48'd0;
	_unnamed__1_6 <= `BSV_ASSIGNMENT_DELAY 56'd0;
	_unnamed__2 <= `BSV_ASSIGNMENT_DELAY 8'd0;
	_unnamed__20 <= `BSV_ASSIGNMENT_DELAY 56'd0;
	_unnamed__21 <= `BSV_ASSIGNMENT_DELAY 56'd0;
	_unnamed__22 <= `BSV_ASSIGNMENT_DELAY 56'd0;
	_unnamed__23 <= `BSV_ASSIGNMENT_DELAY 56'd0;
	_unnamed__24 <= `BSV_ASSIGNMENT_DELAY 56'd0;
	_unnamed__25 <= `BSV_ASSIGNMENT_DELAY 56'd0;
	_unnamed__26 <= `BSV_ASSIGNMENT_DELAY 56'd0;
	_unnamed__27 <= `BSV_ASSIGNMENT_DELAY 56'd0;
	_unnamed__28 <= `BSV_ASSIGNMENT_DELAY 56'd0;
	_unnamed__29 <= `BSV_ASSIGNMENT_DELAY 56'd0;
	_unnamed__2_1 <= `BSV_ASSIGNMENT_DELAY 16'd0;
	_unnamed__2_2 <= `BSV_ASSIGNMENT_DELAY 24'd0;
	_unnamed__2_3 <= `BSV_ASSIGNMENT_DELAY 32'd0;
	_unnamed__2_4 <= `BSV_ASSIGNMENT_DELAY 40'd0;
	_unnamed__2_5 <= `BSV_ASSIGNMENT_DELAY 48'd0;
	_unnamed__2_6 <= `BSV_ASSIGNMENT_DELAY 56'd0;
	_unnamed__3 <= `BSV_ASSIGNMENT_DELAY 8'd0;
	_unnamed__30 <= `BSV_ASSIGNMENT_DELAY 56'd0;
	_unnamed__31 <= `BSV_ASSIGNMENT_DELAY 56'd0;
	_unnamed__32 <= `BSV_ASSIGNMENT_DELAY 56'd0;
	_unnamed__33 <= `BSV_ASSIGNMENT_DELAY 56'd0;
	_unnamed__34 <= `BSV_ASSIGNMENT_DELAY 56'd0;
	_unnamed__35 <= `BSV_ASSIGNMENT_DELAY 56'd0;
	_unnamed__36 <= `BSV_ASSIGNMENT_DELAY 56'd0;
	_unnamed__37 <= `BSV_ASSIGNMENT_DELAY 56'd0;
	_unnamed__38 <= `BSV_ASSIGNMENT_DELAY 56'd0;
	_unnamed__39 <= `BSV_ASSIGNMENT_DELAY 56'd0;
	_unnamed__3_1 <= `BSV_ASSIGNMENT_DELAY 16'd0;
	_unnamed__3_2 <= `BSV_ASSIGNMENT_DELAY 24'd0;
	_unnamed__3_3 <= `BSV_ASSIGNMENT_DELAY 32'd0;
	_unnamed__3_4 <= `BSV_ASSIGNMENT_DELAY 40'd0;
	_unnamed__3_5 <= `BSV_ASSIGNMENT_DELAY 48'd0;
	_unnamed__3_6 <= `BSV_ASSIGNMENT_DELAY 56'd0;
	_unnamed__4 <= `BSV_ASSIGNMENT_DELAY 8'd0;
	_unnamed__40 <= `BSV_ASSIGNMENT_DELAY 56'd0;
	_unnamed__41 <= `BSV_ASSIGNMENT_DELAY 56'd0;
	_unnamed__42 <= `BSV_ASSIGNMENT_DELAY 56'd0;
	_unnamed__43 <= `BSV_ASSIGNMENT_DELAY 56'd0;
	_unnamed__44 <= `BSV_ASSIGNMENT_DELAY 56'd0;
	_unnamed__45 <= `BSV_ASSIGNMENT_DELAY 56'd0;
	_unnamed__46 <= `BSV_ASSIGNMENT_DELAY 56'd0;
	_unnamed__47 <= `BSV_ASSIGNMENT_DELAY 56'd0;
	_unnamed__48 <= `BSV_ASSIGNMENT_DELAY 56'd0;
	_unnamed__49 <= `BSV_ASSIGNMENT_DELAY 56'd0;
	_unnamed__4_1 <= `BSV_ASSIGNMENT_DELAY 16'd0;
	_unnamed__4_2 <= `BSV_ASSIGNMENT_DELAY 24'd0;
	_unnamed__4_3 <= `BSV_ASSIGNMENT_DELAY 32'd0;
	_unnamed__4_4 <= `BSV_ASSIGNMENT_DELAY 40'd0;
	_unnamed__4_5 <= `BSV_ASSIGNMENT_DELAY 48'd0;
	_unnamed__4_6 <= `BSV_ASSIGNMENT_DELAY 56'd0;
	_unnamed__5 <= `BSV_ASSIGNMENT_DELAY 8'd0;
	_unnamed__50 <= `BSV_ASSIGNMENT_DELAY 56'd0;
	_unnamed__51 <= `BSV_ASSIGNMENT_DELAY 56'd0;
	_unnamed__52 <= `BSV_ASSIGNMENT_DELAY 56'd0;
	_unnamed__53 <= `BSV_ASSIGNMENT_DELAY 56'd0;
	_unnamed__54 <= `BSV_ASSIGNMENT_DELAY 56'd0;
	_unnamed__55 <= `BSV_ASSIGNMENT_DELAY 56'd0;
	_unnamed__56 <= `BSV_ASSIGNMENT_DELAY 56'd0;
	_unnamed__57 <= `BSV_ASSIGNMENT_DELAY 56'd0;
	_unnamed__58 <= `BSV_ASSIGNMENT_DELAY 56'd0;
	_unnamed__59 <= `BSV_ASSIGNMENT_DELAY 56'd0;
	_unnamed__5_1 <= `BSV_ASSIGNMENT_DELAY 16'd0;
	_unnamed__5_2 <= `BSV_ASSIGNMENT_DELAY 24'd0;
	_unnamed__5_3 <= `BSV_ASSIGNMENT_DELAY 32'd0;
	_unnamed__5_4 <= `BSV_ASSIGNMENT_DELAY 40'd0;
	_unnamed__5_5 <= `BSV_ASSIGNMENT_DELAY 48'd0;
	_unnamed__5_6 <= `BSV_ASSIGNMENT_DELAY 56'd0;
	_unnamed__6 <= `BSV_ASSIGNMENT_DELAY 8'd0;
	_unnamed__60 <= `BSV_ASSIGNMENT_DELAY 56'd0;
	_unnamed__61 <= `BSV_ASSIGNMENT_DELAY 56'd0;
	_unnamed__62 <= `BSV_ASSIGNMENT_DELAY 56'd0;
	_unnamed__63 <= `BSV_ASSIGNMENT_DELAY 56'd0;
	_unnamed__64 <= `BSV_ASSIGNMENT_DELAY 64'd0;
	_unnamed__6_1 <= `BSV_ASSIGNMENT_DELAY 16'd0;
	_unnamed__6_2 <= `BSV_ASSIGNMENT_DELAY 24'd0;
	_unnamed__6_3 <= `BSV_ASSIGNMENT_DELAY 32'd0;
	_unnamed__6_4 <= `BSV_ASSIGNMENT_DELAY 40'd0;
	_unnamed__6_5 <= `BSV_ASSIGNMENT_DELAY 48'd0;
	_unnamed__6_6 <= `BSV_ASSIGNMENT_DELAY 56'd0;
	_unnamed__7 <= `BSV_ASSIGNMENT_DELAY 8'd0;
	_unnamed__7_1 <= `BSV_ASSIGNMENT_DELAY 16'd0;
	_unnamed__7_2 <= `BSV_ASSIGNMENT_DELAY 24'd0;
	_unnamed__7_3 <= `BSV_ASSIGNMENT_DELAY 32'd0;
	_unnamed__7_4 <= `BSV_ASSIGNMENT_DELAY 40'd0;
	_unnamed__7_5 <= `BSV_ASSIGNMENT_DELAY 48'd0;
	_unnamed__7_6 <= `BSV_ASSIGNMENT_DELAY 56'd0;
	_unnamed__8 <= `BSV_ASSIGNMENT_DELAY 56'd0;
	_unnamed__9 <= `BSV_ASSIGNMENT_DELAY 56'd0;
	cx <= `BSV_ASSIGNMENT_DELAY 12'd0;
	cx2 <= `BSV_ASSIGNMENT_DELAY 12'd0;
	kernel <= `BSV_ASSIGNMENT_DELAY 4'd0;
	mem_rCache <= `BSV_ASSIGNMENT_DELAY 78'h0AAAAAAAAAAAAAAAAAAA;
	mem_rRdPtr <= `BSV_ASSIGNMENT_DELAY 13'd0;
	mem_rWrPtr <= `BSV_ASSIGNMENT_DELAY 13'd0;
	mx <= `BSV_ASSIGNMENT_DELAY 8'd0;
	p0_rv <= `BSV_ASSIGNMENT_DELAY 2'd0;
	p1_rv <= `BSV_ASSIGNMENT_DELAY 2'd0;
	p2_rv <= `BSV_ASSIGNMENT_DELAY 2'd0;
	p3_rv <= `BSV_ASSIGNMENT_DELAY 2'd0;
	p4_rv <= `BSV_ASSIGNMENT_DELAY 2'd0;
	p5_rv <= `BSV_ASSIGNMENT_DELAY 2'd0;
	p6_rv <= `BSV_ASSIGNMENT_DELAY 2'd0;
	p7_rv <= `BSV_ASSIGNMENT_DELAY 2'd0;
	width <= `BSV_ASSIGNMENT_DELAY 12'd16;
      end
    else
      begin
        if (_unnamed_$EN) _unnamed_ <= `BSV_ASSIGNMENT_DELAY _unnamed_$D_IN;
	if (_unnamed__0_1$EN)
	  _unnamed__0_1 <= `BSV_ASSIGNMENT_DELAY _unnamed__0_1$D_IN;
	if (_unnamed__0_2$EN)
	  _unnamed__0_2 <= `BSV_ASSIGNMENT_DELAY _unnamed__0_2$D_IN;
	if (_unnamed__0_3$EN)
	  _unnamed__0_3 <= `BSV_ASSIGNMENT_DELAY _unnamed__0_3$D_IN;
	if (_unnamed__0_4$EN)
	  _unnamed__0_4 <= `BSV_ASSIGNMENT_DELAY _unnamed__0_4$D_IN;
	if (_unnamed__0_5$EN)
	  _unnamed__0_5 <= `BSV_ASSIGNMENT_DELAY _unnamed__0_5$D_IN;
	if (_unnamed__0_6$EN)
	  _unnamed__0_6 <= `BSV_ASSIGNMENT_DELAY _unnamed__0_6$D_IN;
	if (_unnamed__1$EN)
	  _unnamed__1 <= `BSV_ASSIGNMENT_DELAY _unnamed__1$D_IN;
	if (_unnamed__10$EN)
	  _unnamed__10 <= `BSV_ASSIGNMENT_DELAY _unnamed__10$D_IN;
	if (_unnamed__11$EN)
	  _unnamed__11 <= `BSV_ASSIGNMENT_DELAY _unnamed__11$D_IN;
	if (_unnamed__12$EN)
	  _unnamed__12 <= `BSV_ASSIGNMENT_DELAY _unnamed__12$D_IN;
	if (_unnamed__13$EN)
	  _unnamed__13 <= `BSV_ASSIGNMENT_DELAY _unnamed__13$D_IN;
	if (_unnamed__14$EN)
	  _unnamed__14 <= `BSV_ASSIGNMENT_DELAY _unnamed__14$D_IN;
	if (_unnamed__15$EN)
	  _unnamed__15 <= `BSV_ASSIGNMENT_DELAY _unnamed__15$D_IN;
	if (_unnamed__16$EN)
	  _unnamed__16 <= `BSV_ASSIGNMENT_DELAY _unnamed__16$D_IN;
	if (_unnamed__17$EN)
	  _unnamed__17 <= `BSV_ASSIGNMENT_DELAY _unnamed__17$D_IN;
	if (_unnamed__18$EN)
	  _unnamed__18 <= `BSV_ASSIGNMENT_DELAY _unnamed__18$D_IN;
	if (_unnamed__19$EN)
	  _unnamed__19 <= `BSV_ASSIGNMENT_DELAY _unnamed__19$D_IN;
	if (_unnamed__1_1$EN)
	  _unnamed__1_1 <= `BSV_ASSIGNMENT_DELAY _unnamed__1_1$D_IN;
	if (_unnamed__1_2$EN)
	  _unnamed__1_2 <= `BSV_ASSIGNMENT_DELAY _unnamed__1_2$D_IN;
	if (_unnamed__1_3$EN)
	  _unnamed__1_3 <= `BSV_ASSIGNMENT_DELAY _unnamed__1_3$D_IN;
	if (_unnamed__1_4$EN)
	  _unnamed__1_4 <= `BSV_ASSIGNMENT_DELAY _unnamed__1_4$D_IN;
	if (_unnamed__1_5$EN)
	  _unnamed__1_5 <= `BSV_ASSIGNMENT_DELAY _unnamed__1_5$D_IN;
	if (_unnamed__1_6$EN)
	  _unnamed__1_6 <= `BSV_ASSIGNMENT_DELAY _unnamed__1_6$D_IN;
	if (_unnamed__2$EN)
	  _unnamed__2 <= `BSV_ASSIGNMENT_DELAY _unnamed__2$D_IN;
	if (_unnamed__20$EN)
	  _unnamed__20 <= `BSV_ASSIGNMENT_DELAY _unnamed__20$D_IN;
	if (_unnamed__21$EN)
	  _unnamed__21 <= `BSV_ASSIGNMENT_DELAY _unnamed__21$D_IN;
	if (_unnamed__22$EN)
	  _unnamed__22 <= `BSV_ASSIGNMENT_DELAY _unnamed__22$D_IN;
	if (_unnamed__23$EN)
	  _unnamed__23 <= `BSV_ASSIGNMENT_DELAY _unnamed__23$D_IN;
	if (_unnamed__24$EN)
	  _unnamed__24 <= `BSV_ASSIGNMENT_DELAY _unnamed__24$D_IN;
	if (_unnamed__25$EN)
	  _unnamed__25 <= `BSV_ASSIGNMENT_DELAY _unnamed__25$D_IN;
	if (_unnamed__26$EN)
	  _unnamed__26 <= `BSV_ASSIGNMENT_DELAY _unnamed__26$D_IN;
	if (_unnamed__27$EN)
	  _unnamed__27 <= `BSV_ASSIGNMENT_DELAY _unnamed__27$D_IN;
	if (_unnamed__28$EN)
	  _unnamed__28 <= `BSV_ASSIGNMENT_DELAY _unnamed__28$D_IN;
	if (_unnamed__29$EN)
	  _unnamed__29 <= `BSV_ASSIGNMENT_DELAY _unnamed__29$D_IN;
	if (_unnamed__2_1$EN)
	  _unnamed__2_1 <= `BSV_ASSIGNMENT_DELAY _unnamed__2_1$D_IN;
	if (_unnamed__2_2$EN)
	  _unnamed__2_2 <= `BSV_ASSIGNMENT_DELAY _unnamed__2_2$D_IN;
	if (_unnamed__2_3$EN)
	  _unnamed__2_3 <= `BSV_ASSIGNMENT_DELAY _unnamed__2_3$D_IN;
	if (_unnamed__2_4$EN)
	  _unnamed__2_4 <= `BSV_ASSIGNMENT_DELAY _unnamed__2_4$D_IN;
	if (_unnamed__2_5$EN)
	  _unnamed__2_5 <= `BSV_ASSIGNMENT_DELAY _unnamed__2_5$D_IN;
	if (_unnamed__2_6$EN)
	  _unnamed__2_6 <= `BSV_ASSIGNMENT_DELAY _unnamed__2_6$D_IN;
	if (_unnamed__3$EN)
	  _unnamed__3 <= `BSV_ASSIGNMENT_DELAY _unnamed__3$D_IN;
	if (_unnamed__30$EN)
	  _unnamed__30 <= `BSV_ASSIGNMENT_DELAY _unnamed__30$D_IN;
	if (_unnamed__31$EN)
	  _unnamed__31 <= `BSV_ASSIGNMENT_DELAY _unnamed__31$D_IN;
	if (_unnamed__32$EN)
	  _unnamed__32 <= `BSV_ASSIGNMENT_DELAY _unnamed__32$D_IN;
	if (_unnamed__33$EN)
	  _unnamed__33 <= `BSV_ASSIGNMENT_DELAY _unnamed__33$D_IN;
	if (_unnamed__34$EN)
	  _unnamed__34 <= `BSV_ASSIGNMENT_DELAY _unnamed__34$D_IN;
	if (_unnamed__35$EN)
	  _unnamed__35 <= `BSV_ASSIGNMENT_DELAY _unnamed__35$D_IN;
	if (_unnamed__36$EN)
	  _unnamed__36 <= `BSV_ASSIGNMENT_DELAY _unnamed__36$D_IN;
	if (_unnamed__37$EN)
	  _unnamed__37 <= `BSV_ASSIGNMENT_DELAY _unnamed__37$D_IN;
	if (_unnamed__38$EN)
	  _unnamed__38 <= `BSV_ASSIGNMENT_DELAY _unnamed__38$D_IN;
	if (_unnamed__39$EN)
	  _unnamed__39 <= `BSV_ASSIGNMENT_DELAY _unnamed__39$D_IN;
	if (_unnamed__3_1$EN)
	  _unnamed__3_1 <= `BSV_ASSIGNMENT_DELAY _unnamed__3_1$D_IN;
	if (_unnamed__3_2$EN)
	  _unnamed__3_2 <= `BSV_ASSIGNMENT_DELAY _unnamed__3_2$D_IN;
	if (_unnamed__3_3$EN)
	  _unnamed__3_3 <= `BSV_ASSIGNMENT_DELAY _unnamed__3_3$D_IN;
	if (_unnamed__3_4$EN)
	  _unnamed__3_4 <= `BSV_ASSIGNMENT_DELAY _unnamed__3_4$D_IN;
	if (_unnamed__3_5$EN)
	  _unnamed__3_5 <= `BSV_ASSIGNMENT_DELAY _unnamed__3_5$D_IN;
	if (_unnamed__3_6$EN)
	  _unnamed__3_6 <= `BSV_ASSIGNMENT_DELAY _unnamed__3_6$D_IN;
	if (_unnamed__4$EN)
	  _unnamed__4 <= `BSV_ASSIGNMENT_DELAY _unnamed__4$D_IN;
	if (_unnamed__40$EN)
	  _unnamed__40 <= `BSV_ASSIGNMENT_DELAY _unnamed__40$D_IN;
	if (_unnamed__41$EN)
	  _unnamed__41 <= `BSV_ASSIGNMENT_DELAY _unnamed__41$D_IN;
	if (_unnamed__42$EN)
	  _unnamed__42 <= `BSV_ASSIGNMENT_DELAY _unnamed__42$D_IN;
	if (_unnamed__43$EN)
	  _unnamed__43 <= `BSV_ASSIGNMENT_DELAY _unnamed__43$D_IN;
	if (_unnamed__44$EN)
	  _unnamed__44 <= `BSV_ASSIGNMENT_DELAY _unnamed__44$D_IN;
	if (_unnamed__45$EN)
	  _unnamed__45 <= `BSV_ASSIGNMENT_DELAY _unnamed__45$D_IN;
	if (_unnamed__46$EN)
	  _unnamed__46 <= `BSV_ASSIGNMENT_DELAY _unnamed__46$D_IN;
	if (_unnamed__47$EN)
	  _unnamed__47 <= `BSV_ASSIGNMENT_DELAY _unnamed__47$D_IN;
	if (_unnamed__48$EN)
	  _unnamed__48 <= `BSV_ASSIGNMENT_DELAY _unnamed__48$D_IN;
	if (_unnamed__49$EN)
	  _unnamed__49 <= `BSV_ASSIGNMENT_DELAY _unnamed__49$D_IN;
	if (_unnamed__4_1$EN)
	  _unnamed__4_1 <= `BSV_ASSIGNMENT_DELAY _unnamed__4_1$D_IN;
	if (_unnamed__4_2$EN)
	  _unnamed__4_2 <= `BSV_ASSIGNMENT_DELAY _unnamed__4_2$D_IN;
	if (_unnamed__4_3$EN)
	  _unnamed__4_3 <= `BSV_ASSIGNMENT_DELAY _unnamed__4_3$D_IN;
	if (_unnamed__4_4$EN)
	  _unnamed__4_4 <= `BSV_ASSIGNMENT_DELAY _unnamed__4_4$D_IN;
	if (_unnamed__4_5$EN)
	  _unnamed__4_5 <= `BSV_ASSIGNMENT_DELAY _unnamed__4_5$D_IN;
	if (_unnamed__4_6$EN)
	  _unnamed__4_6 <= `BSV_ASSIGNMENT_DELAY _unnamed__4_6$D_IN;
	if (_unnamed__5$EN)
	  _unnamed__5 <= `BSV_ASSIGNMENT_DELAY _unnamed__5$D_IN;
	if (_unnamed__50$EN)
	  _unnamed__50 <= `BSV_ASSIGNMENT_DELAY _unnamed__50$D_IN;
	if (_unnamed__51$EN)
	  _unnamed__51 <= `BSV_ASSIGNMENT_DELAY _unnamed__51$D_IN;
	if (_unnamed__52$EN)
	  _unnamed__52 <= `BSV_ASSIGNMENT_DELAY _unnamed__52$D_IN;
	if (_unnamed__53$EN)
	  _unnamed__53 <= `BSV_ASSIGNMENT_DELAY _unnamed__53$D_IN;
	if (_unnamed__54$EN)
	  _unnamed__54 <= `BSV_ASSIGNMENT_DELAY _unnamed__54$D_IN;
	if (_unnamed__55$EN)
	  _unnamed__55 <= `BSV_ASSIGNMENT_DELAY _unnamed__55$D_IN;
	if (_unnamed__56$EN)
	  _unnamed__56 <= `BSV_ASSIGNMENT_DELAY _unnamed__56$D_IN;
	if (_unnamed__57$EN)
	  _unnamed__57 <= `BSV_ASSIGNMENT_DELAY _unnamed__57$D_IN;
	if (_unnamed__58$EN)
	  _unnamed__58 <= `BSV_ASSIGNMENT_DELAY _unnamed__58$D_IN;
	if (_unnamed__59$EN)
	  _unnamed__59 <= `BSV_ASSIGNMENT_DELAY _unnamed__59$D_IN;
	if (_unnamed__5_1$EN)
	  _unnamed__5_1 <= `BSV_ASSIGNMENT_DELAY _unnamed__5_1$D_IN;
	if (_unnamed__5_2$EN)
	  _unnamed__5_2 <= `BSV_ASSIGNMENT_DELAY _unnamed__5_2$D_IN;
	if (_unnamed__5_3$EN)
	  _unnamed__5_3 <= `BSV_ASSIGNMENT_DELAY _unnamed__5_3$D_IN;
	if (_unnamed__5_4$EN)
	  _unnamed__5_4 <= `BSV_ASSIGNMENT_DELAY _unnamed__5_4$D_IN;
	if (_unnamed__5_5$EN)
	  _unnamed__5_5 <= `BSV_ASSIGNMENT_DELAY _unnamed__5_5$D_IN;
	if (_unnamed__5_6$EN)
	  _unnamed__5_6 <= `BSV_ASSIGNMENT_DELAY _unnamed__5_6$D_IN;
	if (_unnamed__6$EN)
	  _unnamed__6 <= `BSV_ASSIGNMENT_DELAY _unnamed__6$D_IN;
	if (_unnamed__60$EN)
	  _unnamed__60 <= `BSV_ASSIGNMENT_DELAY _unnamed__60$D_IN;
	if (_unnamed__61$EN)
	  _unnamed__61 <= `BSV_ASSIGNMENT_DELAY _unnamed__61$D_IN;
	if (_unnamed__62$EN)
	  _unnamed__62 <= `BSV_ASSIGNMENT_DELAY _unnamed__62$D_IN;
	if (_unnamed__63$EN)
	  _unnamed__63 <= `BSV_ASSIGNMENT_DELAY _unnamed__63$D_IN;
	if (_unnamed__64$EN)
	  _unnamed__64 <= `BSV_ASSIGNMENT_DELAY _unnamed__64$D_IN;
	if (_unnamed__6_1$EN)
	  _unnamed__6_1 <= `BSV_ASSIGNMENT_DELAY _unnamed__6_1$D_IN;
	if (_unnamed__6_2$EN)
	  _unnamed__6_2 <= `BSV_ASSIGNMENT_DELAY _unnamed__6_2$D_IN;
	if (_unnamed__6_3$EN)
	  _unnamed__6_3 <= `BSV_ASSIGNMENT_DELAY _unnamed__6_3$D_IN;
	if (_unnamed__6_4$EN)
	  _unnamed__6_4 <= `BSV_ASSIGNMENT_DELAY _unnamed__6_4$D_IN;
	if (_unnamed__6_5$EN)
	  _unnamed__6_5 <= `BSV_ASSIGNMENT_DELAY _unnamed__6_5$D_IN;
	if (_unnamed__6_6$EN)
	  _unnamed__6_6 <= `BSV_ASSIGNMENT_DELAY _unnamed__6_6$D_IN;
	if (_unnamed__7$EN)
	  _unnamed__7 <= `BSV_ASSIGNMENT_DELAY _unnamed__7$D_IN;
	if (_unnamed__7_1$EN)
	  _unnamed__7_1 <= `BSV_ASSIGNMENT_DELAY _unnamed__7_1$D_IN;
	if (_unnamed__7_2$EN)
	  _unnamed__7_2 <= `BSV_ASSIGNMENT_DELAY _unnamed__7_2$D_IN;
	if (_unnamed__7_3$EN)
	  _unnamed__7_3 <= `BSV_ASSIGNMENT_DELAY _unnamed__7_3$D_IN;
	if (_unnamed__7_4$EN)
	  _unnamed__7_4 <= `BSV_ASSIGNMENT_DELAY _unnamed__7_4$D_IN;
	if (_unnamed__7_5$EN)
	  _unnamed__7_5 <= `BSV_ASSIGNMENT_DELAY _unnamed__7_5$D_IN;
	if (_unnamed__7_6$EN)
	  _unnamed__7_6 <= `BSV_ASSIGNMENT_DELAY _unnamed__7_6$D_IN;
	if (_unnamed__8$EN)
	  _unnamed__8 <= `BSV_ASSIGNMENT_DELAY _unnamed__8$D_IN;
	if (_unnamed__9$EN)
	  _unnamed__9 <= `BSV_ASSIGNMENT_DELAY _unnamed__9$D_IN;
	if (cx$EN) cx <= `BSV_ASSIGNMENT_DELAY cx$D_IN;
	if (cx2$EN) cx2 <= `BSV_ASSIGNMENT_DELAY cx2$D_IN;
	if (kernel$EN) kernel <= `BSV_ASSIGNMENT_DELAY kernel$D_IN;
	if (mem_rCache$EN)
	  mem_rCache <= `BSV_ASSIGNMENT_DELAY mem_rCache$D_IN;
	if (mem_rRdPtr$EN)
	  mem_rRdPtr <= `BSV_ASSIGNMENT_DELAY mem_rRdPtr$D_IN;
	if (mem_rWrPtr$EN)
	  mem_rWrPtr <= `BSV_ASSIGNMENT_DELAY mem_rWrPtr$D_IN;
	if (mx$EN) mx <= `BSV_ASSIGNMENT_DELAY mx$D_IN;
	if (p0_rv$EN) p0_rv <= `BSV_ASSIGNMENT_DELAY p0_rv$D_IN;
	if (p1_rv$EN) p1_rv <= `BSV_ASSIGNMENT_DELAY p1_rv$D_IN;
	if (p2_rv$EN) p2_rv <= `BSV_ASSIGNMENT_DELAY p2_rv$D_IN;
	if (p3_rv$EN) p3_rv <= `BSV_ASSIGNMENT_DELAY p3_rv$D_IN;
	if (p4_rv$EN) p4_rv <= `BSV_ASSIGNMENT_DELAY p4_rv$D_IN;
	if (p5_rv$EN) p5_rv <= `BSV_ASSIGNMENT_DELAY p5_rv$D_IN;
	if (p6_rv$EN) p6_rv <= `BSV_ASSIGNMENT_DELAY p6_rv$D_IN;
	if (p7_rv$EN) p7_rv <= `BSV_ASSIGNMENT_DELAY p7_rv$D_IN;
	if (width$EN) width <= `BSV_ASSIGNMENT_DELAY width$D_IN;
      end
  end

  // synopsys translate_off
  `ifdef BSV_NO_INITIAL_BLOCKS
  `else // not BSV_NO_INITIAL_BLOCKS
  initial
  begin
    _unnamed_ = 8'hAA;
    _unnamed__0_1 = 16'hAAAA;
    _unnamed__0_2 = 24'hAAAAAA;
    _unnamed__0_3 = 32'hAAAAAAAA;
    _unnamed__0_4 = 40'hAAAAAAAAAA;
    _unnamed__0_5 = 48'hAAAAAAAAAAAA;
    _unnamed__0_6 = 56'hAAAAAAAAAAAAAA;
    _unnamed__1 = 8'hAA;
    _unnamed__10 = 56'hAAAAAAAAAAAAAA;
    _unnamed__11 = 56'hAAAAAAAAAAAAAA;
    _unnamed__12 = 56'hAAAAAAAAAAAAAA;
    _unnamed__13 = 56'hAAAAAAAAAAAAAA;
    _unnamed__14 = 56'hAAAAAAAAAAAAAA;
    _unnamed__15 = 56'hAAAAAAAAAAAAAA;
    _unnamed__16 = 56'hAAAAAAAAAAAAAA;
    _unnamed__17 = 56'hAAAAAAAAAAAAAA;
    _unnamed__18 = 56'hAAAAAAAAAAAAAA;
    _unnamed__19 = 56'hAAAAAAAAAAAAAA;
    _unnamed__1_1 = 16'hAAAA;
    _unnamed__1_2 = 24'hAAAAAA;
    _unnamed__1_3 = 32'hAAAAAAAA;
    _unnamed__1_4 = 40'hAAAAAAAAAA;
    _unnamed__1_5 = 48'hAAAAAAAAAAAA;
    _unnamed__1_6 = 56'hAAAAAAAAAAAAAA;
    _unnamed__2 = 8'hAA;
    _unnamed__20 = 56'hAAAAAAAAAAAAAA;
    _unnamed__21 = 56'hAAAAAAAAAAAAAA;
    _unnamed__22 = 56'hAAAAAAAAAAAAAA;
    _unnamed__23 = 56'hAAAAAAAAAAAAAA;
    _unnamed__24 = 56'hAAAAAAAAAAAAAA;
    _unnamed__25 = 56'hAAAAAAAAAAAAAA;
    _unnamed__26 = 56'hAAAAAAAAAAAAAA;
    _unnamed__27 = 56'hAAAAAAAAAAAAAA;
    _unnamed__28 = 56'hAAAAAAAAAAAAAA;
    _unnamed__29 = 56'hAAAAAAAAAAAAAA;
    _unnamed__2_1 = 16'hAAAA;
    _unnamed__2_2 = 24'hAAAAAA;
    _unnamed__2_3 = 32'hAAAAAAAA;
    _unnamed__2_4 = 40'hAAAAAAAAAA;
    _unnamed__2_5 = 48'hAAAAAAAAAAAA;
    _unnamed__2_6 = 56'hAAAAAAAAAAAAAA;
    _unnamed__3 = 8'hAA;
    _unnamed__30 = 56'hAAAAAAAAAAAAAA;
    _unnamed__31 = 56'hAAAAAAAAAAAAAA;
    _unnamed__32 = 56'hAAAAAAAAAAAAAA;
    _unnamed__33 = 56'hAAAAAAAAAAAAAA;
    _unnamed__34 = 56'hAAAAAAAAAAAAAA;
    _unnamed__35 = 56'hAAAAAAAAAAAAAA;
    _unnamed__36 = 56'hAAAAAAAAAAAAAA;
    _unnamed__37 = 56'hAAAAAAAAAAAAAA;
    _unnamed__38 = 56'hAAAAAAAAAAAAAA;
    _unnamed__39 = 56'hAAAAAAAAAAAAAA;
    _unnamed__3_1 = 16'hAAAA;
    _unnamed__3_2 = 24'hAAAAAA;
    _unnamed__3_3 = 32'hAAAAAAAA;
    _unnamed__3_4 = 40'hAAAAAAAAAA;
    _unnamed__3_5 = 48'hAAAAAAAAAAAA;
    _unnamed__3_6 = 56'hAAAAAAAAAAAAAA;
    _unnamed__4 = 8'hAA;
    _unnamed__40 = 56'hAAAAAAAAAAAAAA;
    _unnamed__41 = 56'hAAAAAAAAAAAAAA;
    _unnamed__42 = 56'hAAAAAAAAAAAAAA;
    _unnamed__43 = 56'hAAAAAAAAAAAAAA;
    _unnamed__44 = 56'hAAAAAAAAAAAAAA;
    _unnamed__45 = 56'hAAAAAAAAAAAAAA;
    _unnamed__46 = 56'hAAAAAAAAAAAAAA;
    _unnamed__47 = 56'hAAAAAAAAAAAAAA;
    _unnamed__48 = 56'hAAAAAAAAAAAAAA;
    _unnamed__49 = 56'hAAAAAAAAAAAAAA;
    _unnamed__4_1 = 16'hAAAA;
    _unnamed__4_2 = 24'hAAAAAA;
    _unnamed__4_3 = 32'hAAAAAAAA;
    _unnamed__4_4 = 40'hAAAAAAAAAA;
    _unnamed__4_5 = 48'hAAAAAAAAAAAA;
    _unnamed__4_6 = 56'hAAAAAAAAAAAAAA;
    _unnamed__5 = 8'hAA;
    _unnamed__50 = 56'hAAAAAAAAAAAAAA;
    _unnamed__51 = 56'hAAAAAAAAAAAAAA;
    _unnamed__52 = 56'hAAAAAAAAAAAAAA;
    _unnamed__53 = 56'hAAAAAAAAAAAAAA;
    _unnamed__54 = 56'hAAAAAAAAAAAAAA;
    _unnamed__55 = 56'hAAAAAAAAAAAAAA;
    _unnamed__56 = 56'hAAAAAAAAAAAAAA;
    _unnamed__57 = 56'hAAAAAAAAAAAAAA;
    _unnamed__58 = 56'hAAAAAAAAAAAAAA;
    _unnamed__59 = 56'hAAAAAAAAAAAAAA;
    _unnamed__5_1 = 16'hAAAA;
    _unnamed__5_2 = 24'hAAAAAA;
    _unnamed__5_3 = 32'hAAAAAAAA;
    _unnamed__5_4 = 40'hAAAAAAAAAA;
    _unnamed__5_5 = 48'hAAAAAAAAAAAA;
    _unnamed__5_6 = 56'hAAAAAAAAAAAAAA;
    _unnamed__6 = 8'hAA;
    _unnamed__60 = 56'hAAAAAAAAAAAAAA;
    _unnamed__61 = 56'hAAAAAAAAAAAAAA;
    _unnamed__62 = 56'hAAAAAAAAAAAAAA;
    _unnamed__63 = 56'hAAAAAAAAAAAAAA;
    _unnamed__64 = 64'hAAAAAAAAAAAAAAAA;
    _unnamed__6_1 = 16'hAAAA;
    _unnamed__6_2 = 24'hAAAAAA;
    _unnamed__6_3 = 32'hAAAAAAAA;
    _unnamed__6_4 = 40'hAAAAAAAAAA;
    _unnamed__6_5 = 48'hAAAAAAAAAAAA;
    _unnamed__6_6 = 56'hAAAAAAAAAAAAAA;
    _unnamed__7 = 8'hAA;
    _unnamed__7_1 = 16'hAAAA;
    _unnamed__7_2 = 24'hAAAAAA;
    _unnamed__7_3 = 32'hAAAAAAAA;
    _unnamed__7_4 = 40'hAAAAAAAAAA;
    _unnamed__7_5 = 48'hAAAAAAAAAAAA;
    _unnamed__7_6 = 56'hAAAAAAAAAAAAAA;
    _unnamed__8 = 56'hAAAAAAAAAAAAAA;
    _unnamed__9 = 56'hAAAAAAAAAAAAAA;
    cx = 12'hAAA;
    cx2 = 12'hAAA;
    kernel = 4'hA;
    mem_rCache = 78'h2AAAAAAAAAAAAAAAAAAA;
    mem_rRdPtr = 13'h0AAA;
    mem_rWrPtr = 13'h0AAA;
    mx = 8'hAA;
    p0_rv = 2'h2;
    p1_rv = 2'h2;
    p2_rv = 2'h2;
    p3_rv = 2'h2;
    p4_rv = 2'h2;
    p5_rv = 2'h2;
    p6_rv = 2'h2;
    p7_rv = 2'h2;
    width = 12'hAAA;
  end
  `endif // BSV_NO_INITIAL_BLOCKS
  // synopsys translate_on
endmodule  // mkMerge

