/*
 * Generated by Bluespec Compiler, version 2023.01 (build 52adafa5)
 * 
 * On Sun May  7 22:40:23 IST 2023
 * 
 */

/* Generation options: */
#ifndef __mkCoalesce_h__
#define __mkCoalesce_h__

#include "bluesim_types.h"
#include "bs_module.h"
#include "bluesim_primitives.h"
#include "bs_vcd.h"


/* Class declaration for the mkCoalesce module */
class MOD_mkCoalesce : public Module {
 
 /* Clock handles */
 private:
  tClock __clk_handle_0;
 
 /* Clock gate handles */
 public:
  tUInt8 *clk_gate[0];
 
 /* Instantiation parameters */
 public:
 
 /* Module state */
 public:
  MOD_Reg<tUInt8> INST__unnamed_;
  MOD_Reg<tUInt8> INST__unnamed__0_1;
  MOD_Reg<tUInt8> INST__unnamed__0_2;
  MOD_Reg<tUInt8> INST__unnamed__0_3;
  MOD_Reg<tUInt8> INST__unnamed__1;
  MOD_Reg<tUInt8> INST__unnamed__10;
  MOD_Reg<tUInt8> INST__unnamed__10_1;
  MOD_Reg<tUInt8> INST__unnamed__10_2;
  MOD_Reg<tUInt8> INST__unnamed__10_3;
  MOD_Reg<tUInt8> INST__unnamed__11;
  MOD_Reg<tUInt8> INST__unnamed__11_1;
  MOD_Reg<tUInt8> INST__unnamed__11_2;
  MOD_Reg<tUInt8> INST__unnamed__11_3;
  MOD_Reg<tUInt8> INST__unnamed__12;
  MOD_Reg<tUInt8> INST__unnamed__12_1;
  MOD_Reg<tUInt8> INST__unnamed__12_2;
  MOD_Reg<tUInt8> INST__unnamed__12_3;
  MOD_Reg<tUInt8> INST__unnamed__13;
  MOD_Reg<tUInt8> INST__unnamed__13_1;
  MOD_Reg<tUInt8> INST__unnamed__13_2;
  MOD_Reg<tUInt8> INST__unnamed__13_3;
  MOD_Reg<tUInt8> INST__unnamed__14;
  MOD_Reg<tUInt8> INST__unnamed__14_1;
  MOD_Reg<tUInt8> INST__unnamed__14_2;
  MOD_Reg<tUInt8> INST__unnamed__14_3;
  MOD_Reg<tUInt8> INST__unnamed__15;
  MOD_Reg<tUInt8> INST__unnamed__15_1;
  MOD_Reg<tUInt8> INST__unnamed__15_2;
  MOD_Reg<tUInt8> INST__unnamed__15_3;
  MOD_Reg<tUInt8> INST__unnamed__1_1;
  MOD_Reg<tUInt8> INST__unnamed__1_2;
  MOD_Reg<tUInt8> INST__unnamed__1_3;
  MOD_Reg<tUInt8> INST__unnamed__2;
  MOD_Reg<tUInt8> INST__unnamed__2_1;
  MOD_Reg<tUInt8> INST__unnamed__2_2;
  MOD_Reg<tUInt8> INST__unnamed__2_3;
  MOD_Reg<tUInt8> INST__unnamed__3;
  MOD_Reg<tUInt8> INST__unnamed__3_1;
  MOD_Reg<tUInt8> INST__unnamed__3_2;
  MOD_Reg<tUInt8> INST__unnamed__3_3;
  MOD_Reg<tUInt8> INST__unnamed__4;
  MOD_Reg<tUInt8> INST__unnamed__4_1;
  MOD_Reg<tUInt8> INST__unnamed__4_2;
  MOD_Reg<tUInt8> INST__unnamed__4_3;
  MOD_Reg<tUInt8> INST__unnamed__5;
  MOD_Reg<tUInt8> INST__unnamed__5_1;
  MOD_Reg<tUInt8> INST__unnamed__5_2;
  MOD_Reg<tUInt8> INST__unnamed__5_3;
  MOD_Reg<tUInt8> INST__unnamed__6;
  MOD_Reg<tUInt8> INST__unnamed__6_1;
  MOD_Reg<tUInt8> INST__unnamed__6_2;
  MOD_Reg<tUInt8> INST__unnamed__6_3;
  MOD_Reg<tUInt8> INST__unnamed__7;
  MOD_Reg<tUInt8> INST__unnamed__7_1;
  MOD_Reg<tUInt8> INST__unnamed__7_2;
  MOD_Reg<tUInt8> INST__unnamed__7_3;
  MOD_Reg<tUInt8> INST__unnamed__8;
  MOD_Reg<tUInt8> INST__unnamed__8_1;
  MOD_Reg<tUInt8> INST__unnamed__8_2;
  MOD_Reg<tUInt8> INST__unnamed__8_3;
  MOD_Reg<tUInt8> INST__unnamed__9;
  MOD_Reg<tUInt8> INST__unnamed__9_1;
  MOD_Reg<tUInt8> INST__unnamed__9_2;
  MOD_Reg<tUInt8> INST__unnamed__9_3;
  MOD_Fifo<tUWide> INST_inQ;
  MOD_CReg<tUInt8> INST_p0_rv;
  MOD_CReg<tUInt8> INST_p1_rv;
  MOD_CReg<tUInt8> INST_p2_rv;
  MOD_CReg<tUInt8> INST_p3_rv;
 
 /* Constructor */
 public:
  MOD_mkCoalesce(tSimStateHdl simHdl, char const *name, Module *parent);
 
 /* Symbol init methods */
 private:
  void init_symbols_0();
 
 /* Reset signal definitions */
 private:
  tUInt8 PORT_RST_N;
 
 /* Port definitions */
 public:
  tUWide PORT_put_datas;
  tUWide PORT_get;
 
 /* Publicly accessible definitions */
 public:
 
 /* Local definitions */
 private:
  tUWide DEF_inQ_first____d51;
  tUWide DEF_unnamed__15_3_7_CONCAT_unnamed__14_3_8_9_CONCA_ETC___d107;
  tUWide DEF_unnamed__15_3_7_CONCAT_unnamed__14_3_8_9_CONCA_ETC___d104;
  tUWide DEF_unnamed__15_3_7_CONCAT_unnamed__14_3_8_9_CONCA_ETC___d101;
  tUInt8 DEF__0_CONCAT_DONTCARE___d74;
 
 /* Rules */
 public:
  void RL__Q1();
  void RL__Q2();
  void RL__Q3();
  void RL__Q1_1();
  void RL__Q2_1();
  void RL__Q3_1();
  void RL__Q1_2();
  void RL__Q2_2();
  void RL__Q3_2();
  void RL__Q1_3();
  void RL__Q2_3();
  void RL__Q3_3();
  void RL__Q1_4();
  void RL__Q2_4();
  void RL__Q3_4();
  void RL__Q1_5();
  void RL__Q2_5();
  void RL__Q3_5();
  void RL__Q1_6();
  void RL__Q2_6();
  void RL__Q3_6();
  void RL__Q1_7();
  void RL__Q2_7();
  void RL__Q3_7();
  void RL__Q1_8();
  void RL__Q2_8();
  void RL__Q3_8();
  void RL__Q1_9();
  void RL__Q2_9();
  void RL__Q3_9();
  void RL__Q1_10();
  void RL__Q2_10();
  void RL__Q3_10();
  void RL__Q1_11();
  void RL__Q2_11();
  void RL__Q3_11();
  void RL__Q1_12();
  void RL__Q2_12();
  void RL__Q3_12();
  void RL__Q1_13();
  void RL__Q2_13();
  void RL__Q3_13();
  void RL__Q1_14();
  void RL__Q2_14();
  void RL__Q3_14();
  void RL__activate1();
  void RL__activate2();
  void RL__activate3();
  void RL__activate4();
 
 /* Methods */
 public:
  void METH_put(tUWide ARG_put_datas);
  tUInt8 METH_RDY_put();
  tUWide METH_get();
  tUInt8 METH_RDY_get();
 
 /* Reset routines */
 public:
  void reset_RST_N(tUInt8 ARG_rst_in);
 
 /* Static handles to reset routines */
 public:
 
 /* Pointers to reset fns in parent module for asserting output resets */
 private:
 
 /* Functions for the parent module to register its reset fns */
 public:
 
 /* Functions to set the elaborated clock id */
 public:
  void set_clk_0(char const *s);
 
 /* State dumping routine */
 public:
  void dump_state(unsigned int indent);
 
 /* VCD dumping routines */
 public:
  unsigned int dump_VCD_defs(unsigned int levels);
  void dump_VCD(tVCDDumpType dt, unsigned int levels, MOD_mkCoalesce &backing);
  void vcd_defs(tVCDDumpType dt, MOD_mkCoalesce &backing);
  void vcd_prims(tVCDDumpType dt, MOD_mkCoalesce &backing);
};

#endif /* ifndef __mkCoalesce_h__ */
