/*
 * Generated by Bluespec Compiler, version 2023.01-6-g034050db (build 034050db)
 * 
 * On Tue May  9 19:08:20 IST 2023
 * 
 */

/* Generation options: */
#ifndef __model_mkFlowTest3_h__
#define __model_mkFlowTest3_h__

#include "bluesim_types.h"
#include "bs_module.h"
#include "bluesim_primitives.h"
#include "bs_vcd.h"

#include "bs_model.h"
#include "mkFlowTest3.h"

/* Class declaration for a model of mkFlowTest3 */
class MODEL_mkFlowTest3 : public Model {
 
 /* Top-level module instance */
 private:
  MOD_mkFlowTest3 *mkFlowTest3_instance;
 
 /* Handle to the simulation kernel */
 private:
  tSimStateHdl sim_hdl;
 
 /* Constructor */
 public:
  MODEL_mkFlowTest3();
 
 /* Functions required by the kernel */
 public:
  void create_model(tSimStateHdl simHdl, bool master);
  void destroy_model();
  void reset_model(bool asserted);
  void get_version(char const **name, char const **build);
  time_t get_creation_time();
  void * get_instance();
  void dump_state();
  void dump_VCD_defs();
  void dump_VCD(tVCDDumpType dt);
};

/* Function for creating a new model */
extern "C" {
  void * new_MODEL_mkFlowTest3();
}

#endif /* ifndef __model_mkFlowTest3_h__ */
