//
// Generated by Bluespec Compiler, version untagged-gad02e931 (build ad02e931)
//
// On Tue Jan 11 16:10:21 GMT 2022
//
//
// Ports:
// Name                         I/O  size props
// RDY_put                        O     1 reg
// get                            O   576 reg
// RDY_get                        O     1
// RDY_configure                  O     1 const
// CLK                            I     1 clock
// RST_N                          I     1 reset
// put_datas                      I    80 reg
// configure_a                    I     4 unused
// configure_m                    I     8 reg
// configure_wx                   I    12 reg
// EN_put                         I     1
// EN_configure                   I     1
// EN_get                         I     1
//
// No combinational paths from inputs to outputs
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkMerge(CLK,
	       RST_N,

	       put_datas,
	       EN_put,
	       RDY_put,

	       EN_get,
	       get,
	       RDY_get,

	       configure_a,
	       configure_m,
	       configure_wx,
	       EN_configure,
	       RDY_configure);
  input  CLK;
  input  RST_N;

  // action method put
  input  [79 : 0] put_datas;
  input  EN_put;
  output RDY_put;

  // actionvalue method get
  input  EN_get;
  output [575 : 0] get;
  output RDY_get;

  // action method configure
  input  [3 : 0] configure_a;
  input  [7 : 0] configure_m;
  input  [11 : 0] configure_wx;
  input  EN_configure;
  output RDY_configure;

  // signals for module outputs
  wire [575 : 0] get;
  wire RDY_configure, RDY_get, RDY_put;

  // inlined wires
  wire [1 : 0] p0_rv$port1__read,
	       p0_rv$port2__read,
	       p1_rv$port1__read,
	       p1_rv$port2__read,
	       p2_rv$port1__read,
	       p2_rv$port2__read,
	       p3_rv$port1__read,
	       p3_rv$port2__read;
  wire mem_pwDequeue$whas,
       mem_pwEnqueue$whas,
       p0_rv$EN_port1__write,
       p1_rv$EN_port0__write,
       p2_rv$EN_port0__write,
       p2_rv$EN_port1__write,
       p3_rv$EN_port1__write;

  // register _unnamed_
  reg [7 : 0] _unnamed_;
  wire [7 : 0] _unnamed_$D_IN;
  wire _unnamed_$EN;

  // register _unnamed__0_1
  reg [15 : 0] _unnamed__0_1;
  wire [15 : 0] _unnamed__0_1$D_IN;
  wire _unnamed__0_1$EN;

  // register _unnamed__0_2
  reg [23 : 0] _unnamed__0_2;
  wire [23 : 0] _unnamed__0_2$D_IN;
  wire _unnamed__0_2$EN;

  // register _unnamed__1
  reg [7 : 0] _unnamed__1;
  wire [7 : 0] _unnamed__1$D_IN;
  wire _unnamed__1$EN;

  // register _unnamed__10
  reg [23 : 0] _unnamed__10;
  wire [23 : 0] _unnamed__10$D_IN;
  wire _unnamed__10$EN;

  // register _unnamed__11
  reg [23 : 0] _unnamed__11;
  wire [23 : 0] _unnamed__11$D_IN;
  wire _unnamed__11$EN;

  // register _unnamed__12
  reg [23 : 0] _unnamed__12;
  wire [23 : 0] _unnamed__12$D_IN;
  wire _unnamed__12$EN;

  // register _unnamed__13
  reg [23 : 0] _unnamed__13;
  wire [23 : 0] _unnamed__13$D_IN;
  wire _unnamed__13$EN;

  // register _unnamed__14
  reg [23 : 0] _unnamed__14;
  wire [23 : 0] _unnamed__14$D_IN;
  wire _unnamed__14$EN;

  // register _unnamed__15
  reg [23 : 0] _unnamed__15;
  wire [23 : 0] _unnamed__15$D_IN;
  wire _unnamed__15$EN;

  // register _unnamed__16
  reg [23 : 0] _unnamed__16;
  wire [23 : 0] _unnamed__16$D_IN;
  wire _unnamed__16$EN;

  // register _unnamed__17
  reg [23 : 0] _unnamed__17;
  wire [23 : 0] _unnamed__17$D_IN;
  wire _unnamed__17$EN;

  // register _unnamed__18
  reg [23 : 0] _unnamed__18;
  wire [23 : 0] _unnamed__18$D_IN;
  wire _unnamed__18$EN;

  // register _unnamed__19
  reg [23 : 0] _unnamed__19;
  wire [23 : 0] _unnamed__19$D_IN;
  wire _unnamed__19$EN;

  // register _unnamed__1_1
  reg [15 : 0] _unnamed__1_1;
  wire [15 : 0] _unnamed__1_1$D_IN;
  wire _unnamed__1_1$EN;

  // register _unnamed__1_2
  reg [23 : 0] _unnamed__1_2;
  wire [23 : 0] _unnamed__1_2$D_IN;
  wire _unnamed__1_2$EN;

  // register _unnamed__2
  reg [7 : 0] _unnamed__2;
  wire [7 : 0] _unnamed__2$D_IN;
  wire _unnamed__2$EN;

  // register _unnamed__20
  reg [23 : 0] _unnamed__20;
  wire [23 : 0] _unnamed__20$D_IN;
  wire _unnamed__20$EN;

  // register _unnamed__21
  reg [23 : 0] _unnamed__21;
  wire [23 : 0] _unnamed__21$D_IN;
  wire _unnamed__21$EN;

  // register _unnamed__22
  reg [23 : 0] _unnamed__22;
  wire [23 : 0] _unnamed__22$D_IN;
  wire _unnamed__22$EN;

  // register _unnamed__23
  reg [23 : 0] _unnamed__23;
  wire [23 : 0] _unnamed__23$D_IN;
  wire _unnamed__23$EN;

  // register _unnamed__24
  reg [23 : 0] _unnamed__24;
  wire [23 : 0] _unnamed__24$D_IN;
  wire _unnamed__24$EN;

  // register _unnamed__25
  reg [23 : 0] _unnamed__25;
  wire [23 : 0] _unnamed__25$D_IN;
  wire _unnamed__25$EN;

  // register _unnamed__26
  reg [23 : 0] _unnamed__26;
  wire [23 : 0] _unnamed__26$D_IN;
  wire _unnamed__26$EN;

  // register _unnamed__27
  reg [23 : 0] _unnamed__27;
  wire [23 : 0] _unnamed__27$D_IN;
  wire _unnamed__27$EN;

  // register _unnamed__28
  reg [23 : 0] _unnamed__28;
  wire [23 : 0] _unnamed__28$D_IN;
  wire _unnamed__28$EN;

  // register _unnamed__29
  reg [23 : 0] _unnamed__29;
  wire [23 : 0] _unnamed__29$D_IN;
  wire _unnamed__29$EN;

  // register _unnamed__2_1
  reg [15 : 0] _unnamed__2_1;
  wire [15 : 0] _unnamed__2_1$D_IN;
  wire _unnamed__2_1$EN;

  // register _unnamed__2_2
  reg [23 : 0] _unnamed__2_2;
  wire [23 : 0] _unnamed__2_2$D_IN;
  wire _unnamed__2_2$EN;

  // register _unnamed__3
  reg [7 : 0] _unnamed__3;
  wire [7 : 0] _unnamed__3$D_IN;
  wire _unnamed__3$EN;

  // register _unnamed__30
  reg [23 : 0] _unnamed__30;
  wire [23 : 0] _unnamed__30$D_IN;
  wire _unnamed__30$EN;

  // register _unnamed__31
  reg [23 : 0] _unnamed__31;
  wire [23 : 0] _unnamed__31$D_IN;
  wire _unnamed__31$EN;

  // register _unnamed__32
  reg [23 : 0] _unnamed__32;
  wire [23 : 0] _unnamed__32$D_IN;
  wire _unnamed__32$EN;

  // register _unnamed__33
  reg [23 : 0] _unnamed__33;
  wire [23 : 0] _unnamed__33$D_IN;
  wire _unnamed__33$EN;

  // register _unnamed__34
  reg [23 : 0] _unnamed__34;
  wire [23 : 0] _unnamed__34$D_IN;
  wire _unnamed__34$EN;

  // register _unnamed__35
  reg [23 : 0] _unnamed__35;
  wire [23 : 0] _unnamed__35$D_IN;
  wire _unnamed__35$EN;

  // register _unnamed__36
  reg [23 : 0] _unnamed__36;
  wire [23 : 0] _unnamed__36$D_IN;
  wire _unnamed__36$EN;

  // register _unnamed__37
  reg [23 : 0] _unnamed__37;
  wire [23 : 0] _unnamed__37$D_IN;
  wire _unnamed__37$EN;

  // register _unnamed__38
  reg [23 : 0] _unnamed__38;
  wire [23 : 0] _unnamed__38$D_IN;
  wire _unnamed__38$EN;

  // register _unnamed__39
  reg [23 : 0] _unnamed__39;
  wire [23 : 0] _unnamed__39$D_IN;
  wire _unnamed__39$EN;

  // register _unnamed__3_1
  reg [15 : 0] _unnamed__3_1;
  wire [15 : 0] _unnamed__3_1$D_IN;
  wire _unnamed__3_1$EN;

  // register _unnamed__3_2
  reg [23 : 0] _unnamed__3_2;
  wire [23 : 0] _unnamed__3_2$D_IN;
  wire _unnamed__3_2$EN;

  // register _unnamed__4
  reg [7 : 0] _unnamed__4;
  wire [7 : 0] _unnamed__4$D_IN;
  wire _unnamed__4$EN;

  // register _unnamed__40
  reg [79 : 0] _unnamed__40;
  wire [79 : 0] _unnamed__40$D_IN;
  wire _unnamed__40$EN;

  // register _unnamed__4_1
  reg [15 : 0] _unnamed__4_1;
  wire [15 : 0] _unnamed__4_1$D_IN;
  wire _unnamed__4_1$EN;

  // register _unnamed__4_2
  reg [23 : 0] _unnamed__4_2;
  wire [23 : 0] _unnamed__4_2$D_IN;
  wire _unnamed__4_2$EN;

  // register _unnamed__5
  reg [7 : 0] _unnamed__5;
  wire [7 : 0] _unnamed__5$D_IN;
  wire _unnamed__5$EN;

  // register _unnamed__5_1
  reg [15 : 0] _unnamed__5_1;
  wire [15 : 0] _unnamed__5_1$D_IN;
  wire _unnamed__5_1$EN;

  // register _unnamed__5_2
  reg [23 : 0] _unnamed__5_2;
  wire [23 : 0] _unnamed__5_2$D_IN;
  wire _unnamed__5_2$EN;

  // register _unnamed__6
  reg [7 : 0] _unnamed__6;
  wire [7 : 0] _unnamed__6$D_IN;
  wire _unnamed__6$EN;

  // register _unnamed__6_1
  reg [15 : 0] _unnamed__6_1;
  wire [15 : 0] _unnamed__6_1$D_IN;
  wire _unnamed__6_1$EN;

  // register _unnamed__6_2
  reg [23 : 0] _unnamed__6_2;
  wire [23 : 0] _unnamed__6_2$D_IN;
  wire _unnamed__6_2$EN;

  // register _unnamed__7
  reg [7 : 0] _unnamed__7;
  wire [7 : 0] _unnamed__7$D_IN;
  wire _unnamed__7$EN;

  // register _unnamed__7_1
  reg [15 : 0] _unnamed__7_1;
  wire [15 : 0] _unnamed__7_1$D_IN;
  wire _unnamed__7_1$EN;

  // register _unnamed__7_2
  reg [23 : 0] _unnamed__7_2;
  wire [23 : 0] _unnamed__7_2$D_IN;
  wire _unnamed__7_2$EN;

  // register _unnamed__8
  reg [7 : 0] _unnamed__8;
  wire [7 : 0] _unnamed__8$D_IN;
  wire _unnamed__8$EN;

  // register _unnamed__8_1
  reg [15 : 0] _unnamed__8_1;
  wire [15 : 0] _unnamed__8_1$D_IN;
  wire _unnamed__8_1$EN;

  // register _unnamed__8_2
  reg [23 : 0] _unnamed__8_2;
  wire [23 : 0] _unnamed__8_2$D_IN;
  wire _unnamed__8_2$EN;

  // register _unnamed__9
  reg [7 : 0] _unnamed__9;
  wire [7 : 0] _unnamed__9$D_IN;
  wire _unnamed__9$EN;

  // register _unnamed__9_1
  reg [15 : 0] _unnamed__9_1;
  wire [15 : 0] _unnamed__9_1$D_IN;
  wire _unnamed__9_1$EN;

  // register _unnamed__9_2
  reg [23 : 0] _unnamed__9_2;
  wire [23 : 0] _unnamed__9_2$D_IN;
  wire _unnamed__9_2$EN;

  // register cx
  reg [11 : 0] cx;
  wire [11 : 0] cx$D_IN;
  wire cx$EN;

  // register cx2
  reg [11 : 0] cx2;
  wire [11 : 0] cx2$D_IN;
  wire cx2$EN;

  // register kernel
  reg [3 : 0] kernel;
  wire [3 : 0] kernel$D_IN;
  wire kernel$EN;

  // register mem_rCache
  reg [93 : 0] mem_rCache;
  wire [93 : 0] mem_rCache$D_IN;
  wire mem_rCache$EN;

  // register mem_rRdPtr
  reg [12 : 0] mem_rRdPtr;
  wire [12 : 0] mem_rRdPtr$D_IN;
  wire mem_rRdPtr$EN;

  // register mem_rWrPtr
  reg [12 : 0] mem_rWrPtr;
  wire [12 : 0] mem_rWrPtr$D_IN;
  wire mem_rWrPtr$EN;

  // register mx
  reg [7 : 0] mx;
  wire [7 : 0] mx$D_IN;
  wire mx$EN;

  // register p0_rv
  reg [1 : 0] p0_rv;
  wire [1 : 0] p0_rv$D_IN;
  wire p0_rv$EN;

  // register p1_rv
  reg [1 : 0] p1_rv;
  wire [1 : 0] p1_rv$D_IN;
  wire p1_rv$EN;

  // register p2_rv
  reg [1 : 0] p2_rv;
  wire [1 : 0] p2_rv$D_IN;
  wire p2_rv$EN;

  // register p3_rv
  reg [1 : 0] p3_rv;
  wire [1 : 0] p3_rv$D_IN;
  wire p3_rv$EN;

  // register width
  reg [11 : 0] width;
  wire [11 : 0] width$D_IN;
  wire width$EN;

  // ports of submodule inQ
  wire [79 : 0] inQ$D_IN, inQ$D_OUT;
  wire inQ$CLR, inQ$DEQ, inQ$EMPTY_N, inQ$ENQ, inQ$FULL_N;

  // ports of submodule mem_memory
  wire [79 : 0] mem_memory$DIA, mem_memory$DIB, mem_memory$DOB;
  wire [11 : 0] mem_memory$ADDRA, mem_memory$ADDRB;
  wire mem_memory$ENA, mem_memory$ENB, mem_memory$WEA, mem_memory$WEB;

  // rule scheduling signals
  wire WILL_FIRE_RL__activate1, WILL_FIRE_RL_initialLoad;

  // inputs to muxes for submodule ports
  wire [79 : 0] MUX_mem_wDataIn$wset_1__VAL_2;

  // remaining internal signals
  wire [79 : 0] IF_mem_wDataOut_whas__15_THEN_mem_wDataOut_wge_ETC___d126,
		d1__h9275,
		x3__h5818,
		x_wget__h5600;
  wire [23 : 0] x2__h6906,
		x2__h7348,
		x2__h7547,
		x2__h7746,
		x2__h7945,
		x2__h8144,
		x2__h8343,
		x2__h8542,
		x2__h8741,
		x__h7177,
		x__h7377,
		x__h7576,
		x__h7775,
		x__h7974,
		x__h8173,
		x__h8372,
		x__h8571,
		x__h8770;
  wire [12 : 0] x__h5901, x__h5990;
  wire NOT_mem_rRdPtr_read__7_EQ_mem_rWrPtr_read_12_1_ETC___d121,
       NOT_mem_rRdPtr_read__7_PLUS_2048_7_EQ_mem_rWrP_ETC___d89,
       cx2_7_ULT_width_8___d99;

  // action method put
  assign RDY_put = inQ$FULL_N ;

  // actionvalue method get
  assign get =
	     { _unnamed__33,
	       _unnamed__32,
	       _unnamed__31,
	       _unnamed__30,
	       _unnamed__29,
	       _unnamed__28,
	       _unnamed__27,
	       _unnamed__26,
	       _unnamed__25,
	       _unnamed__24,
	       _unnamed__23,
	       _unnamed__22,
	       _unnamed__21,
	       _unnamed__20,
	       _unnamed__19,
	       _unnamed__18,
	       _unnamed__17,
	       _unnamed__16,
	       _unnamed__15,
	       _unnamed__14,
	       _unnamed__13,
	       _unnamed__12,
	       _unnamed__11,
	       _unnamed__10 } ;
  assign RDY_get = p3_rv[1] ;

  // action method configure
  assign RDY_configure = 1'd1 ;

  // submodule inQ
  FIFO2 #(.width(32'd80), .guarded(1'd1)) inQ(.RST(RST_N),
					      .CLK(CLK),
					      .D_IN(inQ$D_IN),
					      .ENQ(inQ$ENQ),
					      .DEQ(inQ$DEQ),
					      .CLR(inQ$CLR),
					      .D_OUT(inQ$D_OUT),
					      .FULL_N(inQ$FULL_N),
					      .EMPTY_N(inQ$EMPTY_N));

  // submodule mem_memory
  BRAM2 #(.PIPELINED(1'd0),
	  .ADDR_WIDTH(32'd12),
	  .DATA_WIDTH(32'd80),
	  .MEMSIZE(13'd4096)) mem_memory(.CLKA(CLK),
					 .CLKB(CLK),
					 .ADDRA(mem_memory$ADDRA),
					 .ADDRB(mem_memory$ADDRB),
					 .DIA(mem_memory$DIA),
					 .DIB(mem_memory$DIB),
					 .WEA(mem_memory$WEA),
					 .WEB(mem_memory$WEB),
					 .ENA(mem_memory$ENA),
					 .ENB(mem_memory$ENB),
					 .DOA(),
					 .DOB(mem_memory$DOB));

  // rule RL_initialLoad
  assign WILL_FIRE_RL_initialLoad =
	     NOT_mem_rRdPtr_read__7_PLUS_2048_7_EQ_mem_rWrP_ETC___d89 &&
	     inQ$EMPTY_N &&
	     cx2_7_ULT_width_8___d99 ;

  // rule RL__activate1
  assign WILL_FIRE_RL__activate1 =
	     NOT_mem_rRdPtr_read__7_PLUS_2048_7_EQ_mem_rWrP_ETC___d89 &&
	     p0_rv[1] &&
	     !p1_rv$port1__read[1] &&
	     !cx2_7_ULT_width_8___d99 ;

  // inputs to muxes for submodule ports
  assign MUX_mem_wDataIn$wset_1__VAL_2 = { 64'd0, _unnamed__40[79:64] } ;

  // inlined wires
  assign mem_pwDequeue$whas =
	     NOT_mem_rRdPtr_read__7_EQ_mem_rWrPtr_read_12_1_ETC___d121 &&
	     !cx2_7_ULT_width_8___d99 ;
  assign mem_pwEnqueue$whas =
	     WILL_FIRE_RL_initialLoad || WILL_FIRE_RL__activate1 ;
  assign p0_rv$port1__read = WILL_FIRE_RL__activate1 ? 2'd0 : p0_rv ;
  assign p0_rv$EN_port1__write =
	     NOT_mem_rRdPtr_read__7_EQ_mem_rWrPtr_read_12_1_ETC___d121 &&
	     !cx2_7_ULT_width_8___d99 ;
  assign p0_rv$port2__read =
	     p0_rv$EN_port1__write ? 2'd3 : p0_rv$port1__read ;
  assign p1_rv$EN_port0__write = p1_rv[1] && !p2_rv$port1__read[1] ;
  assign p1_rv$port1__read = p1_rv$EN_port0__write ? 2'd0 : p1_rv ;
  assign p1_rv$port2__read =
	     WILL_FIRE_RL__activate1 ? 2'd3 : p1_rv$port1__read ;
  assign p2_rv$EN_port0__write = p2_rv[1] && !p3_rv$port1__read[1] ;
  assign p2_rv$port1__read = p2_rv$EN_port0__write ? 2'd0 : p2_rv ;
  assign p2_rv$EN_port1__write = p1_rv[1] && !p2_rv$port1__read[1] ;
  assign p2_rv$port2__read =
	     p2_rv$EN_port1__write ? 2'd3 : p2_rv$port1__read ;
  assign p3_rv$port1__read = EN_get ? 2'd0 : p3_rv ;
  assign p3_rv$EN_port1__write =
	     p2_rv[1] && !p3_rv$port1__read[1] &&
	     cx >= { 8'd0, kernel - 4'd1 } ;
  assign p3_rv$port2__read =
	     p3_rv$EN_port1__write ? 2'd3 : p3_rv$port1__read ;

  // register _unnamed_
  assign _unnamed_$D_IN =
	     IF_mem_wDataOut_whas__15_THEN_mem_wDataOut_wge_ETC___d126[7:0] ;
  assign _unnamed_$EN = mem_pwDequeue$whas ;

  // register _unnamed__0_1
  assign _unnamed__0_1$D_IN = { _unnamed_, _unnamed__1 } ;
  assign _unnamed__0_1$EN = 1'd1 ;

  // register _unnamed__0_2
  assign _unnamed__0_2$D_IN = x__h7177 | x2__h6906 ;
  assign _unnamed__0_2$EN = 1'd1 ;

  // register _unnamed__1
  assign _unnamed__1$D_IN =
	     IF_mem_wDataOut_whas__15_THEN_mem_wDataOut_wge_ETC___d126[15:8] ;
  assign _unnamed__1$EN = mem_pwDequeue$whas ;

  // register _unnamed__10
  assign _unnamed__10$D_IN = { _unnamed__10[15:0], _unnamed__0_2[7:0] } ;
  assign _unnamed__10$EN = p2_rv[1] && !p3_rv$port1__read[1] ;

  // register _unnamed__11
  assign _unnamed__11$D_IN = { _unnamed__11[15:0], _unnamed__0_2[15:8] } ;
  assign _unnamed__11$EN = p2_rv[1] && !p3_rv$port1__read[1] ;

  // register _unnamed__12
  assign _unnamed__12$D_IN = { _unnamed__12[15:0], _unnamed__0_2[23:16] } ;
  assign _unnamed__12$EN = p2_rv[1] && !p3_rv$port1__read[1] ;

  // register _unnamed__13
  assign _unnamed__13$D_IN = { _unnamed__13[15:0], _unnamed__1_2[7:0] } ;
  assign _unnamed__13$EN = p2_rv[1] && !p3_rv$port1__read[1] ;

  // register _unnamed__14
  assign _unnamed__14$D_IN = { _unnamed__14[15:0], _unnamed__1_2[15:8] } ;
  assign _unnamed__14$EN = p2_rv[1] && !p3_rv$port1__read[1] ;

  // register _unnamed__15
  assign _unnamed__15$D_IN = { _unnamed__15[15:0], _unnamed__1_2[23:16] } ;
  assign _unnamed__15$EN = p2_rv[1] && !p3_rv$port1__read[1] ;

  // register _unnamed__16
  assign _unnamed__16$D_IN = { _unnamed__16[15:0], _unnamed__2_2[7:0] } ;
  assign _unnamed__16$EN = p2_rv[1] && !p3_rv$port1__read[1] ;

  // register _unnamed__17
  assign _unnamed__17$D_IN = { _unnamed__17[15:0], _unnamed__2_2[15:8] } ;
  assign _unnamed__17$EN = p2_rv[1] && !p3_rv$port1__read[1] ;

  // register _unnamed__18
  assign _unnamed__18$D_IN = { _unnamed__18[15:0], _unnamed__2_2[23:16] } ;
  assign _unnamed__18$EN = p2_rv[1] && !p3_rv$port1__read[1] ;

  // register _unnamed__19
  assign _unnamed__19$D_IN = { _unnamed__19[15:0], _unnamed__3_2[7:0] } ;
  assign _unnamed__19$EN = p2_rv[1] && !p3_rv$port1__read[1] ;

  // register _unnamed__1_1
  assign _unnamed__1_1$D_IN = { _unnamed__1, _unnamed__2 } ;
  assign _unnamed__1_1$EN = 1'd1 ;

  // register _unnamed__1_2
  assign _unnamed__1_2$D_IN = x__h7377 | x2__h7348 ;
  assign _unnamed__1_2$EN = 1'd1 ;

  // register _unnamed__2
  assign _unnamed__2$D_IN =
	     IF_mem_wDataOut_whas__15_THEN_mem_wDataOut_wge_ETC___d126[23:16] ;
  assign _unnamed__2$EN = mem_pwDequeue$whas ;

  // register _unnamed__20
  assign _unnamed__20$D_IN = { _unnamed__20[15:0], _unnamed__3_2[15:8] } ;
  assign _unnamed__20$EN = p2_rv[1] && !p3_rv$port1__read[1] ;

  // register _unnamed__21
  assign _unnamed__21$D_IN = { _unnamed__21[15:0], _unnamed__3_2[23:16] } ;
  assign _unnamed__21$EN = p2_rv[1] && !p3_rv$port1__read[1] ;

  // register _unnamed__22
  assign _unnamed__22$D_IN = { _unnamed__22[15:0], _unnamed__4_2[7:0] } ;
  assign _unnamed__22$EN = p2_rv[1] && !p3_rv$port1__read[1] ;

  // register _unnamed__23
  assign _unnamed__23$D_IN = { _unnamed__23[15:0], _unnamed__4_2[15:8] } ;
  assign _unnamed__23$EN = p2_rv[1] && !p3_rv$port1__read[1] ;

  // register _unnamed__24
  assign _unnamed__24$D_IN = { _unnamed__24[15:0], _unnamed__4_2[23:16] } ;
  assign _unnamed__24$EN = p2_rv[1] && !p3_rv$port1__read[1] ;

  // register _unnamed__25
  assign _unnamed__25$D_IN = { _unnamed__25[15:0], _unnamed__5_2[7:0] } ;
  assign _unnamed__25$EN = p2_rv[1] && !p3_rv$port1__read[1] ;

  // register _unnamed__26
  assign _unnamed__26$D_IN = { _unnamed__26[15:0], _unnamed__5_2[15:8] } ;
  assign _unnamed__26$EN = p2_rv[1] && !p3_rv$port1__read[1] ;

  // register _unnamed__27
  assign _unnamed__27$D_IN = { _unnamed__27[15:0], _unnamed__5_2[23:16] } ;
  assign _unnamed__27$EN = p2_rv[1] && !p3_rv$port1__read[1] ;

  // register _unnamed__28
  assign _unnamed__28$D_IN = { _unnamed__28[15:0], _unnamed__6_2[7:0] } ;
  assign _unnamed__28$EN = p2_rv[1] && !p3_rv$port1__read[1] ;

  // register _unnamed__29
  assign _unnamed__29$D_IN = { _unnamed__29[15:0], _unnamed__6_2[15:8] } ;
  assign _unnamed__29$EN = p2_rv[1] && !p3_rv$port1__read[1] ;

  // register _unnamed__2_1
  assign _unnamed__2_1$D_IN = { _unnamed__2, _unnamed__3 } ;
  assign _unnamed__2_1$EN = 1'd1 ;

  // register _unnamed__2_2
  assign _unnamed__2_2$D_IN = x__h7576 | x2__h7547 ;
  assign _unnamed__2_2$EN = 1'd1 ;

  // register _unnamed__3
  assign _unnamed__3$D_IN =
	     IF_mem_wDataOut_whas__15_THEN_mem_wDataOut_wge_ETC___d126[31:24] ;
  assign _unnamed__3$EN = mem_pwDequeue$whas ;

  // register _unnamed__30
  assign _unnamed__30$D_IN = { _unnamed__30[15:0], _unnamed__6_2[23:16] } ;
  assign _unnamed__30$EN = p2_rv[1] && !p3_rv$port1__read[1] ;

  // register _unnamed__31
  assign _unnamed__31$D_IN = { _unnamed__31[15:0], _unnamed__7_2[7:0] } ;
  assign _unnamed__31$EN = p2_rv[1] && !p3_rv$port1__read[1] ;

  // register _unnamed__32
  assign _unnamed__32$D_IN = { _unnamed__32[15:0], _unnamed__7_2[15:8] } ;
  assign _unnamed__32$EN = p2_rv[1] && !p3_rv$port1__read[1] ;

  // register _unnamed__33
  assign _unnamed__33$D_IN = { _unnamed__33[15:0], _unnamed__7_2[23:16] } ;
  assign _unnamed__33$EN = p2_rv[1] && !p3_rv$port1__read[1] ;

  // register _unnamed__34
  assign _unnamed__34$D_IN = { _unnamed__34[15:0], _unnamed__8_2[7:0] } ;
  assign _unnamed__34$EN = p2_rv[1] && !p3_rv$port1__read[1] ;

  // register _unnamed__35
  assign _unnamed__35$D_IN = { _unnamed__35[15:0], _unnamed__8_2[15:8] } ;
  assign _unnamed__35$EN = p2_rv[1] && !p3_rv$port1__read[1] ;

  // register _unnamed__36
  assign _unnamed__36$D_IN = { _unnamed__36[15:0], _unnamed__8_2[23:16] } ;
  assign _unnamed__36$EN = p2_rv[1] && !p3_rv$port1__read[1] ;

  // register _unnamed__37
  assign _unnamed__37$D_IN = { _unnamed__37[15:0], _unnamed__9_2[7:0] } ;
  assign _unnamed__37$EN = p2_rv[1] && !p3_rv$port1__read[1] ;

  // register _unnamed__38
  assign _unnamed__38$D_IN = { _unnamed__38[15:0], _unnamed__9_2[15:8] } ;
  assign _unnamed__38$EN = p2_rv[1] && !p3_rv$port1__read[1] ;

  // register _unnamed__39
  assign _unnamed__39$D_IN = { _unnamed__39[15:0], _unnamed__9_2[23:16] } ;
  assign _unnamed__39$EN = p2_rv[1] && !p3_rv$port1__read[1] ;

  // register _unnamed__3_1
  assign _unnamed__3_1$D_IN = { _unnamed__3, _unnamed__4 } ;
  assign _unnamed__3_1$EN = 1'd1 ;

  // register _unnamed__3_2
  assign _unnamed__3_2$D_IN = x__h7775 | x2__h7746 ;
  assign _unnamed__3_2$EN = 1'd1 ;

  // register _unnamed__4
  assign _unnamed__4$D_IN =
	     IF_mem_wDataOut_whas__15_THEN_mem_wDataOut_wge_ETC___d126[39:32] ;
  assign _unnamed__4$EN = mem_pwDequeue$whas ;

  // register _unnamed__40
  assign _unnamed__40$D_IN = 80'h0 ;
  assign _unnamed__40$EN = 1'b0 ;

  // register _unnamed__4_1
  assign _unnamed__4_1$D_IN = { _unnamed__4, _unnamed__5 } ;
  assign _unnamed__4_1$EN = 1'd1 ;

  // register _unnamed__4_2
  assign _unnamed__4_2$D_IN = x__h7974 | x2__h7945 ;
  assign _unnamed__4_2$EN = 1'd1 ;

  // register _unnamed__5
  assign _unnamed__5$D_IN =
	     IF_mem_wDataOut_whas__15_THEN_mem_wDataOut_wge_ETC___d126[47:40] ;
  assign _unnamed__5$EN = mem_pwDequeue$whas ;

  // register _unnamed__5_1
  assign _unnamed__5_1$D_IN = { _unnamed__5, _unnamed__6 } ;
  assign _unnamed__5_1$EN = 1'd1 ;

  // register _unnamed__5_2
  assign _unnamed__5_2$D_IN = x__h8173 | x2__h8144 ;
  assign _unnamed__5_2$EN = 1'd1 ;

  // register _unnamed__6
  assign _unnamed__6$D_IN =
	     IF_mem_wDataOut_whas__15_THEN_mem_wDataOut_wge_ETC___d126[55:48] ;
  assign _unnamed__6$EN = mem_pwDequeue$whas ;

  // register _unnamed__6_1
  assign _unnamed__6_1$D_IN = { _unnamed__6, _unnamed__7 } ;
  assign _unnamed__6_1$EN = 1'd1 ;

  // register _unnamed__6_2
  assign _unnamed__6_2$D_IN = x__h8372 | x2__h8343 ;
  assign _unnamed__6_2$EN = 1'd1 ;

  // register _unnamed__7
  assign _unnamed__7$D_IN =
	     IF_mem_wDataOut_whas__15_THEN_mem_wDataOut_wge_ETC___d126[63:56] ;
  assign _unnamed__7$EN = mem_pwDequeue$whas ;

  // register _unnamed__7_1
  assign _unnamed__7_1$D_IN = { _unnamed__7, _unnamed__8 } ;
  assign _unnamed__7_1$EN = 1'd1 ;

  // register _unnamed__7_2
  assign _unnamed__7_2$D_IN = x__h8571 | x2__h8542 ;
  assign _unnamed__7_2$EN = 1'd1 ;

  // register _unnamed__8
  assign _unnamed__8$D_IN =
	     IF_mem_wDataOut_whas__15_THEN_mem_wDataOut_wge_ETC___d126[71:64] ;
  assign _unnamed__8$EN = mem_pwDequeue$whas ;

  // register _unnamed__8_1
  assign _unnamed__8_1$D_IN = { _unnamed__8, _unnamed__9 } ;
  assign _unnamed__8_1$EN = 1'd1 ;

  // register _unnamed__8_2
  assign _unnamed__8_2$D_IN = x__h8770 | x2__h8741 ;
  assign _unnamed__8_2$EN = 1'd1 ;

  // register _unnamed__9
  assign _unnamed__9$D_IN =
	     IF_mem_wDataOut_whas__15_THEN_mem_wDataOut_wge_ETC___d126[79:72] ;
  assign _unnamed__9$EN = mem_pwDequeue$whas ;

  // register _unnamed__9_1
  assign _unnamed__9_1$D_IN = 16'h0 ;
  assign _unnamed__9_1$EN = 1'b0 ;

  // register _unnamed__9_2
  assign _unnamed__9_2$D_IN = 24'h0 ;
  assign _unnamed__9_2$EN = 1'b0 ;

  // register cx
  assign cx$D_IN = (cx == width - 12'd1) ? 12'd0 : cx + 12'd1 ;
  assign cx$EN = p2_rv[1] && !p3_rv$port1__read[1] ;

  // register cx2
  assign cx2$D_IN = cx2 + 12'd1 ;
  assign cx2$EN = WILL_FIRE_RL_initialLoad ;

  // register kernel
  assign kernel$D_IN = 4'd3 ;
  assign kernel$EN = EN_configure ;

  // register mem_rCache
  assign mem_rCache$D_IN = { 1'd1, mem_rWrPtr, x3__h5818 } ;
  assign mem_rCache$EN = mem_pwEnqueue$whas ;

  // register mem_rRdPtr
  assign mem_rRdPtr$D_IN = x__h5990 ;
  assign mem_rRdPtr$EN = mem_pwDequeue$whas ;

  // register mem_rWrPtr
  assign mem_rWrPtr$D_IN = x__h5901 ;
  assign mem_rWrPtr$EN = mem_pwEnqueue$whas ;

  // register mx
  assign mx$D_IN = configure_m ;
  assign mx$EN = EN_configure ;

  // register p0_rv
  assign p0_rv$D_IN = p0_rv$port2__read ;
  assign p0_rv$EN = 1'b1 ;

  // register p1_rv
  assign p1_rv$D_IN = p1_rv$port2__read ;
  assign p1_rv$EN = 1'b1 ;

  // register p2_rv
  assign p2_rv$D_IN = p2_rv$port2__read ;
  assign p2_rv$EN = 1'b1 ;

  // register p3_rv
  assign p3_rv$D_IN = p3_rv$port2__read ;
  assign p3_rv$EN = 1'b1 ;

  // register width
  assign width$D_IN = configure_wx ;
  assign width$EN = EN_configure ;

  // submodule inQ
  assign inQ$D_IN = put_datas ;
  assign inQ$ENQ = EN_put ;
  assign inQ$DEQ =
	     WILL_FIRE_RL_initialLoad ||
	     NOT_mem_rRdPtr_read__7_EQ_mem_rWrPtr_read_12_1_ETC___d121 &&
	     !cx2_7_ULT_width_8___d99 ;
  assign inQ$CLR = 1'b0 ;

  // submodule mem_memory
  assign mem_memory$ADDRA = mem_rWrPtr[11:0] ;
  assign mem_memory$ADDRB =
	     mem_pwDequeue$whas ? x__h5990[11:0] : mem_rRdPtr[11:0] ;
  assign mem_memory$DIA = x3__h5818 ;
  assign mem_memory$DIB = 80'hAAAAAAAAAAAAAAAAAAAA /* unspecified value */  ;
  assign mem_memory$WEA = mem_pwEnqueue$whas ;
  assign mem_memory$WEB = 1'd0 ;
  assign mem_memory$ENA = 1'b1 ;
  assign mem_memory$ENB = 1'b1 ;

  // remaining internal signals
  assign IF_mem_wDataOut_whas__15_THEN_mem_wDataOut_wge_ETC___d126 =
	     d1__h9275 | inQ$D_OUT ;
  assign NOT_mem_rRdPtr_read__7_EQ_mem_rWrPtr_read_12_1_ETC___d121 =
	     mem_rRdPtr != mem_rWrPtr && inQ$EMPTY_N &&
	     !p0_rv$port1__read[1] ;
  assign NOT_mem_rRdPtr_read__7_PLUS_2048_7_EQ_mem_rWrP_ETC___d89 =
	     mem_rRdPtr + 13'd2048 != mem_rWrPtr ;
  assign cx2_7_ULT_width_8___d99 = cx2 < width ;
  assign d1__h9275 =
	     (mem_rCache[93] && mem_rCache[92:80] == mem_rRdPtr) ?
	       mem_rCache[79:0] :
	       mem_memory$DOB ;
  assign x2__h6906 = { 8'd0, _unnamed__1_1 } ;
  assign x2__h7348 = { 8'd0, _unnamed__2_1 } ;
  assign x2__h7547 = { 8'd0, _unnamed__3_1 } ;
  assign x2__h7746 = { 8'd0, _unnamed__4_1 } ;
  assign x2__h7945 = { 8'd0, _unnamed__5_1 } ;
  assign x2__h8144 = { 8'd0, _unnamed__6_1 } ;
  assign x2__h8343 = { 8'd0, _unnamed__7_1 } ;
  assign x2__h8542 = { 8'd0, _unnamed__8_1 } ;
  assign x2__h8741 = { 8'd0, _unnamed__9_1 } ;
  assign x3__h5818 = mem_pwEnqueue$whas ? x_wget__h5600 : 80'd0 ;
  assign x__h5901 = mem_rWrPtr + 13'd1 ;
  assign x__h5990 = mem_rRdPtr + 13'd1 ;
  assign x__h7177 = { _unnamed__0_1, 8'd0 } ;
  assign x__h7377 = { _unnamed__1_1, 8'd0 } ;
  assign x__h7576 = { _unnamed__2_1, 8'd0 } ;
  assign x__h7775 = { _unnamed__3_1, 8'd0 } ;
  assign x__h7974 = { _unnamed__4_1, 8'd0 } ;
  assign x__h8173 = { _unnamed__5_1, 8'd0 } ;
  assign x__h8372 = { _unnamed__6_1, 8'd0 } ;
  assign x__h8571 = { _unnamed__7_1, 8'd0 } ;
  assign x__h8770 = { _unnamed__8_1, 8'd0 } ;
  assign x_wget__h5600 =
	     WILL_FIRE_RL_initialLoad ?
	       inQ$D_OUT :
	       MUX_mem_wDataIn$wset_1__VAL_2 ;

  // handling of inlined registers

  always@(posedge CLK)
  begin
    if (RST_N == `BSV_RESET_VALUE)
      begin
        _unnamed_ <= `BSV_ASSIGNMENT_DELAY 8'd0;
	_unnamed__0_1 <= `BSV_ASSIGNMENT_DELAY 16'd0;
	_unnamed__0_2 <= `BSV_ASSIGNMENT_DELAY 24'd0;
	_unnamed__1 <= `BSV_ASSIGNMENT_DELAY 8'd0;
	_unnamed__10 <= `BSV_ASSIGNMENT_DELAY 24'd0;
	_unnamed__11 <= `BSV_ASSIGNMENT_DELAY 24'd0;
	_unnamed__12 <= `BSV_ASSIGNMENT_DELAY 24'd0;
	_unnamed__13 <= `BSV_ASSIGNMENT_DELAY 24'd0;
	_unnamed__14 <= `BSV_ASSIGNMENT_DELAY 24'd0;
	_unnamed__15 <= `BSV_ASSIGNMENT_DELAY 24'd0;
	_unnamed__16 <= `BSV_ASSIGNMENT_DELAY 24'd0;
	_unnamed__17 <= `BSV_ASSIGNMENT_DELAY 24'd0;
	_unnamed__18 <= `BSV_ASSIGNMENT_DELAY 24'd0;
	_unnamed__19 <= `BSV_ASSIGNMENT_DELAY 24'd0;
	_unnamed__1_1 <= `BSV_ASSIGNMENT_DELAY 16'd0;
	_unnamed__1_2 <= `BSV_ASSIGNMENT_DELAY 24'd0;
	_unnamed__2 <= `BSV_ASSIGNMENT_DELAY 8'd0;
	_unnamed__20 <= `BSV_ASSIGNMENT_DELAY 24'd0;
	_unnamed__21 <= `BSV_ASSIGNMENT_DELAY 24'd0;
	_unnamed__22 <= `BSV_ASSIGNMENT_DELAY 24'd0;
	_unnamed__23 <= `BSV_ASSIGNMENT_DELAY 24'd0;
	_unnamed__24 <= `BSV_ASSIGNMENT_DELAY 24'd0;
	_unnamed__25 <= `BSV_ASSIGNMENT_DELAY 24'd0;
	_unnamed__26 <= `BSV_ASSIGNMENT_DELAY 24'd0;
	_unnamed__27 <= `BSV_ASSIGNMENT_DELAY 24'd0;
	_unnamed__28 <= `BSV_ASSIGNMENT_DELAY 24'd0;
	_unnamed__29 <= `BSV_ASSIGNMENT_DELAY 24'd0;
	_unnamed__2_1 <= `BSV_ASSIGNMENT_DELAY 16'd0;
	_unnamed__2_2 <= `BSV_ASSIGNMENT_DELAY 24'd0;
	_unnamed__3 <= `BSV_ASSIGNMENT_DELAY 8'd0;
	_unnamed__30 <= `BSV_ASSIGNMENT_DELAY 24'd0;
	_unnamed__31 <= `BSV_ASSIGNMENT_DELAY 24'd0;
	_unnamed__32 <= `BSV_ASSIGNMENT_DELAY 24'd0;
	_unnamed__33 <= `BSV_ASSIGNMENT_DELAY 24'd0;
	_unnamed__34 <= `BSV_ASSIGNMENT_DELAY 24'd0;
	_unnamed__35 <= `BSV_ASSIGNMENT_DELAY 24'd0;
	_unnamed__36 <= `BSV_ASSIGNMENT_DELAY 24'd0;
	_unnamed__37 <= `BSV_ASSIGNMENT_DELAY 24'd0;
	_unnamed__38 <= `BSV_ASSIGNMENT_DELAY 24'd0;
	_unnamed__39 <= `BSV_ASSIGNMENT_DELAY 24'd0;
	_unnamed__3_1 <= `BSV_ASSIGNMENT_DELAY 16'd0;
	_unnamed__3_2 <= `BSV_ASSIGNMENT_DELAY 24'd0;
	_unnamed__4 <= `BSV_ASSIGNMENT_DELAY 8'd0;
	_unnamed__40 <= `BSV_ASSIGNMENT_DELAY 80'd0;
	_unnamed__4_1 <= `BSV_ASSIGNMENT_DELAY 16'd0;
	_unnamed__4_2 <= `BSV_ASSIGNMENT_DELAY 24'd0;
	_unnamed__5 <= `BSV_ASSIGNMENT_DELAY 8'd0;
	_unnamed__5_1 <= `BSV_ASSIGNMENT_DELAY 16'd0;
	_unnamed__5_2 <= `BSV_ASSIGNMENT_DELAY 24'd0;
	_unnamed__6 <= `BSV_ASSIGNMENT_DELAY 8'd0;
	_unnamed__6_1 <= `BSV_ASSIGNMENT_DELAY 16'd0;
	_unnamed__6_2 <= `BSV_ASSIGNMENT_DELAY 24'd0;
	_unnamed__7 <= `BSV_ASSIGNMENT_DELAY 8'd0;
	_unnamed__7_1 <= `BSV_ASSIGNMENT_DELAY 16'd0;
	_unnamed__7_2 <= `BSV_ASSIGNMENT_DELAY 24'd0;
	_unnamed__8 <= `BSV_ASSIGNMENT_DELAY 8'd0;
	_unnamed__8_1 <= `BSV_ASSIGNMENT_DELAY 16'd0;
	_unnamed__8_2 <= `BSV_ASSIGNMENT_DELAY 24'd0;
	_unnamed__9 <= `BSV_ASSIGNMENT_DELAY 8'd0;
	_unnamed__9_1 <= `BSV_ASSIGNMENT_DELAY 16'd0;
	_unnamed__9_2 <= `BSV_ASSIGNMENT_DELAY 24'd0;
	cx <= `BSV_ASSIGNMENT_DELAY 12'd0;
	cx2 <= `BSV_ASSIGNMENT_DELAY 12'd0;
	kernel <= `BSV_ASSIGNMENT_DELAY 4'd0;
	mem_rCache <= `BSV_ASSIGNMENT_DELAY 94'h0AAAAAAAAAAAAAAAAAAAAAAA;
	mem_rRdPtr <= `BSV_ASSIGNMENT_DELAY 13'd0;
	mem_rWrPtr <= `BSV_ASSIGNMENT_DELAY 13'd0;
	mx <= `BSV_ASSIGNMENT_DELAY 8'd0;
	p0_rv <= `BSV_ASSIGNMENT_DELAY 2'd0;
	p1_rv <= `BSV_ASSIGNMENT_DELAY 2'd0;
	p2_rv <= `BSV_ASSIGNMENT_DELAY 2'd0;
	p3_rv <= `BSV_ASSIGNMENT_DELAY 2'd0;
	width <= `BSV_ASSIGNMENT_DELAY 12'd16;
      end
    else
      begin
        if (_unnamed_$EN) _unnamed_ <= `BSV_ASSIGNMENT_DELAY _unnamed_$D_IN;
	if (_unnamed__0_1$EN)
	  _unnamed__0_1 <= `BSV_ASSIGNMENT_DELAY _unnamed__0_1$D_IN;
	if (_unnamed__0_2$EN)
	  _unnamed__0_2 <= `BSV_ASSIGNMENT_DELAY _unnamed__0_2$D_IN;
	if (_unnamed__1$EN)
	  _unnamed__1 <= `BSV_ASSIGNMENT_DELAY _unnamed__1$D_IN;
	if (_unnamed__10$EN)
	  _unnamed__10 <= `BSV_ASSIGNMENT_DELAY _unnamed__10$D_IN;
	if (_unnamed__11$EN)
	  _unnamed__11 <= `BSV_ASSIGNMENT_DELAY _unnamed__11$D_IN;
	if (_unnamed__12$EN)
	  _unnamed__12 <= `BSV_ASSIGNMENT_DELAY _unnamed__12$D_IN;
	if (_unnamed__13$EN)
	  _unnamed__13 <= `BSV_ASSIGNMENT_DELAY _unnamed__13$D_IN;
	if (_unnamed__14$EN)
	  _unnamed__14 <= `BSV_ASSIGNMENT_DELAY _unnamed__14$D_IN;
	if (_unnamed__15$EN)
	  _unnamed__15 <= `BSV_ASSIGNMENT_DELAY _unnamed__15$D_IN;
	if (_unnamed__16$EN)
	  _unnamed__16 <= `BSV_ASSIGNMENT_DELAY _unnamed__16$D_IN;
	if (_unnamed__17$EN)
	  _unnamed__17 <= `BSV_ASSIGNMENT_DELAY _unnamed__17$D_IN;
	if (_unnamed__18$EN)
	  _unnamed__18 <= `BSV_ASSIGNMENT_DELAY _unnamed__18$D_IN;
	if (_unnamed__19$EN)
	  _unnamed__19 <= `BSV_ASSIGNMENT_DELAY _unnamed__19$D_IN;
	if (_unnamed__1_1$EN)
	  _unnamed__1_1 <= `BSV_ASSIGNMENT_DELAY _unnamed__1_1$D_IN;
	if (_unnamed__1_2$EN)
	  _unnamed__1_2 <= `BSV_ASSIGNMENT_DELAY _unnamed__1_2$D_IN;
	if (_unnamed__2$EN)
	  _unnamed__2 <= `BSV_ASSIGNMENT_DELAY _unnamed__2$D_IN;
	if (_unnamed__20$EN)
	  _unnamed__20 <= `BSV_ASSIGNMENT_DELAY _unnamed__20$D_IN;
	if (_unnamed__21$EN)
	  _unnamed__21 <= `BSV_ASSIGNMENT_DELAY _unnamed__21$D_IN;
	if (_unnamed__22$EN)
	  _unnamed__22 <= `BSV_ASSIGNMENT_DELAY _unnamed__22$D_IN;
	if (_unnamed__23$EN)
	  _unnamed__23 <= `BSV_ASSIGNMENT_DELAY _unnamed__23$D_IN;
	if (_unnamed__24$EN)
	  _unnamed__24 <= `BSV_ASSIGNMENT_DELAY _unnamed__24$D_IN;
	if (_unnamed__25$EN)
	  _unnamed__25 <= `BSV_ASSIGNMENT_DELAY _unnamed__25$D_IN;
	if (_unnamed__26$EN)
	  _unnamed__26 <= `BSV_ASSIGNMENT_DELAY _unnamed__26$D_IN;
	if (_unnamed__27$EN)
	  _unnamed__27 <= `BSV_ASSIGNMENT_DELAY _unnamed__27$D_IN;
	if (_unnamed__28$EN)
	  _unnamed__28 <= `BSV_ASSIGNMENT_DELAY _unnamed__28$D_IN;
	if (_unnamed__29$EN)
	  _unnamed__29 <= `BSV_ASSIGNMENT_DELAY _unnamed__29$D_IN;
	if (_unnamed__2_1$EN)
	  _unnamed__2_1 <= `BSV_ASSIGNMENT_DELAY _unnamed__2_1$D_IN;
	if (_unnamed__2_2$EN)
	  _unnamed__2_2 <= `BSV_ASSIGNMENT_DELAY _unnamed__2_2$D_IN;
	if (_unnamed__3$EN)
	  _unnamed__3 <= `BSV_ASSIGNMENT_DELAY _unnamed__3$D_IN;
	if (_unnamed__30$EN)
	  _unnamed__30 <= `BSV_ASSIGNMENT_DELAY _unnamed__30$D_IN;
	if (_unnamed__31$EN)
	  _unnamed__31 <= `BSV_ASSIGNMENT_DELAY _unnamed__31$D_IN;
	if (_unnamed__32$EN)
	  _unnamed__32 <= `BSV_ASSIGNMENT_DELAY _unnamed__32$D_IN;
	if (_unnamed__33$EN)
	  _unnamed__33 <= `BSV_ASSIGNMENT_DELAY _unnamed__33$D_IN;
	if (_unnamed__34$EN)
	  _unnamed__34 <= `BSV_ASSIGNMENT_DELAY _unnamed__34$D_IN;
	if (_unnamed__35$EN)
	  _unnamed__35 <= `BSV_ASSIGNMENT_DELAY _unnamed__35$D_IN;
	if (_unnamed__36$EN)
	  _unnamed__36 <= `BSV_ASSIGNMENT_DELAY _unnamed__36$D_IN;
	if (_unnamed__37$EN)
	  _unnamed__37 <= `BSV_ASSIGNMENT_DELAY _unnamed__37$D_IN;
	if (_unnamed__38$EN)
	  _unnamed__38 <= `BSV_ASSIGNMENT_DELAY _unnamed__38$D_IN;
	if (_unnamed__39$EN)
	  _unnamed__39 <= `BSV_ASSIGNMENT_DELAY _unnamed__39$D_IN;
	if (_unnamed__3_1$EN)
	  _unnamed__3_1 <= `BSV_ASSIGNMENT_DELAY _unnamed__3_1$D_IN;
	if (_unnamed__3_2$EN)
	  _unnamed__3_2 <= `BSV_ASSIGNMENT_DELAY _unnamed__3_2$D_IN;
	if (_unnamed__4$EN)
	  _unnamed__4 <= `BSV_ASSIGNMENT_DELAY _unnamed__4$D_IN;
	if (_unnamed__40$EN)
	  _unnamed__40 <= `BSV_ASSIGNMENT_DELAY _unnamed__40$D_IN;
	if (_unnamed__4_1$EN)
	  _unnamed__4_1 <= `BSV_ASSIGNMENT_DELAY _unnamed__4_1$D_IN;
	if (_unnamed__4_2$EN)
	  _unnamed__4_2 <= `BSV_ASSIGNMENT_DELAY _unnamed__4_2$D_IN;
	if (_unnamed__5$EN)
	  _unnamed__5 <= `BSV_ASSIGNMENT_DELAY _unnamed__5$D_IN;
	if (_unnamed__5_1$EN)
	  _unnamed__5_1 <= `BSV_ASSIGNMENT_DELAY _unnamed__5_1$D_IN;
	if (_unnamed__5_2$EN)
	  _unnamed__5_2 <= `BSV_ASSIGNMENT_DELAY _unnamed__5_2$D_IN;
	if (_unnamed__6$EN)
	  _unnamed__6 <= `BSV_ASSIGNMENT_DELAY _unnamed__6$D_IN;
	if (_unnamed__6_1$EN)
	  _unnamed__6_1 <= `BSV_ASSIGNMENT_DELAY _unnamed__6_1$D_IN;
	if (_unnamed__6_2$EN)
	  _unnamed__6_2 <= `BSV_ASSIGNMENT_DELAY _unnamed__6_2$D_IN;
	if (_unnamed__7$EN)
	  _unnamed__7 <= `BSV_ASSIGNMENT_DELAY _unnamed__7$D_IN;
	if (_unnamed__7_1$EN)
	  _unnamed__7_1 <= `BSV_ASSIGNMENT_DELAY _unnamed__7_1$D_IN;
	if (_unnamed__7_2$EN)
	  _unnamed__7_2 <= `BSV_ASSIGNMENT_DELAY _unnamed__7_2$D_IN;
	if (_unnamed__8$EN)
	  _unnamed__8 <= `BSV_ASSIGNMENT_DELAY _unnamed__8$D_IN;
	if (_unnamed__8_1$EN)
	  _unnamed__8_1 <= `BSV_ASSIGNMENT_DELAY _unnamed__8_1$D_IN;
	if (_unnamed__8_2$EN)
	  _unnamed__8_2 <= `BSV_ASSIGNMENT_DELAY _unnamed__8_2$D_IN;
	if (_unnamed__9$EN)
	  _unnamed__9 <= `BSV_ASSIGNMENT_DELAY _unnamed__9$D_IN;
	if (_unnamed__9_1$EN)
	  _unnamed__9_1 <= `BSV_ASSIGNMENT_DELAY _unnamed__9_1$D_IN;
	if (_unnamed__9_2$EN)
	  _unnamed__9_2 <= `BSV_ASSIGNMENT_DELAY _unnamed__9_2$D_IN;
	if (cx$EN) cx <= `BSV_ASSIGNMENT_DELAY cx$D_IN;
	if (cx2$EN) cx2 <= `BSV_ASSIGNMENT_DELAY cx2$D_IN;
	if (kernel$EN) kernel <= `BSV_ASSIGNMENT_DELAY kernel$D_IN;
	if (mem_rCache$EN)
	  mem_rCache <= `BSV_ASSIGNMENT_DELAY mem_rCache$D_IN;
	if (mem_rRdPtr$EN)
	  mem_rRdPtr <= `BSV_ASSIGNMENT_DELAY mem_rRdPtr$D_IN;
	if (mem_rWrPtr$EN)
	  mem_rWrPtr <= `BSV_ASSIGNMENT_DELAY mem_rWrPtr$D_IN;
	if (mx$EN) mx <= `BSV_ASSIGNMENT_DELAY mx$D_IN;
	if (p0_rv$EN) p0_rv <= `BSV_ASSIGNMENT_DELAY p0_rv$D_IN;
	if (p1_rv$EN) p1_rv <= `BSV_ASSIGNMENT_DELAY p1_rv$D_IN;
	if (p2_rv$EN) p2_rv <= `BSV_ASSIGNMENT_DELAY p2_rv$D_IN;
	if (p3_rv$EN) p3_rv <= `BSV_ASSIGNMENT_DELAY p3_rv$D_IN;
	if (width$EN) width <= `BSV_ASSIGNMENT_DELAY width$D_IN;
      end
  end

  // synopsys translate_off
  `ifdef BSV_NO_INITIAL_BLOCKS
  `else // not BSV_NO_INITIAL_BLOCKS
  initial
  begin
    _unnamed_ = 8'hAA;
    _unnamed__0_1 = 16'hAAAA;
    _unnamed__0_2 = 24'hAAAAAA;
    _unnamed__1 = 8'hAA;
    _unnamed__10 = 24'hAAAAAA;
    _unnamed__11 = 24'hAAAAAA;
    _unnamed__12 = 24'hAAAAAA;
    _unnamed__13 = 24'hAAAAAA;
    _unnamed__14 = 24'hAAAAAA;
    _unnamed__15 = 24'hAAAAAA;
    _unnamed__16 = 24'hAAAAAA;
    _unnamed__17 = 24'hAAAAAA;
    _unnamed__18 = 24'hAAAAAA;
    _unnamed__19 = 24'hAAAAAA;
    _unnamed__1_1 = 16'hAAAA;
    _unnamed__1_2 = 24'hAAAAAA;
    _unnamed__2 = 8'hAA;
    _unnamed__20 = 24'hAAAAAA;
    _unnamed__21 = 24'hAAAAAA;
    _unnamed__22 = 24'hAAAAAA;
    _unnamed__23 = 24'hAAAAAA;
    _unnamed__24 = 24'hAAAAAA;
    _unnamed__25 = 24'hAAAAAA;
    _unnamed__26 = 24'hAAAAAA;
    _unnamed__27 = 24'hAAAAAA;
    _unnamed__28 = 24'hAAAAAA;
    _unnamed__29 = 24'hAAAAAA;
    _unnamed__2_1 = 16'hAAAA;
    _unnamed__2_2 = 24'hAAAAAA;
    _unnamed__3 = 8'hAA;
    _unnamed__30 = 24'hAAAAAA;
    _unnamed__31 = 24'hAAAAAA;
    _unnamed__32 = 24'hAAAAAA;
    _unnamed__33 = 24'hAAAAAA;
    _unnamed__34 = 24'hAAAAAA;
    _unnamed__35 = 24'hAAAAAA;
    _unnamed__36 = 24'hAAAAAA;
    _unnamed__37 = 24'hAAAAAA;
    _unnamed__38 = 24'hAAAAAA;
    _unnamed__39 = 24'hAAAAAA;
    _unnamed__3_1 = 16'hAAAA;
    _unnamed__3_2 = 24'hAAAAAA;
    _unnamed__4 = 8'hAA;
    _unnamed__40 = 80'hAAAAAAAAAAAAAAAAAAAA;
    _unnamed__4_1 = 16'hAAAA;
    _unnamed__4_2 = 24'hAAAAAA;
    _unnamed__5 = 8'hAA;
    _unnamed__5_1 = 16'hAAAA;
    _unnamed__5_2 = 24'hAAAAAA;
    _unnamed__6 = 8'hAA;
    _unnamed__6_1 = 16'hAAAA;
    _unnamed__6_2 = 24'hAAAAAA;
    _unnamed__7 = 8'hAA;
    _unnamed__7_1 = 16'hAAAA;
    _unnamed__7_2 = 24'hAAAAAA;
    _unnamed__8 = 8'hAA;
    _unnamed__8_1 = 16'hAAAA;
    _unnamed__8_2 = 24'hAAAAAA;
    _unnamed__9 = 8'hAA;
    _unnamed__9_1 = 16'hAAAA;
    _unnamed__9_2 = 24'hAAAAAA;
    cx = 12'hAAA;
    cx2 = 12'hAAA;
    kernel = 4'hA;
    mem_rCache = 94'h2AAAAAAAAAAAAAAAAAAAAAAA;
    mem_rRdPtr = 13'h0AAA;
    mem_rWrPtr = 13'h0AAA;
    mx = 8'hAA;
    p0_rv = 2'h2;
    p1_rv = 2'h2;
    p2_rv = 2'h2;
    p3_rv = 2'h2;
    width = 12'hAAA;
  end
  `endif // BSV_NO_INITIAL_BLOCKS
  // synopsys translate_on
endmodule  // mkMerge

